"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.GitHub = void 0;
const JSII_RTTI_SYMBOL_1 = Symbol.for("jsii.rtti");
const projen_1 = require("projen");
const workflows_model_1 = require("projen/lib/github/workflows-model");
const base_1 = require("../base");
/**
 * GitHub builder implementing all relevant configuration for the project.
 */
class GitHub extends base_1.GitHubBase {
    /**
     * Initializes the GitHub builder.
     * It calls the `initialize()` method immediately after invoking `super(project)`
     * to ensure that all necessary configuration steps are applied.
     * @param project The project to configure GitHub for.
     */
    constructor(project) {
        super(project);
        this.initialize();
    }
    /**
     * File path to GitHub story issue template.
     * @return File path to story issue file.
     * @protected
     */
    get storyIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/story.yml';
    }
    /**
     * @override
     */
    get pullRequestTemplate() {
        return [
            '## Reviewers Checklist',
            '',
            'for complete review list refer to ABS Loop - Review Aspects',
            '',
            '### Organizational Section',
            '',
            '- [ ] PR is assigned to the according story/feature/bug',
            '- [ ] Story/feature/bug is descriptive',
            '- [ ] Story/feature/bug is assigned to according labels',
            '- [ ] Story/feature/bug is assigned to a developer',
            '',
            '### Structure',
            '',
            '- [ ] Readability: Code is easy to understand, with meaningful names for variables, functions, and classes',
            '- [ ] Comments: Meaningful and helpful comments. Code is documented without being over-commented',
            '- [ ] DRY, KISS and YAGNI: Code implements only necessary features; no over-engineering',
            '- [ ] No sensitive data (e.g., passwords, API keys) in the code',
            '- [ ] No major updates for used packages',
            '',
            '### Coding',
            '',
            '- [ ] Model/Binding property changes or renaming does not break the code',
            '- [ ] Model/Binding properties have consistent names (capitalization, lowercase, ..)',
            '- [ ] Type aliases are defined for associations and compositions',
            '- [ ] No hungarian notation (e.g. aList, oModel, ..)',
            '',
            '### Most important (as long as we do not have Test Driven Development in place)',
            '',
            '- [ ] Code is locally tested by developer',
            '',
            '### Second most important',
            '',
            '- [ ] API first: application can be used headless (with the API only)',
            '<!-- Generated by projen. To modify, edit .projenrc.ts and run "npx projen".-->',
        ];
    }
    /**
     * Issue template for the GitHub story configuration.
     * @return Template for the story issue template file.
     * @protected
     */
    get storyIssueTemplate() {
        return [
            'name: 💡 Story',
            'description: As a [role], I [want to], [so that]',
            'title: "[STORY] <title>"',
            'labels: ["type: story"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Description',
            "      description: Provide a brief overview of the story, focusing who want's to do what and why.",
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * @override
     */
    get featureIssueTemplate() {
        return [
            'name: 💡 Feature',
            'description: Story related feature',
            'title: "[FEATURE] <title>"',
            'labels: ["type: feature"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Description',
            '      description: A description of the feature.',
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Task List',
            '      description: Describe the steps to fulfill the feature.',
            '      value: |',
            '        - [ ] My First Task',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * @override
     */
    get releaseWorkflowOptions() {
        return {
            on: {
                pullRequest: {
                    branches: ['dev'],
                    types: ['closed'],
                },
            },
            job: {
                runsOn: ['ubuntu-latest'],
                permissions: {
                    contents: workflows_model_1.JobPermission.WRITE,
                    pullRequests: workflows_model_1.JobPermission.WRITE,
                },
                steps: [
                    {
                        name: 'Bump version and create release',
                        uses: 'dxfrontier/gh-action-release@main',
                        with: {
                            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
                            BRANCH: 'dev',
                        },
                    },
                ],
            },
        };
    }
    /**
     * Workflow deployment template options for the GitHub configuration.
     * @return Options for deployment workflow
     * @protected
     */
    get deploymentWorkflowOptions() {
        return {
            on: {
                pullRequest: {
                    branches: ['dev'],
                    types: ['closed'],
                },
            },
            job: {
                runsOn: ['ubuntu-latest'],
                permissions: {
                    contents: workflows_model_1.JobPermission.WRITE,
                    pullRequests: workflows_model_1.JobPermission.WRITE,
                },
                steps: [
                    {
                        name: 'Deploy to Cloud Foundry',
                        uses: 'dxfrontier/gh-action-deploy-cf@main',
                        with: {
                            CF_IAS_ORIGIN: '${{ secrets.IAS_ORIGIN }}',
                            CF_API_DEV: '${{ secrets.CF_API_DEV }}',
                            CF_ORG_DEV: '${{ secrets.CF_ORG_DEV }}',
                            CF_SPACE_DEV: '${{ secrets.CF_SPACE_DEV }}',
                            CF_USERNAME_DEV: '${{ secrets.CF_USERNAME_DEV }}',
                            CF_PASSWORD_DEV: '${{ secrets.CF_PASSWORD_DEV }}',
                            CF_API_PROD: '${{ secrets.CF_API_PROD }}',
                            CF_ORG_PROD: '${{ secrets.CF_ORG_PROD }}',
                            CF_SPACE_PROD: '${{ secrets.CF_SPACE_PROD }}',
                            CF_USERNAME_PROD: '${{ secrets.CF_USERNAME_PROD }}',
                            CF_PASSWORD_PROD: '${{ secrets.CF_PASSWORD_PROD }}',
                        },
                    },
                ],
            },
        };
    }
    /**
     * Creates the template file for a GitHub story issue.
     * @protected
     */
    createStoryIssue() {
        new projen_1.TextFile(this.project, this.storyIssueFilePath, {
            lines: this.storyIssueTemplate,
        });
    }
    /**
     * @override
     */
    createStaleWorkflow() { }
    /**
     * Creates the template file for a GitHub deployment workflow.
     * @protected
     */
    createDeploymentWorkflow() {
        const workflow = this.project.github?.addWorkflow('Deployment');
        workflow?.on(this.deploymentWorkflowOptions.on);
        workflow?.addJob('deploy', this.deploymentWorkflowOptions.job);
    }
    /**
     * @override
     */
    addTemplates() {
        super.addTemplates();
        this.createStoryIssue();
        this.createDeploymentWorkflow();
    }
}
exports.GitHub = GitHub;
_a = JSII_RTTI_SYMBOL_1;
GitHub[_a] = { fqn: "@dxfrontier/projen-template-projects.GitHub", version: "0.0.0" };
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZ2l0aHViLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vc3JjL2NhcC1zZXJ2aWNlL2dpdGh1Yi50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7OztBQUFBLG1DQUFrQztBQUVsQyx1RUFBa0U7QUFDbEUsa0NBQTREO0FBRzVEOztHQUVHO0FBQ0gsTUFBYSxNQUFPLFNBQVEsaUJBQVU7SUFDcEM7Ozs7O09BS0c7SUFDSCxZQUFZLE9BQThCO1FBQ3hDLEtBQUssQ0FBQyxPQUFPLENBQUMsQ0FBQztRQUNmLElBQUksQ0FBQyxVQUFVLEVBQUUsQ0FBQztJQUNwQixDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMsa0JBQWtCO1FBQzlCLE9BQU8sa0NBQWtDLENBQUM7SUFDNUMsQ0FBQztJQUVEOztPQUVHO0lBQ0gsSUFBYyxtQkFBbUI7UUFDL0IsT0FBTztZQUNMLHdCQUF3QjtZQUN4QixFQUFFO1lBQ0YsNkRBQTZEO1lBQzdELEVBQUU7WUFDRiw0QkFBNEI7WUFDNUIsRUFBRTtZQUNGLHlEQUF5RDtZQUN6RCx3Q0FBd0M7WUFDeEMseURBQXlEO1lBQ3pELG9EQUFvRDtZQUNwRCxFQUFFO1lBQ0YsZUFBZTtZQUNmLEVBQUU7WUFDRiw0R0FBNEc7WUFDNUcsa0dBQWtHO1lBQ2xHLHlGQUF5RjtZQUN6RixpRUFBaUU7WUFDakUsMENBQTBDO1lBQzFDLEVBQUU7WUFDRixZQUFZO1lBQ1osRUFBRTtZQUNGLDBFQUEwRTtZQUMxRSxzRkFBc0Y7WUFDdEYsa0VBQWtFO1lBQ2xFLHNEQUFzRDtZQUN0RCxFQUFFO1lBQ0YsaUZBQWlGO1lBQ2pGLEVBQUU7WUFDRiwyQ0FBMkM7WUFDM0MsRUFBRTtZQUNGLDJCQUEyQjtZQUMzQixFQUFFO1lBQ0YsdUVBQXVFO1lBQ3ZFLGlGQUFpRjtTQUNsRixDQUFDO0lBQ0osQ0FBQztJQUVEOzs7O09BSUc7SUFDSCxJQUFjLGtCQUFrQjtRQUM5QixPQUFPO1lBQ0wsZ0JBQWdCO1lBQ2hCLGtEQUFrRDtZQUNsRCwwQkFBMEI7WUFDMUIseUJBQXlCO1lBQ3pCLE9BQU87WUFDUCxvQkFBb0I7WUFDcEIsaUJBQWlCO1lBQ2pCLDBCQUEwQjtZQUMxQixtR0FBbUc7WUFDbkcsa0JBQWtCO1lBQ2xCLHNCQUFzQjtZQUN0QiwyRUFBMkU7U0FDNUUsQ0FBQztJQUNKLENBQUM7SUFFRDs7T0FFRztJQUNILElBQWMsb0JBQW9CO1FBQ2hDLE9BQU87WUFDTCxrQkFBa0I7WUFDbEIsb0NBQW9DO1lBQ3BDLDRCQUE0QjtZQUM1QiwyQkFBMkI7WUFDM0IsT0FBTztZQUNQLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsMEJBQTBCO1lBQzFCLGtEQUFrRDtZQUNsRCxrQkFBa0I7WUFDbEIsc0JBQXNCO1lBQ3RCLEVBQUU7WUFDRixvQkFBb0I7WUFDcEIsaUJBQWlCO1lBQ2pCLHdCQUF3QjtZQUN4QiwrREFBK0Q7WUFDL0QsZ0JBQWdCO1lBQ2hCLDZCQUE2QjtZQUM3QixrQkFBa0I7WUFDbEIsc0JBQXNCO1lBQ3RCLDJFQUEyRTtTQUM1RSxDQUFDO0lBQ0osQ0FBQztJQUVEOztPQUVHO0lBQ0gsSUFBYyxzQkFBc0I7UUFDbEMsT0FBTztZQUNMLEVBQUUsRUFBRTtnQkFDRixXQUFXLEVBQUU7b0JBQ1gsUUFBUSxFQUFFLENBQUMsS0FBSyxDQUFDO29CQUNqQixLQUFLLEVBQUUsQ0FBQyxRQUFRLENBQUM7aUJBQ2xCO2FBQ0Y7WUFDRCxHQUFHLEVBQUU7Z0JBQ0gsTUFBTSxFQUFFLENBQUMsZUFBZSxDQUFDO2dCQUN6QixXQUFXLEVBQUU7b0JBQ1gsUUFBUSxFQUFFLCtCQUFhLENBQUMsS0FBSztvQkFDN0IsWUFBWSxFQUFFLCtCQUFhLENBQUMsS0FBSztpQkFDbEM7Z0JBQ0QsS0FBSyxFQUFFO29CQUNMO3dCQUNFLElBQUksRUFBRSxpQ0FBaUM7d0JBQ3ZDLElBQUksRUFBRSxtQ0FBbUM7d0JBQ3pDLElBQUksRUFBRTs0QkFDSixZQUFZLEVBQUUsNkJBQTZCOzRCQUMzQyxNQUFNLEVBQUUsS0FBSzt5QkFDZDtxQkFDRjtpQkFDRjthQUNGO1NBQ0YsQ0FBQztJQUNKLENBQUM7SUFFRDs7OztPQUlHO0lBQ0gsSUFBYyx5QkFBeUI7UUFDckMsT0FBTztZQUNMLEVBQUUsRUFBRTtnQkFDRixXQUFXLEVBQUU7b0JBQ1gsUUFBUSxFQUFFLENBQUMsS0FBSyxDQUFDO29CQUNqQixLQUFLLEVBQUUsQ0FBQyxRQUFRLENBQUM7aUJBQ2xCO2FBQ0Y7WUFDRCxHQUFHLEVBQUU7Z0JBQ0gsTUFBTSxFQUFFLENBQUMsZUFBZSxDQUFDO2dCQUN6QixXQUFXLEVBQUU7b0JBQ1gsUUFBUSxFQUFFLCtCQUFhLENBQUMsS0FBSztvQkFDN0IsWUFBWSxFQUFFLCtCQUFhLENBQUMsS0FBSztpQkFDbEM7Z0JBQ0QsS0FBSyxFQUFFO29CQUNMO3dCQUNFLElBQUksRUFBRSx5QkFBeUI7d0JBQy9CLElBQUksRUFBRSxxQ0FBcUM7d0JBQzNDLElBQUksRUFBRTs0QkFDSixhQUFhLEVBQUUsMkJBQTJCOzRCQUMxQyxVQUFVLEVBQUUsMkJBQTJCOzRCQUN2QyxVQUFVLEVBQUUsMkJBQTJCOzRCQUN2QyxZQUFZLEVBQUUsNkJBQTZCOzRCQUMzQyxlQUFlLEVBQUUsZ0NBQWdDOzRCQUNqRCxlQUFlLEVBQUUsZ0NBQWdDOzRCQUNqRCxXQUFXLEVBQUUsNEJBQTRCOzRCQUN6QyxXQUFXLEVBQUUsNEJBQTRCOzRCQUN6QyxhQUFhLEVBQUUsOEJBQThCOzRCQUM3QyxnQkFBZ0IsRUFBRSxpQ0FBaUM7NEJBQ25ELGdCQUFnQixFQUFFLGlDQUFpQzt5QkFDcEQ7cUJBQ0Y7aUJBQ0Y7YUFDRjtTQUNGLENBQUM7SUFDSixDQUFDO0lBRUQ7OztPQUdHO0lBQ08sZ0JBQWdCO1FBQ3hCLElBQUksaUJBQVEsQ0FBQyxJQUFJLENBQUMsT0FBTyxFQUFFLElBQUksQ0FBQyxrQkFBa0IsRUFBRTtZQUNsRCxLQUFLLEVBQUUsSUFBSSxDQUFDLGtCQUFrQjtTQUMvQixDQUFDLENBQUM7SUFDTCxDQUFDO0lBRUQ7O09BRUc7SUFDTyxtQkFBbUIsS0FBVSxDQUFDO0lBRXhDOzs7T0FHRztJQUNPLHdCQUF3QjtRQUNoQyxNQUFNLFFBQVEsR0FBK0IsSUFBSSxDQUFDLE9BQU8sQ0FBQyxNQUFNLEVBQUUsV0FBVyxDQUFDLFlBQVksQ0FBQyxDQUFDO1FBQzVGLFFBQVEsRUFBRSxFQUFFLENBQUMsSUFBSSxDQUFDLHlCQUF5QixDQUFDLEVBQUUsQ0FBQyxDQUFDO1FBQ2hELFFBQVEsRUFBRSxNQUFNLENBQUMsUUFBUSxFQUFFLElBQUksQ0FBQyx5QkFBeUIsQ0FBQyxHQUFHLENBQUMsQ0FBQztJQUNqRSxDQUFDO0lBRUQ7O09BRUc7SUFDTyxZQUFZO1FBQ3BCLEtBQUssQ0FBQyxZQUFZLEVBQUUsQ0FBQztRQUNyQixJQUFJLENBQUMsZ0JBQWdCLEVBQUUsQ0FBQztRQUN4QixJQUFJLENBQUMsd0JBQXdCLEVBQUUsQ0FBQztJQUNsQyxDQUFDOztBQTNOSCx3QkE0TkMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBUZXh0RmlsZSB9IGZyb20gJ3Byb2plbic7XG5pbXBvcnQgeyBHaXRodWJXb3JrZmxvdyB9IGZyb20gJ3Byb2plbi9saWIvZ2l0aHViJztcbmltcG9ydCB7IEpvYlBlcm1pc3Npb24gfSBmcm9tICdwcm9qZW4vbGliL2dpdGh1Yi93b3JrZmxvd3MtbW9kZWwnO1xuaW1wb3J0IHsgR2l0SHViQmFzZSwgVHlwZVNjcmlwdFByb2plY3RCYXNlIH0gZnJvbSAnLi4vYmFzZSc7XG5pbXBvcnQgeyBXb3JrZmxvd09wdGlvbnMgfSBmcm9tICcuLi90eXBlcyc7XG5cbi8qKlxuICogR2l0SHViIGJ1aWxkZXIgaW1wbGVtZW50aW5nIGFsbCByZWxldmFudCBjb25maWd1cmF0aW9uIGZvciB0aGUgcHJvamVjdC5cbiAqL1xuZXhwb3J0IGNsYXNzIEdpdEh1YiBleHRlbmRzIEdpdEh1YkJhc2Uge1xuICAvKipcbiAgICogSW5pdGlhbGl6ZXMgdGhlIEdpdEh1YiBidWlsZGVyLlxuICAgKiBJdCBjYWxscyB0aGUgYGluaXRpYWxpemUoKWAgbWV0aG9kIGltbWVkaWF0ZWx5IGFmdGVyIGludm9raW5nIGBzdXBlcihwcm9qZWN0KWBcbiAgICogdG8gZW5zdXJlIHRoYXQgYWxsIG5lY2Vzc2FyeSBjb25maWd1cmF0aW9uIHN0ZXBzIGFyZSBhcHBsaWVkLlxuICAgKiBAcGFyYW0gcHJvamVjdCBUaGUgcHJvamVjdCB0byBjb25maWd1cmUgR2l0SHViIGZvci5cbiAgICovXG4gIGNvbnN0cnVjdG9yKHByb2plY3Q6IFR5cGVTY3JpcHRQcm9qZWN0QmFzZSkge1xuICAgIHN1cGVyKHByb2plY3QpO1xuICAgIHRoaXMuaW5pdGlhbGl6ZSgpO1xuICB9XG5cbiAgLyoqXG4gICAqIEZpbGUgcGF0aCB0byBHaXRIdWIgc3RvcnkgaXNzdWUgdGVtcGxhdGUuXG4gICAqIEByZXR1cm4gRmlsZSBwYXRoIHRvIHN0b3J5IGlzc3VlIGZpbGUuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBnZXQgc3RvcnlJc3N1ZUZpbGVQYXRoKCk6IHN0cmluZyB7XG4gICAgcmV0dXJuICcuZ2l0aHViL0lTU1VFX1RFTVBMQVRFL3N0b3J5LnltbCc7XG4gIH1cblxuICAvKipcbiAgICogQG92ZXJyaWRlXG4gICAqL1xuICBwcm90ZWN0ZWQgZ2V0IHB1bGxSZXF1ZXN0VGVtcGxhdGUoKTogc3RyaW5nW10ge1xuICAgIHJldHVybiBbXG4gICAgICAnIyMgUmV2aWV3ZXJzIENoZWNrbGlzdCcsXG4gICAgICAnJyxcbiAgICAgICdmb3IgY29tcGxldGUgcmV2aWV3IGxpc3QgcmVmZXIgdG8gQUJTIExvb3AgLSBSZXZpZXcgQXNwZWN0cycsXG4gICAgICAnJyxcbiAgICAgICcjIyMgT3JnYW5pemF0aW9uYWwgU2VjdGlvbicsXG4gICAgICAnJyxcbiAgICAgICctIFsgXSBQUiBpcyBhc3NpZ25lZCB0byB0aGUgYWNjb3JkaW5nIHN0b3J5L2ZlYXR1cmUvYnVnJyxcbiAgICAgICctIFsgXSBTdG9yeS9mZWF0dXJlL2J1ZyBpcyBkZXNjcmlwdGl2ZScsXG4gICAgICAnLSBbIF0gU3RvcnkvZmVhdHVyZS9idWcgaXMgYXNzaWduZWQgdG8gYWNjb3JkaW5nIGxhYmVscycsXG4gICAgICAnLSBbIF0gU3RvcnkvZmVhdHVyZS9idWcgaXMgYXNzaWduZWQgdG8gYSBkZXZlbG9wZXInLFxuICAgICAgJycsXG4gICAgICAnIyMjIFN0cnVjdHVyZScsXG4gICAgICAnJyxcbiAgICAgICctIFsgXSBSZWFkYWJpbGl0eTogQ29kZSBpcyBlYXN5IHRvIHVuZGVyc3RhbmQsIHdpdGggbWVhbmluZ2Z1bCBuYW1lcyBmb3IgdmFyaWFibGVzLCBmdW5jdGlvbnMsIGFuZCBjbGFzc2VzJyxcbiAgICAgICctIFsgXSBDb21tZW50czogTWVhbmluZ2Z1bCBhbmQgaGVscGZ1bCBjb21tZW50cy4gQ29kZSBpcyBkb2N1bWVudGVkIHdpdGhvdXQgYmVpbmcgb3Zlci1jb21tZW50ZWQnLFxuICAgICAgJy0gWyBdIERSWSwgS0lTUyBhbmQgWUFHTkk6IENvZGUgaW1wbGVtZW50cyBvbmx5IG5lY2Vzc2FyeSBmZWF0dXJlczsgbm8gb3Zlci1lbmdpbmVlcmluZycsXG4gICAgICAnLSBbIF0gTm8gc2Vuc2l0aXZlIGRhdGEgKGUuZy4sIHBhc3N3b3JkcywgQVBJIGtleXMpIGluIHRoZSBjb2RlJyxcbiAgICAgICctIFsgXSBObyBtYWpvciB1cGRhdGVzIGZvciB1c2VkIHBhY2thZ2VzJyxcbiAgICAgICcnLFxuICAgICAgJyMjIyBDb2RpbmcnLFxuICAgICAgJycsXG4gICAgICAnLSBbIF0gTW9kZWwvQmluZGluZyBwcm9wZXJ0eSBjaGFuZ2VzIG9yIHJlbmFtaW5nIGRvZXMgbm90IGJyZWFrIHRoZSBjb2RlJyxcbiAgICAgICctIFsgXSBNb2RlbC9CaW5kaW5nIHByb3BlcnRpZXMgaGF2ZSBjb25zaXN0ZW50IG5hbWVzIChjYXBpdGFsaXphdGlvbiwgbG93ZXJjYXNlLCAuLiknLFxuICAgICAgJy0gWyBdIFR5cGUgYWxpYXNlcyBhcmUgZGVmaW5lZCBmb3IgYXNzb2NpYXRpb25zIGFuZCBjb21wb3NpdGlvbnMnLFxuICAgICAgJy0gWyBdIE5vIGh1bmdhcmlhbiBub3RhdGlvbiAoZS5nLiBhTGlzdCwgb01vZGVsLCAuLiknLFxuICAgICAgJycsXG4gICAgICAnIyMjIE1vc3QgaW1wb3J0YW50IChhcyBsb25nIGFzIHdlIGRvIG5vdCBoYXZlIFRlc3QgRHJpdmVuIERldmVsb3BtZW50IGluIHBsYWNlKScsXG4gICAgICAnJyxcbiAgICAgICctIFsgXSBDb2RlIGlzIGxvY2FsbHkgdGVzdGVkIGJ5IGRldmVsb3BlcicsXG4gICAgICAnJyxcbiAgICAgICcjIyMgU2Vjb25kIG1vc3QgaW1wb3J0YW50JyxcbiAgICAgICcnLFxuICAgICAgJy0gWyBdIEFQSSBmaXJzdDogYXBwbGljYXRpb24gY2FuIGJlIHVzZWQgaGVhZGxlc3MgKHdpdGggdGhlIEFQSSBvbmx5KScsXG4gICAgICAnPCEtLSBHZW5lcmF0ZWQgYnkgcHJvamVuLiBUbyBtb2RpZnksIGVkaXQgLnByb2plbnJjLnRzIGFuZCBydW4gXCJucHggcHJvamVuXCIuLS0+JyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIElzc3VlIHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIHN0b3J5IGNvbmZpZ3VyYXRpb24uXG4gICAqIEByZXR1cm4gVGVtcGxhdGUgZm9yIHRoZSBzdG9yeSBpc3N1ZSB0ZW1wbGF0ZSBmaWxlLlxuICAgKiBAcHJvdGVjdGVkXG4gICAqL1xuICBwcm90ZWN0ZWQgZ2V0IHN0b3J5SXNzdWVUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICduYW1lOiDwn5KhIFN0b3J5JyxcbiAgICAgICdkZXNjcmlwdGlvbjogQXMgYSBbcm9sZV0sIEkgW3dhbnQgdG9dLCBbc28gdGhhdF0nLFxuICAgICAgJ3RpdGxlOiBcIltTVE9SWV0gPHRpdGxlPlwiJyxcbiAgICAgICdsYWJlbHM6IFtcInR5cGU6IHN0b3J5XCJdJyxcbiAgICAgICdib2R5OicsXG4gICAgICAnICAtIHR5cGU6IHRleHRhcmVhJyxcbiAgICAgICcgICAgYXR0cmlidXRlczonLFxuICAgICAgJyAgICAgIGxhYmVsOiBEZXNjcmlwdGlvbicsXG4gICAgICBcIiAgICAgIGRlc2NyaXB0aW9uOiBQcm92aWRlIGEgYnJpZWYgb3ZlcnZpZXcgb2YgdGhlIHN0b3J5LCBmb2N1c2luZyB3aG8gd2FudCdzIHRvIGRvIHdoYXQgYW5kIHdoeS5cIixcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnIyBHZW5lcmF0ZWQgYnkgcHJvamVuLiBUbyBtb2RpZnksIGVkaXQgLnByb2plbnJjLnRzIGFuZCBydW4gXCJucHggcHJvamVuXCIuJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIEBvdmVycmlkZVxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBmZWF0dXJlSXNzdWVUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICduYW1lOiDwn5KhIEZlYXR1cmUnLFxuICAgICAgJ2Rlc2NyaXB0aW9uOiBTdG9yeSByZWxhdGVkIGZlYXR1cmUnLFxuICAgICAgJ3RpdGxlOiBcIltGRUFUVVJFXSA8dGl0bGU+XCInLFxuICAgICAgJ2xhYmVsczogW1widHlwZTogZmVhdHVyZVwiXScsXG4gICAgICAnYm9keTonLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogRGVzY3JpcHRpb24nLFxuICAgICAgJyAgICAgIGRlc2NyaXB0aW9uOiBBIGRlc2NyaXB0aW9uIG9mIHRoZSBmZWF0dXJlLicsXG4gICAgICAnICAgIHZhbGlkYXRpb25zOicsXG4gICAgICAnICAgICAgcmVxdWlyZWQ6IHRydWUnLFxuICAgICAgJycsXG4gICAgICAnICAtIHR5cGU6IHRleHRhcmVhJyxcbiAgICAgICcgICAgYXR0cmlidXRlczonLFxuICAgICAgJyAgICAgIGxhYmVsOiBUYXNrIExpc3QnLFxuICAgICAgJyAgICAgIGRlc2NyaXB0aW9uOiBEZXNjcmliZSB0aGUgc3RlcHMgdG8gZnVsZmlsbCB0aGUgZmVhdHVyZS4nLFxuICAgICAgJyAgICAgIHZhbHVlOiB8JyxcbiAgICAgICcgICAgICAgIC0gWyBdIE15IEZpcnN0IFRhc2snLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcjIEdlbmVyYXRlZCBieSBwcm9qZW4uIFRvIG1vZGlmeSwgZWRpdCAucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4nLFxuICAgIF07XG4gIH1cblxuICAvKipcbiAgICogQG92ZXJyaWRlXG4gICAqL1xuICBwcm90ZWN0ZWQgZ2V0IHJlbGVhc2VXb3JrZmxvd09wdGlvbnMoKTogV29ya2Zsb3dPcHRpb25zIHtcbiAgICByZXR1cm4ge1xuICAgICAgb246IHtcbiAgICAgICAgcHVsbFJlcXVlc3Q6IHtcbiAgICAgICAgICBicmFuY2hlczogWydkZXYnXSxcbiAgICAgICAgICB0eXBlczogWydjbG9zZWQnXSxcbiAgICAgICAgfSxcbiAgICAgIH0sXG4gICAgICBqb2I6IHtcbiAgICAgICAgcnVuc09uOiBbJ3VidW50dS1sYXRlc3QnXSxcbiAgICAgICAgcGVybWlzc2lvbnM6IHtcbiAgICAgICAgICBjb250ZW50czogSm9iUGVybWlzc2lvbi5XUklURSxcbiAgICAgICAgICBwdWxsUmVxdWVzdHM6IEpvYlBlcm1pc3Npb24uV1JJVEUsXG4gICAgICAgIH0sXG4gICAgICAgIHN0ZXBzOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogJ0J1bXAgdmVyc2lvbiBhbmQgY3JlYXRlIHJlbGVhc2UnLFxuICAgICAgICAgICAgdXNlczogJ2R4ZnJvbnRpZXIvZ2gtYWN0aW9uLXJlbGVhc2VAbWFpbicsXG4gICAgICAgICAgICB3aXRoOiB7XG4gICAgICAgICAgICAgIEdJVEhVQl9UT0tFTjogJyR7eyBzZWNyZXRzLkdJVEhVQl9UT0tFTiB9fScsXG4gICAgICAgICAgICAgIEJSQU5DSDogJ2RldicsXG4gICAgICAgICAgICB9LFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIH07XG4gIH1cblxuICAvKipcbiAgICogV29ya2Zsb3cgZGVwbG95bWVudCB0ZW1wbGF0ZSBvcHRpb25zIGZvciB0aGUgR2l0SHViIGNvbmZpZ3VyYXRpb24uXG4gICAqIEByZXR1cm4gT3B0aW9ucyBmb3IgZGVwbG95bWVudCB3b3JrZmxvd1xuICAgKiBAcHJvdGVjdGVkXG4gICAqL1xuICBwcm90ZWN0ZWQgZ2V0IGRlcGxveW1lbnRXb3JrZmxvd09wdGlvbnMoKTogV29ya2Zsb3dPcHRpb25zIHtcbiAgICByZXR1cm4ge1xuICAgICAgb246IHtcbiAgICAgICAgcHVsbFJlcXVlc3Q6IHtcbiAgICAgICAgICBicmFuY2hlczogWydkZXYnXSxcbiAgICAgICAgICB0eXBlczogWydjbG9zZWQnXSxcbiAgICAgICAgfSxcbiAgICAgIH0sXG4gICAgICBqb2I6IHtcbiAgICAgICAgcnVuc09uOiBbJ3VidW50dS1sYXRlc3QnXSxcbiAgICAgICAgcGVybWlzc2lvbnM6IHtcbiAgICAgICAgICBjb250ZW50czogSm9iUGVybWlzc2lvbi5XUklURSxcbiAgICAgICAgICBwdWxsUmVxdWVzdHM6IEpvYlBlcm1pc3Npb24uV1JJVEUsXG4gICAgICAgIH0sXG4gICAgICAgIHN0ZXBzOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogJ0RlcGxveSB0byBDbG91ZCBGb3VuZHJ5JyxcbiAgICAgICAgICAgIHVzZXM6ICdkeGZyb250aWVyL2doLWFjdGlvbi1kZXBsb3ktY2ZAbWFpbicsXG4gICAgICAgICAgICB3aXRoOiB7XG4gICAgICAgICAgICAgIENGX0lBU19PUklHSU46ICcke3sgc2VjcmV0cy5JQVNfT1JJR0lOIH19JyxcbiAgICAgICAgICAgICAgQ0ZfQVBJX0RFVjogJyR7eyBzZWNyZXRzLkNGX0FQSV9ERVYgfX0nLFxuICAgICAgICAgICAgICBDRl9PUkdfREVWOiAnJHt7IHNlY3JldHMuQ0ZfT1JHX0RFViB9fScsXG4gICAgICAgICAgICAgIENGX1NQQUNFX0RFVjogJyR7eyBzZWNyZXRzLkNGX1NQQUNFX0RFViB9fScsXG4gICAgICAgICAgICAgIENGX1VTRVJOQU1FX0RFVjogJyR7eyBzZWNyZXRzLkNGX1VTRVJOQU1FX0RFViB9fScsXG4gICAgICAgICAgICAgIENGX1BBU1NXT1JEX0RFVjogJyR7eyBzZWNyZXRzLkNGX1BBU1NXT1JEX0RFViB9fScsXG4gICAgICAgICAgICAgIENGX0FQSV9QUk9EOiAnJHt7IHNlY3JldHMuQ0ZfQVBJX1BST0QgfX0nLFxuICAgICAgICAgICAgICBDRl9PUkdfUFJPRDogJyR7eyBzZWNyZXRzLkNGX09SR19QUk9EIH19JyxcbiAgICAgICAgICAgICAgQ0ZfU1BBQ0VfUFJPRDogJyR7eyBzZWNyZXRzLkNGX1NQQUNFX1BST0QgfX0nLFxuICAgICAgICAgICAgICBDRl9VU0VSTkFNRV9QUk9EOiAnJHt7IHNlY3JldHMuQ0ZfVVNFUk5BTUVfUFJPRCB9fScsXG4gICAgICAgICAgICAgIENGX1BBU1NXT1JEX1BST0Q6ICcke3sgc2VjcmV0cy5DRl9QQVNTV09SRF9QUk9EIH19JyxcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgfTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSB0ZW1wbGF0ZSBmaWxlIGZvciBhIEdpdEh1YiBzdG9yeSBpc3N1ZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGNyZWF0ZVN0b3J5SXNzdWUoKTogdm9pZCB7XG4gICAgbmV3IFRleHRGaWxlKHRoaXMucHJvamVjdCwgdGhpcy5zdG9yeUlzc3VlRmlsZVBhdGgsIHtcbiAgICAgIGxpbmVzOiB0aGlzLnN0b3J5SXNzdWVUZW1wbGF0ZSxcbiAgICB9KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBAb3ZlcnJpZGVcbiAgICovXG4gIHByb3RlY3RlZCBjcmVhdGVTdGFsZVdvcmtmbG93KCk6IHZvaWQge31cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgdGVtcGxhdGUgZmlsZSBmb3IgYSBHaXRIdWIgZGVwbG95bWVudCB3b3JrZmxvdy5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGNyZWF0ZURlcGxveW1lbnRXb3JrZmxvdygpOiB2b2lkIHtcbiAgICBjb25zdCB3b3JrZmxvdzogR2l0aHViV29ya2Zsb3cgfCB1bmRlZmluZWQgPSB0aGlzLnByb2plY3QuZ2l0aHViPy5hZGRXb3JrZmxvdygnRGVwbG95bWVudCcpO1xuICAgIHdvcmtmbG93Py5vbih0aGlzLmRlcGxveW1lbnRXb3JrZmxvd09wdGlvbnMub24pO1xuICAgIHdvcmtmbG93Py5hZGRKb2IoJ2RlcGxveScsIHRoaXMuZGVwbG95bWVudFdvcmtmbG93T3B0aW9ucy5qb2IpO1xuICB9XG5cbiAgLyoqXG4gICAqIEBvdmVycmlkZVxuICAgKi9cbiAgcHJvdGVjdGVkIGFkZFRlbXBsYXRlcygpOiB2b2lkIHtcbiAgICBzdXBlci5hZGRUZW1wbGF0ZXMoKTtcbiAgICB0aGlzLmNyZWF0ZVN0b3J5SXNzdWUoKTtcbiAgICB0aGlzLmNyZWF0ZURlcGxveW1lbnRXb3JrZmxvdygpO1xuICB9XG59XG4iXX0=