import { TextFile } from 'projen';
import { TypeScriptProject } from 'projen/lib/typescript';
import { IProjectComponent } from '../types/component';
import { Scripts } from '../types/script';

/**
 * Configures the Husky templates, settings and npm scripts for the project.
 */
export class HuskyComponent implements IProjectComponent {
  private project: TypeScriptProject;

  /**
   * Initializes the Husky component.
   * @param project The project to configure Husky for.
   */
  constructor(project: TypeScriptProject) {
    this.project = project;
  }

  /**
   * Getter retrieving the file path for the Husky commit-msg hook.
   */
  private get commitMsgFilePath(): string {
    return '.husky/commit-msg';
  }

  /**
   * Getter retrieving the file path for the Husky pre-commit hook.
   */
  private get preCommitFilePath(): string {
    return '.husky/pre-commit';
  }

  /**
   * Getter retrieving the template file for commit-msg hook.
   */
  private get commitMsgTemplate(): string[] {
    return [
      '# Generated by projen.To modify, edit.projenrc.ts and run "npx projen".',
      '',
      'npx --no-install commitlint --edit "$1"',
    ];
  }

  /**
   * Getter retrieving the template file for pre-commit hook.
   */
  private get preCommitTemplate(): string[] {
    return ['# Generated by projen.To modify, edit.projenrc.ts and run "npx projen".', '', 'npx lint-staged'];
  }

  /**
   * Getter retrieving the npm scripts used for the Husky component.
   */
  private get scripts(): Scripts {
    return {
      prepare: 'husky || true',
    };
  }

  /**
   * Getter retrieving the relevant npm packages to be installed as devDependencies for the Husky component.
   */
  private get devDependencies(): string[] {
    return ['husky'];
  }

  /**
   * Creates the template file for the Husky commit-msg hook.
   */
  private createCommitMsgHook(): void {
    new TextFile(this.project, this.commitMsgFilePath, {
      lines: this.commitMsgTemplate,
    });
  }

  /**
   * Creates the template file for the Husky pre-commit hook.
   */
  private createPreCommitHook(): void {
    new TextFile(this.project, this.preCommitFilePath, {
      lines: this.preCommitTemplate,
    });
  }

  /**
   * Add template files to the Husky component.
   */
  public add(): void {
    this.createCommitMsgHook();
    this.createPreCommitHook();
  }

  /**
   * Add npm scripts specific to Husky setup within the project configuration.
   */
  public addScripts(): void {
    for (const [name, command] of Object.entries(this.scripts)) {
      this.project.addTask(name, { exec: command });
    }
  }

  /**
   * Add npm devDependencies specific to Husky setup within the project configuration.
   */
  public addDevDependencies(): void {
    this.project.addDevDeps(...this.devDependencies);
  }

  /**
   * Configures the `.gitattributes` file to treat Husky component related files as generated code, optimizing diffs.
   */
  public updateGitAttributes(): void {
    this.project.gitattributes.addAttributes(`/${this.commitMsgFilePath}`, 'linguist-generated');
    this.project.gitattributes.addAttributes(`/${this.preCommitFilePath}`, 'linguist-generated');
  }

  /**
   * Executes setup for the Husky component.
   */
  public setup(): void {
    this.add();
    this.addScripts();
    this.addDevDependencies();
    this.updateGitAttributes();
  }
}
