"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommitLintComponent = void 0;
const projen_1 = require("projen");
/**
 * Configures the CommitLint templates, settings and npm scripts for the project.
 */
class CommitLintComponent {
    /**
     * Initializes the CommitLint component.
     * @param project The project to configure CommitLint for.
     */
    constructor(project) {
        this.project = project;
    }
    /**
     * Getter retrieving the file path for the CommitLint configuration.
     */
    get filePath() {
        return '.commitlintrc.ts';
    }
    /**
     * Getter retrieving the template file for the CommitLint configuration.
     */
    get template() {
        return [
            '// Generated by projen.To modify, edit.projenrc.ts and run "npx projen".',
            '',
            // eslint-disable-next-line prettier/prettier
            'import type { UserConfig } from \'@commitlint/types\';',
            // eslint-disable-next-line prettier/prettier
            'import { RuleConfigSeverity } from \'@commitlint/types\';',
            '',
            'const Configuration: UserConfig = {',
            // eslint-disable-next-line prettier/prettier
            '  extends: [\'@commitlint/config-conventional\'],',
            '  rules: {',
            // eslint-disable-next-line prettier/prettier
            '    \'type-enum\': [',
            '      RuleConfigSeverity.Error,',
            // eslint-disable-next-line prettier/prettier
            '      \'always\',',
            // eslint-disable-next-line prettier/prettier
            '      [\'build\', \'chore\', \'ci\', \'docs\', \'feat\', \'fix\', \'perf\', \'refactor\', \'revert\', \'style\', \'test\', \'delete\'],',
            '    ],',
            // eslint-disable-next-line prettier/prettier
            '    \'scope-empty\': [RuleConfigSeverity.Error, \'never\'],',
            // eslint-disable-next-line prettier/prettier
            '    \'subject-empty\': [RuleConfigSeverity.Error, \'never\'],',
            '  },',
            // eslint-disable-next-line prettier/prettier
            '  helpUrl: \'https://github.com/conventional-changelog/commitlint/#what-is-commitlint\',',
            '};',
            '',
            'export default Configuration;',
        ];
    }
    /**
     * Getter retrieving the npm scripts for the CommitLint component.
     */
    get scripts() {
        return {
            commit: 'commit',
        };
    }
    /**
     * Getter retrieving the relevant npm packages to be installed as devDependencies for the CommitLint component.
     */
    get devDependencies() {
        return [
            '@commitlint/cli',
            '@commitlint/config-conventional',
            '@commitlint/prompt-cli',
            '@commitlint/types',
            'lint-staged',
        ];
    }
    /**
     * Getter retrieving the settings to be added to package.json for the CommitLint component.
     */
    get npmSettings() {
        return {
            '**/*.{yml,yaml}': ['npm run format:message', 'npm run format:fix'],
        };
    }
    /**
     * Creates the template file for the CommitLint configuration.
     */
    createConfiguration() {
        new projen_1.TextFile(this.project, this.filePath, {
            lines: this.template,
        });
    }
    /**
     * Creates npm package settings specific to CommitLint setup within the project configuration.
     */
    createSettings() {
        this.project.addFields({
            'lint-staged': this.npmSettings,
        });
    }
    /**
     * Adds template files and settings to the CommitLint component.
     */
    add() {
        this.createConfiguration();
        this.createSettings();
    }
    /**
     * Adds npm scripts specific to CommitLint setup within the project configuration.
     */
    addScripts() {
        for (const [name, command] of Object.entries(this.scripts)) {
            this.project.addTask(name, { exec: command });
        }
    }
    /**
     * Adds npm devDependencies specific to CommitLint setup within the project configuration.
     */
    addDevDependencies() {
        this.project.addDevDeps(...this.devDependencies);
    }
    /**
     * Configures the `.gitattributes` file to treat CommitLint component related files as generated code, optimizing diffs.
     */
    updateGitAttributes() {
        this.project.gitattributes.addAttributes(`/${this.filePath}`, 'linguist-generated');
    }
    /**
     * Executes setup for the CommitLint component.
     */
    setup() {
        this.add();
        this.addScripts();
        this.addDevDependencies();
        this.updateGitAttributes();
    }
}
exports.CommitLintComponent = CommitLintComponent;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ29tbWl0TGludENvbXBvbmVudC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIi4uLy4uL3NyYy9jb21wb25lbnRzL0NvbW1pdExpbnRDb21wb25lbnQudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7O0FBQUEsbUNBQWtDO0FBSWxDOztHQUVHO0FBQ0gsTUFBYSxtQkFBbUI7SUFHOUI7OztPQUdHO0lBQ0gsWUFBWSxPQUEwQjtRQUNwQyxJQUFJLENBQUMsT0FBTyxHQUFHLE9BQU8sQ0FBQztJQUN6QixDQUFDO0lBRUQ7O09BRUc7SUFDSCxJQUFZLFFBQVE7UUFDbEIsT0FBTyxrQkFBa0IsQ0FBQztJQUM1QixDQUFDO0lBRUQ7O09BRUc7SUFDSCxJQUFZLFFBQVE7UUFDbEIsT0FBTztZQUNMLDBFQUEwRTtZQUMxRSxFQUFFO1lBQ0YsNkNBQTZDO1lBQzdDLHdEQUF3RDtZQUN4RCw2Q0FBNkM7WUFDN0MsMkRBQTJEO1lBQzNELEVBQUU7WUFDRixxQ0FBcUM7WUFDckMsNkNBQTZDO1lBQzdDLG1EQUFtRDtZQUNuRCxZQUFZO1lBQ1osNkNBQTZDO1lBQzdDLHNCQUFzQjtZQUN0QixpQ0FBaUM7WUFDakMsNkNBQTZDO1lBQzdDLG1CQUFtQjtZQUNuQiw2Q0FBNkM7WUFDN0MseUlBQXlJO1lBQ3pJLFFBQVE7WUFDUiw2Q0FBNkM7WUFDN0MsNkRBQTZEO1lBQzdELDZDQUE2QztZQUM3QywrREFBK0Q7WUFDL0QsTUFBTTtZQUNOLDZDQUE2QztZQUM3QywwRkFBMEY7WUFDMUYsSUFBSTtZQUNKLEVBQUU7WUFDRiwrQkFBK0I7U0FDaEMsQ0FBQztJQUNKLENBQUM7SUFFRDs7T0FFRztJQUNILElBQVksT0FBTztRQUNqQixPQUFPO1lBQ0wsTUFBTSxFQUFFLFFBQVE7U0FDakIsQ0FBQztJQUNKLENBQUM7SUFFRDs7T0FFRztJQUNILElBQVksZUFBZTtRQUN6QixPQUFPO1lBQ0wsaUJBQWlCO1lBQ2pCLGlDQUFpQztZQUNqQyx3QkFBd0I7WUFDeEIsbUJBQW1CO1lBQ25CLGFBQWE7U0FDZCxDQUFDO0lBQ0osQ0FBQztJQUVEOztPQUVHO0lBQ0gsSUFBWSxXQUFXO1FBQ3JCLE9BQU87WUFDTCxpQkFBaUIsRUFBRSxDQUFDLHdCQUF3QixFQUFFLG9CQUFvQixDQUFDO1NBQ3BFLENBQUM7SUFDSixDQUFDO0lBRUQ7O09BRUc7SUFDSyxtQkFBbUI7UUFDekIsSUFBSSxpQkFBUSxDQUFDLElBQUksQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLFFBQVEsRUFBRTtZQUN4QyxLQUFLLEVBQUUsSUFBSSxDQUFDLFFBQVE7U0FDckIsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOztPQUVHO0lBQ0ssY0FBYztRQUNwQixJQUFJLENBQUMsT0FBTyxDQUFDLFNBQVMsQ0FBQztZQUNyQixhQUFhLEVBQUUsSUFBSSxDQUFDLFdBQVc7U0FDaEMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOztPQUVHO0lBQ0ksR0FBRztRQUNSLElBQUksQ0FBQyxtQkFBbUIsRUFBRSxDQUFDO1FBQzNCLElBQUksQ0FBQyxjQUFjLEVBQUUsQ0FBQztJQUN4QixDQUFDO0lBRUQ7O09BRUc7SUFDSSxVQUFVO1FBQ2YsS0FBSyxNQUFNLENBQUMsSUFBSSxFQUFFLE9BQU8sQ0FBQyxJQUFJLE1BQU0sQ0FBQyxPQUFPLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBQyxFQUFFLENBQUM7WUFDM0QsSUFBSSxDQUFDLE9BQU8sQ0FBQyxPQUFPLENBQUMsSUFBSSxFQUFFLEVBQUUsSUFBSSxFQUFFLE9BQU8sRUFBRSxDQUFDLENBQUM7UUFDaEQsQ0FBQztJQUNILENBQUM7SUFFRDs7T0FFRztJQUNJLGtCQUFrQjtRQUN2QixJQUFJLENBQUMsT0FBTyxDQUFDLFVBQVUsQ0FBQyxHQUFHLElBQUksQ0FBQyxlQUFlLENBQUMsQ0FBQztJQUNuRCxDQUFDO0lBRUQ7O09BRUc7SUFDSSxtQkFBbUI7UUFDeEIsSUFBSSxDQUFDLE9BQU8sQ0FBQyxhQUFhLENBQUMsYUFBYSxDQUFDLElBQUksSUFBSSxDQUFDLFFBQVEsRUFBRSxFQUFFLG9CQUFvQixDQUFDLENBQUM7SUFDdEYsQ0FBQztJQUVEOztPQUVHO0lBQ0ksS0FBSztRQUNWLElBQUksQ0FBQyxHQUFHLEVBQUUsQ0FBQztRQUNYLElBQUksQ0FBQyxVQUFVLEVBQUUsQ0FBQztRQUNsQixJQUFJLENBQUMsa0JBQWtCLEVBQUUsQ0FBQztRQUMxQixJQUFJLENBQUMsbUJBQW1CLEVBQUUsQ0FBQztJQUM3QixDQUFDO0NBQ0Y7QUFoSkQsa0RBZ0pDIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHsgVGV4dEZpbGUgfSBmcm9tICdwcm9qZW4nO1xuaW1wb3J0IHsgVHlwZVNjcmlwdFByb2plY3QgfSBmcm9tICdwcm9qZW4vbGliL3R5cGVzY3JpcHQnO1xuaW1wb3J0IHsgSVByb2plY3RDb21wb25lbnQsIExpbnRTdGFnZWRDb25maWcsIFNjcmlwdHMgfSBmcm9tICcuLi90eXBlcyc7XG5cbi8qKlxuICogQ29uZmlndXJlcyB0aGUgQ29tbWl0TGludCB0ZW1wbGF0ZXMsIHNldHRpbmdzIGFuZCBucG0gc2NyaXB0cyBmb3IgdGhlIHByb2plY3QuXG4gKi9cbmV4cG9ydCBjbGFzcyBDb21taXRMaW50Q29tcG9uZW50IGltcGxlbWVudHMgSVByb2plY3RDb21wb25lbnQge1xuICBwcml2YXRlIHByb2plY3Q6IFR5cGVTY3JpcHRQcm9qZWN0O1xuXG4gIC8qKlxuICAgKiBJbml0aWFsaXplcyB0aGUgQ29tbWl0TGludCBjb21wb25lbnQuXG4gICAqIEBwYXJhbSBwcm9qZWN0IFRoZSBwcm9qZWN0IHRvIGNvbmZpZ3VyZSBDb21taXRMaW50IGZvci5cbiAgICovXG4gIGNvbnN0cnVjdG9yKHByb2plY3Q6IFR5cGVTY3JpcHRQcm9qZWN0KSB7XG4gICAgdGhpcy5wcm9qZWN0ID0gcHJvamVjdDtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXR0ZXIgcmV0cmlldmluZyB0aGUgZmlsZSBwYXRoIGZvciB0aGUgQ29tbWl0TGludCBjb25maWd1cmF0aW9uLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgZmlsZVBhdGgoKTogc3RyaW5nIHtcbiAgICByZXR1cm4gJy5jb21taXRsaW50cmMudHMnO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHRoZSB0ZW1wbGF0ZSBmaWxlIGZvciB0aGUgQ29tbWl0TGludCBjb25maWd1cmF0aW9uLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgdGVtcGxhdGUoKTogc3RyaW5nW10ge1xuICAgIHJldHVybiBbXG4gICAgICAnLy8gR2VuZXJhdGVkIGJ5IHByb2plbi5UbyBtb2RpZnksIGVkaXQucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4nLFxuICAgICAgJycsXG4gICAgICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgcHJldHRpZXIvcHJldHRpZXJcbiAgICAgICdpbXBvcnQgdHlwZSB7IFVzZXJDb25maWcgfSBmcm9tIFxcJ0Bjb21taXRsaW50L3R5cGVzXFwnOycsXG4gICAgICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgcHJldHRpZXIvcHJldHRpZXJcbiAgICAgICdpbXBvcnQgeyBSdWxlQ29uZmlnU2V2ZXJpdHkgfSBmcm9tIFxcJ0Bjb21taXRsaW50L3R5cGVzXFwnOycsXG4gICAgICAnJyxcbiAgICAgICdjb25zdCBDb25maWd1cmF0aW9uOiBVc2VyQ29uZmlnID0geycsXG4gICAgICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgcHJldHRpZXIvcHJldHRpZXJcbiAgICAgICcgIGV4dGVuZHM6IFtcXCdAY29tbWl0bGludC9jb25maWctY29udmVudGlvbmFsXFwnXSwnLFxuICAgICAgJyAgcnVsZXM6IHsnLFxuICAgICAgLy8gZXNsaW50LWRpc2FibGUtbmV4dC1saW5lIHByZXR0aWVyL3ByZXR0aWVyXG4gICAgICAnICAgIFxcJ3R5cGUtZW51bVxcJzogWycsXG4gICAgICAnICAgICAgUnVsZUNvbmZpZ1NldmVyaXR5LkVycm9yLCcsXG4gICAgICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgcHJldHRpZXIvcHJldHRpZXJcbiAgICAgICcgICAgICBcXCdhbHdheXNcXCcsJyxcbiAgICAgIC8vIGVzbGludC1kaXNhYmxlLW5leHQtbGluZSBwcmV0dGllci9wcmV0dGllclxuICAgICAgJyAgICAgIFtcXCdidWlsZFxcJywgXFwnY2hvcmVcXCcsIFxcJ2NpXFwnLCBcXCdkb2NzXFwnLCBcXCdmZWF0XFwnLCBcXCdmaXhcXCcsIFxcJ3BlcmZcXCcsIFxcJ3JlZmFjdG9yXFwnLCBcXCdyZXZlcnRcXCcsIFxcJ3N0eWxlXFwnLCBcXCd0ZXN0XFwnLCBcXCdkZWxldGVcXCddLCcsXG4gICAgICAnICAgIF0sJyxcbiAgICAgIC8vIGVzbGludC1kaXNhYmxlLW5leHQtbGluZSBwcmV0dGllci9wcmV0dGllclxuICAgICAgJyAgICBcXCdzY29wZS1lbXB0eVxcJzogW1J1bGVDb25maWdTZXZlcml0eS5FcnJvciwgXFwnbmV2ZXJcXCddLCcsXG4gICAgICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgcHJldHRpZXIvcHJldHRpZXJcbiAgICAgICcgICAgXFwnc3ViamVjdC1lbXB0eVxcJzogW1J1bGVDb25maWdTZXZlcml0eS5FcnJvciwgXFwnbmV2ZXJcXCddLCcsXG4gICAgICAnICB9LCcsXG4gICAgICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgcHJldHRpZXIvcHJldHRpZXJcbiAgICAgICcgIGhlbHBVcmw6IFxcJ2h0dHBzOi8vZ2l0aHViLmNvbS9jb252ZW50aW9uYWwtY2hhbmdlbG9nL2NvbW1pdGxpbnQvI3doYXQtaXMtY29tbWl0bGludFxcJywnLFxuICAgICAgJ307JyxcbiAgICAgICcnLFxuICAgICAgJ2V4cG9ydCBkZWZhdWx0IENvbmZpZ3VyYXRpb247JyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHRoZSBucG0gc2NyaXB0cyBmb3IgdGhlIENvbW1pdExpbnQgY29tcG9uZW50LlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgc2NyaXB0cygpOiBTY3JpcHRzIHtcbiAgICByZXR1cm4ge1xuICAgICAgY29tbWl0OiAnY29tbWl0JyxcbiAgICB9O1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHRoZSByZWxldmFudCBucG0gcGFja2FnZXMgdG8gYmUgaW5zdGFsbGVkIGFzIGRldkRlcGVuZGVuY2llcyBmb3IgdGhlIENvbW1pdExpbnQgY29tcG9uZW50LlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgZGV2RGVwZW5kZW5jaWVzKCk6IHN0cmluZ1tdIHtcbiAgICByZXR1cm4gW1xuICAgICAgJ0Bjb21taXRsaW50L2NsaScsXG4gICAgICAnQGNvbW1pdGxpbnQvY29uZmlnLWNvbnZlbnRpb25hbCcsXG4gICAgICAnQGNvbW1pdGxpbnQvcHJvbXB0LWNsaScsXG4gICAgICAnQGNvbW1pdGxpbnQvdHlwZXMnLFxuICAgICAgJ2xpbnQtc3RhZ2VkJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHRoZSBzZXR0aW5ncyB0byBiZSBhZGRlZCB0byBwYWNrYWdlLmpzb24gZm9yIHRoZSBDb21taXRMaW50IGNvbXBvbmVudC5cbiAgICovXG4gIHByaXZhdGUgZ2V0IG5wbVNldHRpbmdzKCk6IExpbnRTdGFnZWRDb25maWcge1xuICAgIHJldHVybiB7XG4gICAgICAnKiovKi57eW1sLHlhbWx9JzogWyducG0gcnVuIGZvcm1hdDptZXNzYWdlJywgJ25wbSBydW4gZm9ybWF0OmZpeCddLFxuICAgIH07XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgdGVtcGxhdGUgZmlsZSBmb3IgdGhlIENvbW1pdExpbnQgY29uZmlndXJhdGlvbi5cbiAgICovXG4gIHByaXZhdGUgY3JlYXRlQ29uZmlndXJhdGlvbigpOiB2b2lkIHtcbiAgICBuZXcgVGV4dEZpbGUodGhpcy5wcm9qZWN0LCB0aGlzLmZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy50ZW1wbGF0ZSxcbiAgICB9KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIG5wbSBwYWNrYWdlIHNldHRpbmdzIHNwZWNpZmljIHRvIENvbW1pdExpbnQgc2V0dXAgd2l0aGluIHRoZSBwcm9qZWN0IGNvbmZpZ3VyYXRpb24uXG4gICAqL1xuICBwcml2YXRlIGNyZWF0ZVNldHRpbmdzKCk6IHZvaWQge1xuICAgIHRoaXMucHJvamVjdC5hZGRGaWVsZHMoe1xuICAgICAgJ2xpbnQtc3RhZ2VkJzogdGhpcy5ucG1TZXR0aW5ncyxcbiAgICB9KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBBZGRzIHRlbXBsYXRlIGZpbGVzIGFuZCBzZXR0aW5ncyB0byB0aGUgQ29tbWl0TGludCBjb21wb25lbnQuXG4gICAqL1xuICBwdWJsaWMgYWRkKCk6IHZvaWQge1xuICAgIHRoaXMuY3JlYXRlQ29uZmlndXJhdGlvbigpO1xuICAgIHRoaXMuY3JlYXRlU2V0dGluZ3MoKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBBZGRzIG5wbSBzY3JpcHRzIHNwZWNpZmljIHRvIENvbW1pdExpbnQgc2V0dXAgd2l0aGluIHRoZSBwcm9qZWN0IGNvbmZpZ3VyYXRpb24uXG4gICAqL1xuICBwdWJsaWMgYWRkU2NyaXB0cygpOiB2b2lkIHtcbiAgICBmb3IgKGNvbnN0IFtuYW1lLCBjb21tYW5kXSBvZiBPYmplY3QuZW50cmllcyh0aGlzLnNjcmlwdHMpKSB7XG4gICAgICB0aGlzLnByb2plY3QuYWRkVGFzayhuYW1lLCB7IGV4ZWM6IGNvbW1hbmQgfSk7XG4gICAgfVxuICB9XG5cbiAgLyoqXG4gICAqIEFkZHMgbnBtIGRldkRlcGVuZGVuY2llcyBzcGVjaWZpYyB0byBDb21taXRMaW50IHNldHVwIHdpdGhpbiB0aGUgcHJvamVjdCBjb25maWd1cmF0aW9uLlxuICAgKi9cbiAgcHVibGljIGFkZERldkRlcGVuZGVuY2llcygpOiB2b2lkIHtcbiAgICB0aGlzLnByb2plY3QuYWRkRGV2RGVwcyguLi50aGlzLmRldkRlcGVuZGVuY2llcyk7XG4gIH1cblxuICAvKipcbiAgICogQ29uZmlndXJlcyB0aGUgYC5naXRhdHRyaWJ1dGVzYCBmaWxlIHRvIHRyZWF0IENvbW1pdExpbnQgY29tcG9uZW50IHJlbGF0ZWQgZmlsZXMgYXMgZ2VuZXJhdGVkIGNvZGUsIG9wdGltaXppbmcgZGlmZnMuXG4gICAqL1xuICBwdWJsaWMgdXBkYXRlR2l0QXR0cmlidXRlcygpOiB2b2lkIHtcbiAgICB0aGlzLnByb2plY3QuZ2l0YXR0cmlidXRlcy5hZGRBdHRyaWJ1dGVzKGAvJHt0aGlzLmZpbGVQYXRofWAsICdsaW5ndWlzdC1nZW5lcmF0ZWQnKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBFeGVjdXRlcyBzZXR1cCBmb3IgdGhlIENvbW1pdExpbnQgY29tcG9uZW50LlxuICAgKi9cbiAgcHVibGljIHNldHVwKCk6IHZvaWQge1xuICAgIHRoaXMuYWRkKCk7XG4gICAgdGhpcy5hZGRTY3JpcHRzKCk7XG4gICAgdGhpcy5hZGREZXZEZXBlbmRlbmNpZXMoKTtcbiAgICB0aGlzLnVwZGF0ZUdpdEF0dHJpYnV0ZXMoKTtcbiAgfVxufVxuIl19