"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GitHubComponent = void 0;
const projen_1 = require("projen");
const github_1 = require("projen/lib/github");
const workflows_model_1 = require("projen/lib/github/workflows-model");
/**
 * Configures the GitHub templates, settings and npm scripts for the project.
 */
class GitHubComponent {
    /**
     * Initializes the GitHub component.
     * @param project The project to configure GitHub for.
     */
    constructor(project) {
        this.project = project;
    }
    /**
     * Getter retrieving the file path for GitHub bug issue template.
     */
    get bugIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/bug.yml';
    }
    /**
     * Getter retrieving the file path for GitHub feature issue template.
     */
    get featureIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/feature.yml';
    }
    /**
     * Getter retrieving the file path for GitHub question issue template.
     */
    get questionIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/question.yml';
    }
    /**
     * Getter retrieving the file path for the Cliff toml configuration.
     * This file is used by release workflow to create the Changelog.
     */
    get cliffTomlFilePath() {
        return 'cliff.toml';
    }
    /**
     * Getter retrieving pull request template for the GitHub configuration.
     */
    get pullRequestTemplate() {
        return [
            '## Reviewers Checklist',
            '',
            'for complete review list refer to ABS Loop - Review Aspects',
            '',
            '### Organizational Section',
            '',
            '- [ ] PR is assigned to the according feature/bug',
            '- [ ] Feature/bug is descriptive',
            '- [ ] Feature/bug is assigned to according labels',
            '- [ ] Feature/bug is assigned to a developer',
            '',
            '### Structure',
            '',
            '- [ ] Readability: Code is easy to understand, with meaningful names for variables, functions, and classes',
            '- [ ] Comments: Meaningful and helpful comments. Code is documented without being over-commented',
            '- [ ] DRY, KISS and YAGNI: Code implements only necessary features; no over-engineering',
            '- [ ] No sensitive data (e.g., passwords, API keys) in the code',
            '- [ ] No major updates for used packages',
            '',
            '### Testing',
            '',
            '- [ ] Code is locally tested by developer (if applicable)',
            '- [ ] Automated tests pass successfully',
            '<!-- Generated by projen. To modify, edit .projenrc.ts and run "npx projen".-->',
        ];
    }
    /**
     * Getter retrieving bug issue template for the GitHub configuration.
     */
    get bugIssueTemplate() {
        return [
            'name: 🐞 Bug',
            'description: File a bug/issue',
            'title: "[BUG] <title>"',
            'labels: ["type: bug"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Current behavior',
            "      description: A description of what you're experiencing.",
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Expected behavior',
            '      description: A description of what you expected to happen.',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Getter retrieving feature issue template for the GitHub configuration.
     */
    get featureIssueTemplate() {
        return [
            'name: 💡 Feature',
            'description: Story related feature',
            'title: "[FEATURE] <title>"',
            'labels: ["type: feature"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Description',
            '      description: A description of the feature.',
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Task List',
            '      description: Describe the steps to fulfill the feature.',
            '      value: |',
            '        - [ ] My First Task',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Getter retrieving question issue template for the GitHub configuration.
     */
    get questionIssueTemplate() {
        return [
            'name: ❓ Question',
            'description: Ask a question',
            'title: "[QUESTION] <title>"',
            'labels: ["type: question"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Question',
            '      description: What would you like to know? If you encounter unusual behavior or identified a missing feature, consider opening a bug report instead.',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Getter retrieving cliff toml configuration for the GitHub configuration.
     * This file is used by release workflow to create the Changelog.
     */
    get cliffTomlConfiguration() {
        return [
            '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
            '',
            '[changelog]',
            '# changelog header',
            'header = """',
            '# Changelog\n',
            'All notable changes to this project will be documented in this file.\n',
            '"""',
            '# template for the changelog body',
            '# https://keats.github.io/tera/docs/#introduction',
            'body = """',
            '{% if version %}\\',
            '    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}',
            '{% else %}\\',
            '    ## [unreleased]',
            '{% endif %}\\',
            '{% for group, commits in commits | group_by(attribute="group") %}',
            '    ### {{ group | striptags | trim | upper_first }}',
            '    {% for commit in commits %}',
            '        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\\',
            '            {% if commit.breaking %}[**breaking**] {% endif %}\\',
            '            {{ commit.message | upper_first }}\\',
            '    {% endfor %}',
            '{% endfor %}\\',
            '"""',
            '# template for the changelog footer',
            'footer = """',
            '<!-- generated by git-cliff -->',
            '"""',
            '# remove the leading and trailing s',
            'trim = true',
            '# postprocessors',
            'postprocessors = [',
            '  # { pattern = "<REPO>", replace = "https://github.com/orhun/git-cliff" }, # replace repository URL',
            ']',
            '',
            '[git]',
            '# parse the commits based on https://www.conventionalcommits.org',
            'conventional_commits = true',
            '# filter out the commits that are not conventional',
            'filter_unconventional = true',
            '# process each line of a commit as an individual commit',
            'split_commits = false',
            '# regex for preprocessing the commit messages',
            'commit_preprocessors = [',
            '  # Replace issue numbers',
            '  #{ pattern = "\\((\\w+\\s)?#([0-9]+)\\)", replace = "([#${2}](<REPO>/issues/${2}))"},',
            '  # Check spelling of the commit with https://github.com/crate-ci/typos',
            '  # If the spelling is incorrect, it will be automatically fixed.',
            '  #{ pattern = ".*", replace_command = "typos --write-changes -" },',
            ']',
            '# regex for parsing and grouping commits',
            'commit_parsers = [',
            '  { message = "^feat", group = "<!-- 0 -->🚀 Features" },',
            '  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },',
            '  { message = "^doc", group = "<!-- 3 -->📚 Documentation" },',
            '  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },',
            '  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },',
            '  { message = "^style", group = "<!-- 5 -->🎨 Styling" },',
            '  { message = "^test", group = "<!-- 6 -->🧪 Testing" },',
            '  { message = "^chore\\(release\\): prepare for", skip = true },',
            '  { message = "^chore\\(deps.*\\)", skip = true },',
            '  { message = "^chore\\(pr\\)", skip = true },',
            '  { message = "^chore\\(pull\\)", skip = true },',
            '  { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },',
            '  { body = ".*security", group = "<!-- 8 -->🛡️ Security" },',
            '  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },',
            ']',
            '# protect breaking changes from being skipped due to matching a skipping commit_parser',
            'protect_breaking_commits = false',
            '# filter out the commits that are not matched by commit parsers',
            'filter_commits = false',
            '# regex for matching git tags',
            '# tag_pattern = "v[0-9].*"',
            '# regex for skipping tags',
            '# skip_tags = ""',
            '# regex for ignoring tags',
            '# ignore_tags = ""',
            '# sort the tags topologically',
            'topo_order = false',
            '# sort the commits inside sections by oldest/newest order',
            'sort_commits = "oldest"',
            '# limit the number of commits included in the changelog.',
            '# limit_commits = 42',
        ];
    }
    /**
     * Getter retrieving release workflow template options for the GitHub configuration.
     */
    get releaseWorkflowOptions() {
        return {
            on: {
                pullRequest: {
                    branches: ['main'],
                    types: ['closed'],
                },
            },
            job: {
                runsOn: ['ubuntu-latest'],
                permissions: {
                    contents: workflows_model_1.JobPermission.WRITE,
                    pullRequests: workflows_model_1.JobPermission.WRITE,
                },
                steps: [
                    {
                        name: 'Create release',
                        uses: 'dxfrontier/gh-action-release@main',
                        with: {
                            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
                            BRANCH: 'main',
                        },
                    },
                ],
            },
        };
    }
    /**
     * Getter retrieving stale workflow template options for the GitHub configuration.
     */
    get staleWorkflowOptions() {
        return {
            on: {
                schedule: [
                    {
                        cron: '36 18 * * *',
                    },
                ],
            },
            job: {
                runsOn: ['ubuntu-latest'],
                permissions: {
                    issues: workflows_model_1.JobPermission.WRITE,
                    pullRequests: workflows_model_1.JobPermission.WRITE,
                },
                steps: [
                    {
                        uses: 'actions/stale@v5',
                        with: {
                            'repo-token': '${{ secrets.GITHUB_TOKEN }}',
                            'days-before-issue-stale': 30,
                            'stale-issue-message': 'This issue has not been updated in a while. If it is still relevant, please comment on it to keep it open. The issue will be closed soon if it remains inactive.',
                            'close-issue-message': 'This issue has been closed automatically due to inactivity.',
                            'stale-pr-message': 'This PR has not been updated in a while. If it is still relevant, please comment on it to keep it open. The PR will be closed soon if it remains inactive.',
                            'close-pr-message': 'This PR has been closed automatically due to inactivity.',
                            'stale-issue-label': 'status: stale',
                            'stale-pr-label': 'status: stale',
                            'exempt-issue-labels': 'type: feature request',
                            'exempt-pr-labels': 'type: feature request',
                            'exempt-all-milestones': true,
                        },
                    },
                ],
            },
        };
    }
    /**
     * Creates the template file for a GitHub pull request.
     */
    createPullRequest() {
        new github_1.PullRequestTemplate(this.project.github, {
            lines: this.pullRequestTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub bug issue.
     */
    createBugIssue() {
        new projen_1.TextFile(this.project, this.bugIssueFilePath, {
            lines: this.bugIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub feature issue.
     */
    createFeatureIssue() {
        new projen_1.TextFile(this.project, this.featureIssueFilePath, {
            lines: this.featureIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub question issue.
     */
    createQuestionIssue() {
        new projen_1.TextFile(this.project, this.questionIssueFilePath, {
            lines: this.questionIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub release workflow.
     */
    createReleaseWorkflow() {
        var _a;
        const workflow = (_a = this.project.github) === null || _a === void 0 ? void 0 : _a.addWorkflow('Release');
        workflow === null || workflow === void 0 ? void 0 : workflow.on(this.releaseWorkflowOptions.on);
        workflow === null || workflow === void 0 ? void 0 : workflow.addJob('release', this.releaseWorkflowOptions.job);
    }
    /**
     * Creates the template file for a GitHub stale workflow.
     */
    createStaleWorkflow() {
        var _a;
        const workflow = (_a = this.project.github) === null || _a === void 0 ? void 0 : _a.addWorkflow('Stale');
        workflow === null || workflow === void 0 ? void 0 : workflow.on(this.staleWorkflowOptions.on);
        workflow === null || workflow === void 0 ? void 0 : workflow.addJob('stale', this.staleWorkflowOptions.job);
    }
    /**
     * Creates the configuration file for the cliff toml CHANGELOG creation in release workflow.
     */
    createCliffTomlConfiguration() {
        new projen_1.TextFile(this.project, this.cliffTomlFilePath, {
            lines: this.cliffTomlConfiguration,
        });
    }
    /**
     * Adds template files to the GitHub component.
     */
    add() {
        this.createPullRequest();
        this.createBugIssue();
        this.createFeatureIssue();
        this.createQuestionIssue();
        this.createReleaseWorkflow();
        this.createStaleWorkflow();
        this.createCliffTomlConfiguration();
    }
    /**
     * Configures the `.gitattributes` file to treat GitHub component related files as generated code, optimizing diffs.
     */
    updateGitAttributes() {
        // Pull request template is added automatically
        this.project.gitattributes.addAttributes(`/${this.bugIssueFilePath}`, 'linguist-generated');
        this.project.gitattributes.addAttributes(`/${this.featureIssueFilePath}`, 'linguist-generated');
        this.project.gitattributes.addAttributes(`/${this.questionIssueFilePath}`, 'linguist-generated');
        this.project.gitattributes.addAttributes(`/${this.cliffTomlFilePath}`, 'linguist-generated');
        // Workflows templates are added automatically
    }
    /**
     * Executes setup for the GitHub component.
     */
    setup() {
        this.add();
        this.updateGitAttributes();
    }
}
exports.GitHubComponent = GitHubComponent;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2l0SHViQ29tcG9uZW50LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vc3JjL2NvbXBvbmVudHMvR2l0SHViQ29tcG9uZW50LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7OztBQUFBLG1DQUFrQztBQUNsQyw4Q0FBd0U7QUFDeEUsdUVBQWlGO0FBSWpGOztHQUVHO0FBQ0gsTUFBYSxlQUFlO0lBRzFCOzs7T0FHRztJQUNILFlBQVksT0FBMEI7UUFDcEMsSUFBSSxDQUFDLE9BQU8sR0FBRyxPQUFPLENBQUM7SUFDekIsQ0FBQztJQUVEOztPQUVHO0lBQ0gsSUFBWSxnQkFBZ0I7UUFDMUIsT0FBTyxnQ0FBZ0MsQ0FBQztJQUMxQyxDQUFDO0lBRUQ7O09BRUc7SUFDSCxJQUFZLG9CQUFvQjtRQUM5QixPQUFPLG9DQUFvQyxDQUFDO0lBQzlDLENBQUM7SUFFRDs7T0FFRztJQUNILElBQVkscUJBQXFCO1FBQy9CLE9BQU8scUNBQXFDLENBQUM7SUFDL0MsQ0FBQztJQUVEOzs7T0FHRztJQUNILElBQVksaUJBQWlCO1FBQzNCLE9BQU8sWUFBWSxDQUFDO0lBQ3RCLENBQUM7SUFFRDs7T0FFRztJQUNILElBQVksbUJBQW1CO1FBQzdCLE9BQU87WUFDTCx3QkFBd0I7WUFDeEIsRUFBRTtZQUNGLDZEQUE2RDtZQUM3RCxFQUFFO1lBQ0YsNEJBQTRCO1lBQzVCLEVBQUU7WUFDRixtREFBbUQ7WUFDbkQsa0NBQWtDO1lBQ2xDLG1EQUFtRDtZQUNuRCw4Q0FBOEM7WUFDOUMsRUFBRTtZQUNGLGVBQWU7WUFDZixFQUFFO1lBQ0YsNEdBQTRHO1lBQzVHLGtHQUFrRztZQUNsRyx5RkFBeUY7WUFDekYsaUVBQWlFO1lBQ2pFLDBDQUEwQztZQUMxQyxFQUFFO1lBQ0YsYUFBYTtZQUNiLEVBQUU7WUFDRiwyREFBMkQ7WUFDM0QseUNBQXlDO1lBQ3pDLGlGQUFpRjtTQUNsRixDQUFDO0lBQ0osQ0FBQztJQUVEOztPQUVHO0lBQ0gsSUFBWSxnQkFBZ0I7UUFDMUIsT0FBTztZQUNMLGNBQWM7WUFDZCwrQkFBK0I7WUFDL0Isd0JBQXdCO1lBQ3hCLHVCQUF1QjtZQUN2QixPQUFPO1lBQ1Asb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQiwrQkFBK0I7WUFDL0IsK0RBQStEO1lBQy9ELGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsRUFBRTtZQUNGLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsZ0NBQWdDO1lBQ2hDLGtFQUFrRTtZQUNsRSxrQkFBa0I7WUFDbEIsc0JBQXNCO1lBQ3RCLDJFQUEyRTtTQUM1RSxDQUFDO0lBQ0osQ0FBQztJQUVEOztPQUVHO0lBQ0gsSUFBWSxvQkFBb0I7UUFDOUIsT0FBTztZQUNMLGtCQUFrQjtZQUNsQixvQ0FBb0M7WUFDcEMsNEJBQTRCO1lBQzVCLDJCQUEyQjtZQUMzQixPQUFPO1lBQ1Asb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQiwwQkFBMEI7WUFDMUIsa0RBQWtEO1lBQ2xELGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsRUFBRTtZQUNGLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsd0JBQXdCO1lBQ3hCLCtEQUErRDtZQUMvRCxnQkFBZ0I7WUFDaEIsNkJBQTZCO1lBQzdCLGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsMkVBQTJFO1NBQzVFLENBQUM7SUFDSixDQUFDO0lBRUQ7O09BRUc7SUFDSCxJQUFZLHFCQUFxQjtRQUMvQixPQUFPO1lBQ0wsa0JBQWtCO1lBQ2xCLDZCQUE2QjtZQUM3Qiw2QkFBNkI7WUFDN0IsNEJBQTRCO1lBQzVCLE9BQU87WUFDUCxvQkFBb0I7WUFDcEIsaUJBQWlCO1lBQ2pCLHVCQUF1QjtZQUN2QiwySkFBMko7WUFDM0osa0JBQWtCO1lBQ2xCLHNCQUFzQjtZQUN0QiwyRUFBMkU7U0FDNUUsQ0FBQztJQUNKLENBQUM7SUFFRDs7O09BR0c7SUFDSCxJQUFZLHNCQUFzQjtRQUNoQyxPQUFPO1lBQ0wsOEVBQThFO1lBQzlFLEVBQUU7WUFDRixhQUFhO1lBQ2Isb0JBQW9CO1lBQ3BCLGNBQWM7WUFDZCxlQUFlO1lBQ2Ysd0VBQXdFO1lBQ3hFLEtBQUs7WUFDTCxtQ0FBbUM7WUFDbkMsbURBQW1EO1lBQ25ELFlBQVk7WUFDWixvQkFBb0I7WUFDcEIsa0dBQWtHO1lBQ2xHLGNBQWM7WUFDZCxxQkFBcUI7WUFDckIsZUFBZTtZQUNmLG1FQUFtRTtZQUNuRSxzREFBc0Q7WUFDdEQsaUNBQWlDO1lBQ2pDLHFFQUFxRTtZQUNyRSxrRUFBa0U7WUFDbEUsa0RBQWtEO1lBQ2xELGtCQUFrQjtZQUNsQixnQkFBZ0I7WUFDaEIsS0FBSztZQUNMLHFDQUFxQztZQUNyQyxjQUFjO1lBQ2QsaUNBQWlDO1lBQ2pDLEtBQUs7WUFDTCxxQ0FBcUM7WUFDckMsYUFBYTtZQUNiLGtCQUFrQjtZQUNsQixvQkFBb0I7WUFDcEIsc0dBQXNHO1lBQ3RHLEdBQUc7WUFDSCxFQUFFO1lBQ0YsT0FBTztZQUNQLGtFQUFrRTtZQUNsRSw2QkFBNkI7WUFDN0Isb0RBQW9EO1lBQ3BELDhCQUE4QjtZQUM5Qix5REFBeUQ7WUFDekQsdUJBQXVCO1lBQ3ZCLCtDQUErQztZQUMvQywwQkFBMEI7WUFDMUIsMkJBQTJCO1lBQzNCLHlGQUF5RjtZQUN6Rix5RUFBeUU7WUFDekUsbUVBQW1FO1lBQ25FLHFFQUFxRTtZQUNyRSxHQUFHO1lBQ0gsMENBQTBDO1lBQzFDLG9CQUFvQjtZQUNwQiwyREFBMkQ7WUFDM0QsMkRBQTJEO1lBQzNELCtEQUErRDtZQUMvRCw2REFBNkQ7WUFDN0QsK0RBQStEO1lBQy9ELDJEQUEyRDtZQUMzRCwwREFBMEQ7WUFDMUQsa0VBQWtFO1lBQ2xFLG9EQUFvRDtZQUNwRCxnREFBZ0Q7WUFDaEQsa0RBQWtEO1lBQ2xELDJFQUEyRTtZQUMzRSw4REFBOEQ7WUFDOUQsMkRBQTJEO1lBQzNELEdBQUc7WUFDSCx3RkFBd0Y7WUFDeEYsa0NBQWtDO1lBQ2xDLGlFQUFpRTtZQUNqRSx3QkFBd0I7WUFDeEIsK0JBQStCO1lBQy9CLDRCQUE0QjtZQUM1QiwyQkFBMkI7WUFDM0Isa0JBQWtCO1lBQ2xCLDJCQUEyQjtZQUMzQixvQkFBb0I7WUFDcEIsK0JBQStCO1lBQy9CLG9CQUFvQjtZQUNwQiwyREFBMkQ7WUFDM0QseUJBQXlCO1lBQ3pCLDBEQUEwRDtZQUMxRCxzQkFBc0I7U0FDdkIsQ0FBQztJQUNKLENBQUM7SUFFRDs7T0FFRztJQUNILElBQVksc0JBQXNCO1FBQ2hDLE9BQU87WUFDTCxFQUFFLEVBQUU7Z0JBQ0YsV0FBVyxFQUFFO29CQUNYLFFBQVEsRUFBRSxDQUFDLE1BQU0sQ0FBQztvQkFDbEIsS0FBSyxFQUFFLENBQUMsUUFBUSxDQUFDO2lCQUNsQjthQUNGO1lBQ0QsR0FBRyxFQUFFO2dCQUNILE1BQU0sRUFBRSxDQUFDLGVBQWUsQ0FBQztnQkFDekIsV0FBVyxFQUFFO29CQUNYLFFBQVEsRUFBRSwrQkFBYSxDQUFDLEtBQUs7b0JBQzdCLFlBQVksRUFBRSwrQkFBYSxDQUFDLEtBQUs7aUJBQ2xDO2dCQUNELEtBQUssRUFBRTtvQkFDTDt3QkFDRSxJQUFJLEVBQUUsZ0JBQWdCO3dCQUN0QixJQUFJLEVBQUUsbUNBQW1DO3dCQUN6QyxJQUFJLEVBQUU7NEJBQ0osWUFBWSxFQUFFLDZCQUE2Qjs0QkFDM0MsTUFBTSxFQUFFLE1BQU07eUJBQ2Y7cUJBQ0Y7aUJBQ0Y7YUFDRjtTQUNGLENBQUM7SUFDSixDQUFDO0lBRUQ7O09BRUc7SUFDSCxJQUFZLG9CQUFvQjtRQUM5QixPQUFPO1lBQ0wsRUFBRSxFQUFFO2dCQUNGLFFBQVEsRUFBRTtvQkFDUjt3QkFDRSxJQUFJLEVBQUUsYUFBYTtxQkFDcEI7aUJBQ0Y7YUFDRjtZQUNELEdBQUcsRUFBRTtnQkFDSCxNQUFNLEVBQUUsQ0FBQyxlQUFlLENBQUM7Z0JBQ3pCLFdBQVcsRUFBRTtvQkFDWCxNQUFNLEVBQUUsK0JBQWEsQ0FBQyxLQUFLO29CQUMzQixZQUFZLEVBQUUsK0JBQWEsQ0FBQyxLQUFLO2lCQUNsQztnQkFDRCxLQUFLLEVBQUU7b0JBQ0w7d0JBQ0UsSUFBSSxFQUFFLGtCQUFrQjt3QkFDeEIsSUFBSSxFQUFFOzRCQUNKLFlBQVksRUFBRSw2QkFBNkI7NEJBQzNDLHlCQUF5QixFQUFFLEVBQUU7NEJBQzdCLHFCQUFxQixFQUNuQixrS0FBa0s7NEJBQ3BLLHFCQUFxQixFQUFFLDZEQUE2RDs0QkFDcEYsa0JBQWtCLEVBQ2hCLDRKQUE0Sjs0QkFDOUosa0JBQWtCLEVBQUUsMERBQTBEOzRCQUM5RSxtQkFBbUIsRUFBRSxlQUFlOzRCQUNwQyxnQkFBZ0IsRUFBRSxlQUFlOzRCQUNqQyxxQkFBcUIsRUFBRSx1QkFBdUI7NEJBQzlDLGtCQUFrQixFQUFFLHVCQUF1Qjs0QkFDM0MsdUJBQXVCLEVBQUUsSUFBSTt5QkFDOUI7cUJBQ0Y7aUJBQ0Y7YUFDRjtTQUNGLENBQUM7SUFDSixDQUFDO0lBRUQ7O09BRUc7SUFDSyxpQkFBaUI7UUFDdkIsSUFBSSw0QkFBbUIsQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUFDLE1BQU8sRUFBRTtZQUM1QyxLQUFLLEVBQUUsSUFBSSxDQUFDLG1CQUFtQjtTQUNoQyxDQUFDLENBQUM7SUFDTCxDQUFDO0lBRUQ7O09BRUc7SUFDSyxjQUFjO1FBQ3BCLElBQUksaUJBQVEsQ0FBQyxJQUFJLENBQUMsT0FBTyxFQUFFLElBQUksQ0FBQyxnQkFBZ0IsRUFBRTtZQUNoRCxLQUFLLEVBQUUsSUFBSSxDQUFDLGdCQUFnQjtTQUM3QixDQUFDLENBQUM7SUFDTCxDQUFDO0lBRUQ7O09BRUc7SUFDSyxrQkFBa0I7UUFDeEIsSUFBSSxpQkFBUSxDQUFDLElBQUksQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLG9CQUFvQixFQUFFO1lBQ3BELEtBQUssRUFBRSxJQUFJLENBQUMsb0JBQW9CO1NBQ2pDLENBQUMsQ0FBQztJQUNMLENBQUM7SUFFRDs7T0FFRztJQUNLLG1CQUFtQjtRQUN6QixJQUFJLGlCQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxJQUFJLENBQUMscUJBQXFCLEVBQUU7WUFDckQsS0FBSyxFQUFFLElBQUksQ0FBQyxxQkFBcUI7U0FDbEMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOztPQUVHO0lBQ0sscUJBQXFCOztRQUMzQixNQUFNLFFBQVEsR0FBK0IsTUFBQSxJQUFJLENBQUMsT0FBTyxDQUFDLE1BQU0sMENBQUUsV0FBVyxDQUFDLFNBQVMsQ0FBQyxDQUFDO1FBQ3pGLFFBQVEsYUFBUixRQUFRLHVCQUFSLFFBQVEsQ0FBRSxFQUFFLENBQUMsSUFBSSxDQUFDLHNCQUFzQixDQUFDLEVBQUUsQ0FBQyxDQUFDO1FBQzdDLFFBQVEsYUFBUixRQUFRLHVCQUFSLFFBQVEsQ0FBRSxNQUFNLENBQUMsU0FBUyxFQUFFLElBQUksQ0FBQyxzQkFBc0IsQ0FBQyxHQUFHLENBQUMsQ0FBQztJQUMvRCxDQUFDO0lBRUQ7O09BRUc7SUFDSyxtQkFBbUI7O1FBQ3pCLE1BQU0sUUFBUSxHQUErQixNQUFBLElBQUksQ0FBQyxPQUFPLENBQUMsTUFBTSwwQ0FBRSxXQUFXLENBQUMsT0FBTyxDQUFDLENBQUM7UUFDdkYsUUFBUSxhQUFSLFFBQVEsdUJBQVIsUUFBUSxDQUFFLEVBQUUsQ0FBQyxJQUFJLENBQUMsb0JBQW9CLENBQUMsRUFBRSxDQUFDLENBQUM7UUFDM0MsUUFBUSxhQUFSLFFBQVEsdUJBQVIsUUFBUSxDQUFFLE1BQU0sQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLG9CQUFvQixDQUFDLEdBQUcsQ0FBQyxDQUFDO0lBQzNELENBQUM7SUFFRDs7T0FFRztJQUNLLDRCQUE0QjtRQUNsQyxJQUFJLGlCQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxJQUFJLENBQUMsaUJBQWlCLEVBQUU7WUFDakQsS0FBSyxFQUFFLElBQUksQ0FBQyxzQkFBc0I7U0FDbkMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOztPQUVHO0lBQ0ksR0FBRztRQUNSLElBQUksQ0FBQyxpQkFBaUIsRUFBRSxDQUFDO1FBQ3pCLElBQUksQ0FBQyxjQUFjLEVBQUUsQ0FBQztRQUN0QixJQUFJLENBQUMsa0JBQWtCLEVBQUUsQ0FBQztRQUMxQixJQUFJLENBQUMsbUJBQW1CLEVBQUUsQ0FBQztRQUUzQixJQUFJLENBQUMscUJBQXFCLEVBQUUsQ0FBQztRQUM3QixJQUFJLENBQUMsbUJBQW1CLEVBQUUsQ0FBQztRQUMzQixJQUFJLENBQUMsNEJBQTRCLEVBQUUsQ0FBQztJQUN0QyxDQUFDO0lBRUQ7O09BRUc7SUFDSSxtQkFBbUI7UUFDeEIsK0NBQStDO1FBQy9DLElBQUksQ0FBQyxPQUFPLENBQUMsYUFBYSxDQUFDLGFBQWEsQ0FBQyxJQUFJLElBQUksQ0FBQyxnQkFBZ0IsRUFBRSxFQUFFLG9CQUFvQixDQUFDLENBQUM7UUFDNUYsSUFBSSxDQUFDLE9BQU8sQ0FBQyxhQUFhLENBQUMsYUFBYSxDQUFDLElBQUksSUFBSSxDQUFDLG9CQUFvQixFQUFFLEVBQUUsb0JBQW9CLENBQUMsQ0FBQztRQUNoRyxJQUFJLENBQUMsT0FBTyxDQUFDLGFBQWEsQ0FBQyxhQUFhLENBQUMsSUFBSSxJQUFJLENBQUMscUJBQXFCLEVBQUUsRUFBRSxvQkFBb0IsQ0FBQyxDQUFDO1FBQ2pHLElBQUksQ0FBQyxPQUFPLENBQUMsYUFBYSxDQUFDLGFBQWEsQ0FBQyxJQUFJLElBQUksQ0FBQyxpQkFBaUIsRUFBRSxFQUFFLG9CQUFvQixDQUFDLENBQUM7UUFDN0YsOENBQThDO0lBQ2hELENBQUM7SUFFRDs7T0FFRztJQUNJLEtBQUs7UUFDVixJQUFJLENBQUMsR0FBRyxFQUFFLENBQUM7UUFDWCxJQUFJLENBQUMsbUJBQW1CLEVBQUUsQ0FBQztJQUM3QixDQUFDO0NBQ0Y7QUExWkQsMENBMFpDIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHsgVGV4dEZpbGUgfSBmcm9tICdwcm9qZW4nO1xuaW1wb3J0IHsgR2l0aHViV29ya2Zsb3csIFB1bGxSZXF1ZXN0VGVtcGxhdGUgfSBmcm9tICdwcm9qZW4vbGliL2dpdGh1Yic7XG5pbXBvcnQgeyBKb2IsIEpvYlBlcm1pc3Npb24sIFRyaWdnZXJzIH0gZnJvbSAncHJvamVuL2xpYi9naXRodWIvd29ya2Zsb3dzLW1vZGVsJztcbmltcG9ydCB7IFR5cGVTY3JpcHRQcm9qZWN0IH0gZnJvbSAncHJvamVuL2xpYi90eXBlc2NyaXB0JztcbmltcG9ydCB7IElQcm9qZWN0Q29tcG9uZW50IH0gZnJvbSAnLi4vdHlwZXMnO1xuXG4vKipcbiAqIENvbmZpZ3VyZXMgdGhlIEdpdEh1YiB0ZW1wbGF0ZXMsIHNldHRpbmdzIGFuZCBucG0gc2NyaXB0cyBmb3IgdGhlIHByb2plY3QuXG4gKi9cbmV4cG9ydCBjbGFzcyBHaXRIdWJDb21wb25lbnQgaW1wbGVtZW50cyBJUHJvamVjdENvbXBvbmVudCB7XG4gIHByaXZhdGUgcHJvamVjdDogVHlwZVNjcmlwdFByb2plY3Q7XG5cbiAgLyoqXG4gICAqIEluaXRpYWxpemVzIHRoZSBHaXRIdWIgY29tcG9uZW50LlxuICAgKiBAcGFyYW0gcHJvamVjdCBUaGUgcHJvamVjdCB0byBjb25maWd1cmUgR2l0SHViIGZvci5cbiAgICovXG4gIGNvbnN0cnVjdG9yKHByb2plY3Q6IFR5cGVTY3JpcHRQcm9qZWN0KSB7XG4gICAgdGhpcy5wcm9qZWN0ID0gcHJvamVjdDtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXR0ZXIgcmV0cmlldmluZyB0aGUgZmlsZSBwYXRoIGZvciBHaXRIdWIgYnVnIGlzc3VlIHRlbXBsYXRlLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgYnVnSXNzdWVGaWxlUGF0aCgpOiBzdHJpbmcge1xuICAgIHJldHVybiAnLmdpdGh1Yi9JU1NVRV9URU1QTEFURS9idWcueW1sJztcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXR0ZXIgcmV0cmlldmluZyB0aGUgZmlsZSBwYXRoIGZvciBHaXRIdWIgZmVhdHVyZSBpc3N1ZSB0ZW1wbGF0ZS5cbiAgICovXG4gIHByaXZhdGUgZ2V0IGZlYXR1cmVJc3N1ZUZpbGVQYXRoKCk6IHN0cmluZyB7XG4gICAgcmV0dXJuICcuZ2l0aHViL0lTU1VFX1RFTVBMQVRFL2ZlYXR1cmUueW1sJztcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXR0ZXIgcmV0cmlldmluZyB0aGUgZmlsZSBwYXRoIGZvciBHaXRIdWIgcXVlc3Rpb24gaXNzdWUgdGVtcGxhdGUuXG4gICAqL1xuICBwcml2YXRlIGdldCBxdWVzdGlvbklzc3VlRmlsZVBhdGgoKTogc3RyaW5nIHtcbiAgICByZXR1cm4gJy5naXRodWIvSVNTVUVfVEVNUExBVEUvcXVlc3Rpb24ueW1sJztcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXR0ZXIgcmV0cmlldmluZyB0aGUgZmlsZSBwYXRoIGZvciB0aGUgQ2xpZmYgdG9tbCBjb25maWd1cmF0aW9uLlxuICAgKiBUaGlzIGZpbGUgaXMgdXNlZCBieSByZWxlYXNlIHdvcmtmbG93IHRvIGNyZWF0ZSB0aGUgQ2hhbmdlbG9nLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgY2xpZmZUb21sRmlsZVBhdGgoKTogc3RyaW5nIHtcbiAgICByZXR1cm4gJ2NsaWZmLnRvbWwnO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHB1bGwgcmVxdWVzdCB0ZW1wbGF0ZSBmb3IgdGhlIEdpdEh1YiBjb25maWd1cmF0aW9uLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgcHVsbFJlcXVlc3RUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICcjIyBSZXZpZXdlcnMgQ2hlY2tsaXN0JyxcbiAgICAgICcnLFxuICAgICAgJ2ZvciBjb21wbGV0ZSByZXZpZXcgbGlzdCByZWZlciB0byBBQlMgTG9vcCAtIFJldmlldyBBc3BlY3RzJyxcbiAgICAgICcnLFxuICAgICAgJyMjIyBPcmdhbml6YXRpb25hbCBTZWN0aW9uJyxcbiAgICAgICcnLFxuICAgICAgJy0gWyBdIFBSIGlzIGFzc2lnbmVkIHRvIHRoZSBhY2NvcmRpbmcgZmVhdHVyZS9idWcnLFxuICAgICAgJy0gWyBdIEZlYXR1cmUvYnVnIGlzIGRlc2NyaXB0aXZlJyxcbiAgICAgICctIFsgXSBGZWF0dXJlL2J1ZyBpcyBhc3NpZ25lZCB0byBhY2NvcmRpbmcgbGFiZWxzJyxcbiAgICAgICctIFsgXSBGZWF0dXJlL2J1ZyBpcyBhc3NpZ25lZCB0byBhIGRldmVsb3BlcicsXG4gICAgICAnJyxcbiAgICAgICcjIyMgU3RydWN0dXJlJyxcbiAgICAgICcnLFxuICAgICAgJy0gWyBdIFJlYWRhYmlsaXR5OiBDb2RlIGlzIGVhc3kgdG8gdW5kZXJzdGFuZCwgd2l0aCBtZWFuaW5nZnVsIG5hbWVzIGZvciB2YXJpYWJsZXMsIGZ1bmN0aW9ucywgYW5kIGNsYXNzZXMnLFxuICAgICAgJy0gWyBdIENvbW1lbnRzOiBNZWFuaW5nZnVsIGFuZCBoZWxwZnVsIGNvbW1lbnRzLiBDb2RlIGlzIGRvY3VtZW50ZWQgd2l0aG91dCBiZWluZyBvdmVyLWNvbW1lbnRlZCcsXG4gICAgICAnLSBbIF0gRFJZLCBLSVNTIGFuZCBZQUdOSTogQ29kZSBpbXBsZW1lbnRzIG9ubHkgbmVjZXNzYXJ5IGZlYXR1cmVzOyBubyBvdmVyLWVuZ2luZWVyaW5nJyxcbiAgICAgICctIFsgXSBObyBzZW5zaXRpdmUgZGF0YSAoZS5nLiwgcGFzc3dvcmRzLCBBUEkga2V5cykgaW4gdGhlIGNvZGUnLFxuICAgICAgJy0gWyBdIE5vIG1ham9yIHVwZGF0ZXMgZm9yIHVzZWQgcGFja2FnZXMnLFxuICAgICAgJycsXG4gICAgICAnIyMjIFRlc3RpbmcnLFxuICAgICAgJycsXG4gICAgICAnLSBbIF0gQ29kZSBpcyBsb2NhbGx5IHRlc3RlZCBieSBkZXZlbG9wZXIgKGlmIGFwcGxpY2FibGUpJyxcbiAgICAgICctIFsgXSBBdXRvbWF0ZWQgdGVzdHMgcGFzcyBzdWNjZXNzZnVsbHknLFxuICAgICAgJzwhLS0gR2VuZXJhdGVkIGJ5IHByb2plbi4gVG8gbW9kaWZ5LCBlZGl0IC5wcm9qZW5yYy50cyBhbmQgcnVuIFwibnB4IHByb2plblwiLi0tPicsXG4gICAgXTtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXR0ZXIgcmV0cmlldmluZyBidWcgaXNzdWUgdGVtcGxhdGUgZm9yIHRoZSBHaXRIdWIgY29uZmlndXJhdGlvbi5cbiAgICovXG4gIHByaXZhdGUgZ2V0IGJ1Z0lzc3VlVGVtcGxhdGUoKTogc3RyaW5nW10ge1xuICAgIHJldHVybiBbXG4gICAgICAnbmFtZTog8J+QniBCdWcnLFxuICAgICAgJ2Rlc2NyaXB0aW9uOiBGaWxlIGEgYnVnL2lzc3VlJyxcbiAgICAgICd0aXRsZTogXCJbQlVHXSA8dGl0bGU+XCInLFxuICAgICAgJ2xhYmVsczogW1widHlwZTogYnVnXCJdJyxcbiAgICAgICdib2R5OicsXG4gICAgICAnICAtIHR5cGU6IHRleHRhcmVhJyxcbiAgICAgICcgICAgYXR0cmlidXRlczonLFxuICAgICAgJyAgICAgIGxhYmVsOiBDdXJyZW50IGJlaGF2aW9yJyxcbiAgICAgIFwiICAgICAgZGVzY3JpcHRpb246IEEgZGVzY3JpcHRpb24gb2Ygd2hhdCB5b3UncmUgZXhwZXJpZW5jaW5nLlwiLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcnLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogRXhwZWN0ZWQgYmVoYXZpb3InLFxuICAgICAgJyAgICAgIGRlc2NyaXB0aW9uOiBBIGRlc2NyaXB0aW9uIG9mIHdoYXQgeW91IGV4cGVjdGVkIHRvIGhhcHBlbi4nLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcjIEdlbmVyYXRlZCBieSBwcm9qZW4uIFRvIG1vZGlmeSwgZWRpdCAucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4nLFxuICAgIF07XG4gIH1cblxuICAvKipcbiAgICogR2V0dGVyIHJldHJpZXZpbmcgZmVhdHVyZSBpc3N1ZSB0ZW1wbGF0ZSBmb3IgdGhlIEdpdEh1YiBjb25maWd1cmF0aW9uLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgZmVhdHVyZUlzc3VlVGVtcGxhdGUoKTogc3RyaW5nW10ge1xuICAgIHJldHVybiBbXG4gICAgICAnbmFtZTog8J+SoSBGZWF0dXJlJyxcbiAgICAgICdkZXNjcmlwdGlvbjogU3RvcnkgcmVsYXRlZCBmZWF0dXJlJyxcbiAgICAgICd0aXRsZTogXCJbRkVBVFVSRV0gPHRpdGxlPlwiJyxcbiAgICAgICdsYWJlbHM6IFtcInR5cGU6IGZlYXR1cmVcIl0nLFxuICAgICAgJ2JvZHk6JyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IERlc2NyaXB0aW9uJyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogQSBkZXNjcmlwdGlvbiBvZiB0aGUgZmVhdHVyZS4nLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcnLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogVGFzayBMaXN0JyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogRGVzY3JpYmUgdGhlIHN0ZXBzIHRvIGZ1bGZpbGwgdGhlIGZlYXR1cmUuJyxcbiAgICAgICcgICAgICB2YWx1ZTogfCcsXG4gICAgICAnICAgICAgICAtIFsgXSBNeSBGaXJzdCBUYXNrJyxcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnIyBHZW5lcmF0ZWQgYnkgcHJvamVuLiBUbyBtb2RpZnksIGVkaXQgLnByb2plbnJjLnRzIGFuZCBydW4gXCJucHggcHJvamVuXCIuJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHF1ZXN0aW9uIGlzc3VlIHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIGNvbmZpZ3VyYXRpb24uXG4gICAqL1xuICBwcml2YXRlIGdldCBxdWVzdGlvbklzc3VlVGVtcGxhdGUoKTogc3RyaW5nW10ge1xuICAgIHJldHVybiBbXG4gICAgICAnbmFtZTog4p2TIFF1ZXN0aW9uJyxcbiAgICAgICdkZXNjcmlwdGlvbjogQXNrIGEgcXVlc3Rpb24nLFxuICAgICAgJ3RpdGxlOiBcIltRVUVTVElPTl0gPHRpdGxlPlwiJyxcbiAgICAgICdsYWJlbHM6IFtcInR5cGU6IHF1ZXN0aW9uXCJdJyxcbiAgICAgICdib2R5OicsXG4gICAgICAnICAtIHR5cGU6IHRleHRhcmVhJyxcbiAgICAgICcgICAgYXR0cmlidXRlczonLFxuICAgICAgJyAgICAgIGxhYmVsOiBRdWVzdGlvbicsXG4gICAgICAnICAgICAgZGVzY3JpcHRpb246IFdoYXQgd291bGQgeW91IGxpa2UgdG8ga25vdz8gSWYgeW91IGVuY291bnRlciB1bnVzdWFsIGJlaGF2aW9yIG9yIGlkZW50aWZpZWQgYSBtaXNzaW5nIGZlYXR1cmUsIGNvbnNpZGVyIG9wZW5pbmcgYSBidWcgcmVwb3J0IGluc3RlYWQuJyxcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnIyBHZW5lcmF0ZWQgYnkgcHJvamVuLiBUbyBtb2RpZnksIGVkaXQgLnByb2plbnJjLnRzIGFuZCBydW4gXCJucHggcHJvamVuXCIuJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIGNsaWZmIHRvbWwgY29uZmlndXJhdGlvbiBmb3IgdGhlIEdpdEh1YiBjb25maWd1cmF0aW9uLlxuICAgKiBUaGlzIGZpbGUgaXMgdXNlZCBieSByZWxlYXNlIHdvcmtmbG93IHRvIGNyZWF0ZSB0aGUgQ2hhbmdlbG9nLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgY2xpZmZUb21sQ29uZmlndXJhdGlvbigpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICcjIH5+IEdlbmVyYXRlZCBieSBwcm9qZW4uIFRvIG1vZGlmeSwgZWRpdCAucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4nLFxuICAgICAgJycsXG4gICAgICAnW2NoYW5nZWxvZ10nLFxuICAgICAgJyMgY2hhbmdlbG9nIGhlYWRlcicsXG4gICAgICAnaGVhZGVyID0gXCJcIlwiJyxcbiAgICAgICcjIENoYW5nZWxvZ1xcbicsXG4gICAgICAnQWxsIG5vdGFibGUgY2hhbmdlcyB0byB0aGlzIHByb2plY3Qgd2lsbCBiZSBkb2N1bWVudGVkIGluIHRoaXMgZmlsZS5cXG4nLFxuICAgICAgJ1wiXCJcIicsXG4gICAgICAnIyB0ZW1wbGF0ZSBmb3IgdGhlIGNoYW5nZWxvZyBib2R5JyxcbiAgICAgICcjIGh0dHBzOi8va2VhdHMuZ2l0aHViLmlvL3RlcmEvZG9jcy8jaW50cm9kdWN0aW9uJyxcbiAgICAgICdib2R5ID0gXCJcIlwiJyxcbiAgICAgICd7JSBpZiB2ZXJzaW9uICV9XFxcXCcsXG4gICAgICAnICAgICMjIFt7eyB2ZXJzaW9uIHwgdHJpbV9zdGFydF9tYXRjaGVzKHBhdD1cInZcIikgfX1dIC0ge3sgdGltZXN0YW1wIHwgZGF0ZShmb3JtYXQ9XCIlWS0lbS0lZFwiKSB9fScsXG4gICAgICAneyUgZWxzZSAlfVxcXFwnLFxuICAgICAgJyAgICAjIyBbdW5yZWxlYXNlZF0nLFxuICAgICAgJ3slIGVuZGlmICV9XFxcXCcsXG4gICAgICAneyUgZm9yIGdyb3VwLCBjb21taXRzIGluIGNvbW1pdHMgfCBncm91cF9ieShhdHRyaWJ1dGU9XCJncm91cFwiKSAlfScsXG4gICAgICAnICAgICMjIyB7eyBncm91cCB8IHN0cmlwdGFncyB8IHRyaW0gfCB1cHBlcl9maXJzdCB9fScsXG4gICAgICAnICAgIHslIGZvciBjb21taXQgaW4gY29tbWl0cyAlfScsXG4gICAgICAnICAgICAgICAtIHslIGlmIGNvbW1pdC5zY29wZSAlfSooe3sgY29tbWl0LnNjb3BlIH19KSogeyUgZW5kaWYgJX1cXFxcJyxcbiAgICAgICcgICAgICAgICAgICB7JSBpZiBjb21taXQuYnJlYWtpbmcgJX1bKipicmVha2luZyoqXSB7JSBlbmRpZiAlfVxcXFwnLFxuICAgICAgJyAgICAgICAgICAgIHt7IGNvbW1pdC5tZXNzYWdlIHwgdXBwZXJfZmlyc3QgfX1cXFxcJyxcbiAgICAgICcgICAgeyUgZW5kZm9yICV9JyxcbiAgICAgICd7JSBlbmRmb3IgJX1cXFxcJyxcbiAgICAgICdcIlwiXCInLFxuICAgICAgJyMgdGVtcGxhdGUgZm9yIHRoZSBjaGFuZ2Vsb2cgZm9vdGVyJyxcbiAgICAgICdmb290ZXIgPSBcIlwiXCInLFxuICAgICAgJzwhLS0gZ2VuZXJhdGVkIGJ5IGdpdC1jbGlmZiAtLT4nLFxuICAgICAgJ1wiXCJcIicsXG4gICAgICAnIyByZW1vdmUgdGhlIGxlYWRpbmcgYW5kIHRyYWlsaW5nIHMnLFxuICAgICAgJ3RyaW0gPSB0cnVlJyxcbiAgICAgICcjIHBvc3Rwcm9jZXNzb3JzJyxcbiAgICAgICdwb3N0cHJvY2Vzc29ycyA9IFsnLFxuICAgICAgJyAgIyB7IHBhdHRlcm4gPSBcIjxSRVBPPlwiLCByZXBsYWNlID0gXCJodHRwczovL2dpdGh1Yi5jb20vb3JodW4vZ2l0LWNsaWZmXCIgfSwgIyByZXBsYWNlIHJlcG9zaXRvcnkgVVJMJyxcbiAgICAgICddJyxcbiAgICAgICcnLFxuICAgICAgJ1tnaXRdJyxcbiAgICAgICcjIHBhcnNlIHRoZSBjb21taXRzIGJhc2VkIG9uIGh0dHBzOi8vd3d3LmNvbnZlbnRpb25hbGNvbW1pdHMub3JnJyxcbiAgICAgICdjb252ZW50aW9uYWxfY29tbWl0cyA9IHRydWUnLFxuICAgICAgJyMgZmlsdGVyIG91dCB0aGUgY29tbWl0cyB0aGF0IGFyZSBub3QgY29udmVudGlvbmFsJyxcbiAgICAgICdmaWx0ZXJfdW5jb252ZW50aW9uYWwgPSB0cnVlJyxcbiAgICAgICcjIHByb2Nlc3MgZWFjaCBsaW5lIG9mIGEgY29tbWl0IGFzIGFuIGluZGl2aWR1YWwgY29tbWl0JyxcbiAgICAgICdzcGxpdF9jb21taXRzID0gZmFsc2UnLFxuICAgICAgJyMgcmVnZXggZm9yIHByZXByb2Nlc3NpbmcgdGhlIGNvbW1pdCBtZXNzYWdlcycsXG4gICAgICAnY29tbWl0X3ByZXByb2Nlc3NvcnMgPSBbJyxcbiAgICAgICcgICMgUmVwbGFjZSBpc3N1ZSBudW1iZXJzJyxcbiAgICAgICcgICN7IHBhdHRlcm4gPSBcIlxcXFwoKFxcXFx3K1xcXFxzKT8jKFswLTldKylcXFxcKVwiLCByZXBsYWNlID0gXCIoWyMkezJ9XSg8UkVQTz4vaXNzdWVzLyR7Mn0pKVwifSwnLFxuICAgICAgJyAgIyBDaGVjayBzcGVsbGluZyBvZiB0aGUgY29tbWl0IHdpdGggaHR0cHM6Ly9naXRodWIuY29tL2NyYXRlLWNpL3R5cG9zJyxcbiAgICAgICcgICMgSWYgdGhlIHNwZWxsaW5nIGlzIGluY29ycmVjdCwgaXQgd2lsbCBiZSBhdXRvbWF0aWNhbGx5IGZpeGVkLicsXG4gICAgICAnICAjeyBwYXR0ZXJuID0gXCIuKlwiLCByZXBsYWNlX2NvbW1hbmQgPSBcInR5cG9zIC0td3JpdGUtY2hhbmdlcyAtXCIgfSwnLFxuICAgICAgJ10nLFxuICAgICAgJyMgcmVnZXggZm9yIHBhcnNpbmcgYW5kIGdyb3VwaW5nIGNvbW1pdHMnLFxuICAgICAgJ2NvbW1pdF9wYXJzZXJzID0gWycsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5mZWF0XCIsIGdyb3VwID0gXCI8IS0tIDAgLS0+8J+agCBGZWF0dXJlc1wiIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmZpeFwiLCBncm91cCA9IFwiPCEtLSAxIC0tPvCfkJsgQnVnIEZpeGVzXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeZG9jXCIsIGdyb3VwID0gXCI8IS0tIDMgLS0+8J+TmiBEb2N1bWVudGF0aW9uXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJecGVyZlwiLCBncm91cCA9IFwiPCEtLSA0IC0tPuKaoSBQZXJmb3JtYW5jZVwiIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXnJlZmFjdG9yXCIsIGdyb3VwID0gXCI8IS0tIDIgLS0+8J+anCBSZWZhY3RvclwiIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXnN0eWxlXCIsIGdyb3VwID0gXCI8IS0tIDUgLS0+8J+OqCBTdHlsaW5nXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJedGVzdFwiLCBncm91cCA9IFwiPCEtLSA2IC0tPvCfp6ogVGVzdGluZ1wiIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmNob3JlXFxcXChyZWxlYXNlXFxcXCk6IHByZXBhcmUgZm9yXCIsIHNraXAgPSB0cnVlIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmNob3JlXFxcXChkZXBzLipcXFxcKVwiLCBza2lwID0gdHJ1ZSB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5jaG9yZVxcXFwocHJcXFxcKVwiLCBza2lwID0gdHJ1ZSB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5jaG9yZVxcXFwocHVsbFxcXFwpXCIsIHNraXAgPSB0cnVlIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmNob3JlfF5jaVwiLCBncm91cCA9IFwiPCEtLSA3IC0tPuKame+4jyBNaXNjZWxsYW5lb3VzIFRhc2tzXCIgfSwnLFxuICAgICAgJyAgeyBib2R5ID0gXCIuKnNlY3VyaXR5XCIsIGdyb3VwID0gXCI8IS0tIDggLS0+8J+boe+4jyBTZWN1cml0eVwiIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXnJldmVydFwiLCBncm91cCA9IFwiPCEtLSA5IC0tPuKXgO+4jyBSZXZlcnRcIiB9LCcsXG4gICAgICAnXScsXG4gICAgICAnIyBwcm90ZWN0IGJyZWFraW5nIGNoYW5nZXMgZnJvbSBiZWluZyBza2lwcGVkIGR1ZSB0byBtYXRjaGluZyBhIHNraXBwaW5nIGNvbW1pdF9wYXJzZXInLFxuICAgICAgJ3Byb3RlY3RfYnJlYWtpbmdfY29tbWl0cyA9IGZhbHNlJyxcbiAgICAgICcjIGZpbHRlciBvdXQgdGhlIGNvbW1pdHMgdGhhdCBhcmUgbm90IG1hdGNoZWQgYnkgY29tbWl0IHBhcnNlcnMnLFxuICAgICAgJ2ZpbHRlcl9jb21taXRzID0gZmFsc2UnLFxuICAgICAgJyMgcmVnZXggZm9yIG1hdGNoaW5nIGdpdCB0YWdzJyxcbiAgICAgICcjIHRhZ19wYXR0ZXJuID0gXCJ2WzAtOV0uKlwiJyxcbiAgICAgICcjIHJlZ2V4IGZvciBza2lwcGluZyB0YWdzJyxcbiAgICAgICcjIHNraXBfdGFncyA9IFwiXCInLFxuICAgICAgJyMgcmVnZXggZm9yIGlnbm9yaW5nIHRhZ3MnLFxuICAgICAgJyMgaWdub3JlX3RhZ3MgPSBcIlwiJyxcbiAgICAgICcjIHNvcnQgdGhlIHRhZ3MgdG9wb2xvZ2ljYWxseScsXG4gICAgICAndG9wb19vcmRlciA9IGZhbHNlJyxcbiAgICAgICcjIHNvcnQgdGhlIGNvbW1pdHMgaW5zaWRlIHNlY3Rpb25zIGJ5IG9sZGVzdC9uZXdlc3Qgb3JkZXInLFxuICAgICAgJ3NvcnRfY29tbWl0cyA9IFwib2xkZXN0XCInLFxuICAgICAgJyMgbGltaXQgdGhlIG51bWJlciBvZiBjb21taXRzIGluY2x1ZGVkIGluIHRoZSBjaGFuZ2Vsb2cuJyxcbiAgICAgICcjIGxpbWl0X2NvbW1pdHMgPSA0MicsXG4gICAgXTtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXR0ZXIgcmV0cmlldmluZyByZWxlYXNlIHdvcmtmbG93IHRlbXBsYXRlIG9wdGlvbnMgZm9yIHRoZSBHaXRIdWIgY29uZmlndXJhdGlvbi5cbiAgICovXG4gIHByaXZhdGUgZ2V0IHJlbGVhc2VXb3JrZmxvd09wdGlvbnMoKTogeyBvbjogVHJpZ2dlcnM7IGpvYjogSm9iIH0ge1xuICAgIHJldHVybiB7XG4gICAgICBvbjoge1xuICAgICAgICBwdWxsUmVxdWVzdDoge1xuICAgICAgICAgIGJyYW5jaGVzOiBbJ21haW4nXSxcbiAgICAgICAgICB0eXBlczogWydjbG9zZWQnXSxcbiAgICAgICAgfSxcbiAgICAgIH0sXG4gICAgICBqb2I6IHtcbiAgICAgICAgcnVuc09uOiBbJ3VidW50dS1sYXRlc3QnXSxcbiAgICAgICAgcGVybWlzc2lvbnM6IHtcbiAgICAgICAgICBjb250ZW50czogSm9iUGVybWlzc2lvbi5XUklURSxcbiAgICAgICAgICBwdWxsUmVxdWVzdHM6IEpvYlBlcm1pc3Npb24uV1JJVEUsXG4gICAgICAgIH0sXG4gICAgICAgIHN0ZXBzOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogJ0NyZWF0ZSByZWxlYXNlJyxcbiAgICAgICAgICAgIHVzZXM6ICdkeGZyb250aWVyL2doLWFjdGlvbi1yZWxlYXNlQG1haW4nLFxuICAgICAgICAgICAgd2l0aDoge1xuICAgICAgICAgICAgICBHSVRIVUJfVE9LRU46ICcke3sgc2VjcmV0cy5HSVRIVUJfVE9LRU4gfX0nLFxuICAgICAgICAgICAgICBCUkFOQ0g6ICdtYWluJyxcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgfTtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXR0ZXIgcmV0cmlldmluZyBzdGFsZSB3b3JrZmxvdyB0ZW1wbGF0ZSBvcHRpb25zIGZvciB0aGUgR2l0SHViIGNvbmZpZ3VyYXRpb24uXG4gICAqL1xuICBwcml2YXRlIGdldCBzdGFsZVdvcmtmbG93T3B0aW9ucygpOiB7IG9uOiBUcmlnZ2Vyczsgam9iOiBKb2IgfSB7XG4gICAgcmV0dXJuIHtcbiAgICAgIG9uOiB7XG4gICAgICAgIHNjaGVkdWxlOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgY3JvbjogJzM2IDE4ICogKiAqJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIGpvYjoge1xuICAgICAgICBydW5zT246IFsndWJ1bnR1LWxhdGVzdCddLFxuICAgICAgICBwZXJtaXNzaW9uczoge1xuICAgICAgICAgIGlzc3VlczogSm9iUGVybWlzc2lvbi5XUklURSxcbiAgICAgICAgICBwdWxsUmVxdWVzdHM6IEpvYlBlcm1pc3Npb24uV1JJVEUsXG4gICAgICAgIH0sXG4gICAgICAgIHN0ZXBzOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdXNlczogJ2FjdGlvbnMvc3RhbGVAdjUnLFxuICAgICAgICAgICAgd2l0aDoge1xuICAgICAgICAgICAgICAncmVwby10b2tlbic6ICcke3sgc2VjcmV0cy5HSVRIVUJfVE9LRU4gfX0nLFxuICAgICAgICAgICAgICAnZGF5cy1iZWZvcmUtaXNzdWUtc3RhbGUnOiAzMCxcbiAgICAgICAgICAgICAgJ3N0YWxlLWlzc3VlLW1lc3NhZ2UnOlxuICAgICAgICAgICAgICAgICdUaGlzIGlzc3VlIGhhcyBub3QgYmVlbiB1cGRhdGVkIGluIGEgd2hpbGUuIElmIGl0IGlzIHN0aWxsIHJlbGV2YW50LCBwbGVhc2UgY29tbWVudCBvbiBpdCB0byBrZWVwIGl0IG9wZW4uIFRoZSBpc3N1ZSB3aWxsIGJlIGNsb3NlZCBzb29uIGlmIGl0IHJlbWFpbnMgaW5hY3RpdmUuJyxcbiAgICAgICAgICAgICAgJ2Nsb3NlLWlzc3VlLW1lc3NhZ2UnOiAnVGhpcyBpc3N1ZSBoYXMgYmVlbiBjbG9zZWQgYXV0b21hdGljYWxseSBkdWUgdG8gaW5hY3Rpdml0eS4nLFxuICAgICAgICAgICAgICAnc3RhbGUtcHItbWVzc2FnZSc6XG4gICAgICAgICAgICAgICAgJ1RoaXMgUFIgaGFzIG5vdCBiZWVuIHVwZGF0ZWQgaW4gYSB3aGlsZS4gSWYgaXQgaXMgc3RpbGwgcmVsZXZhbnQsIHBsZWFzZSBjb21tZW50IG9uIGl0IHRvIGtlZXAgaXQgb3Blbi4gVGhlIFBSIHdpbGwgYmUgY2xvc2VkIHNvb24gaWYgaXQgcmVtYWlucyBpbmFjdGl2ZS4nLFxuICAgICAgICAgICAgICAnY2xvc2UtcHItbWVzc2FnZSc6ICdUaGlzIFBSIGhhcyBiZWVuIGNsb3NlZCBhdXRvbWF0aWNhbGx5IGR1ZSB0byBpbmFjdGl2aXR5LicsXG4gICAgICAgICAgICAgICdzdGFsZS1pc3N1ZS1sYWJlbCc6ICdzdGF0dXM6IHN0YWxlJyxcbiAgICAgICAgICAgICAgJ3N0YWxlLXByLWxhYmVsJzogJ3N0YXR1czogc3RhbGUnLFxuICAgICAgICAgICAgICAnZXhlbXB0LWlzc3VlLWxhYmVscyc6ICd0eXBlOiBmZWF0dXJlIHJlcXVlc3QnLFxuICAgICAgICAgICAgICAnZXhlbXB0LXByLWxhYmVscyc6ICd0eXBlOiBmZWF0dXJlIHJlcXVlc3QnLFxuICAgICAgICAgICAgICAnZXhlbXB0LWFsbC1taWxlc3RvbmVzJzogdHJ1ZSxcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgfTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSB0ZW1wbGF0ZSBmaWxlIGZvciBhIEdpdEh1YiBwdWxsIHJlcXVlc3QuXG4gICAqL1xuICBwcml2YXRlIGNyZWF0ZVB1bGxSZXF1ZXN0KCk6IHZvaWQge1xuICAgIG5ldyBQdWxsUmVxdWVzdFRlbXBsYXRlKHRoaXMucHJvamVjdC5naXRodWIhLCB7XG4gICAgICBsaW5lczogdGhpcy5wdWxsUmVxdWVzdFRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIGJ1ZyBpc3N1ZS5cbiAgICovXG4gIHByaXZhdGUgY3JlYXRlQnVnSXNzdWUoKTogdm9pZCB7XG4gICAgbmV3IFRleHRGaWxlKHRoaXMucHJvamVjdCwgdGhpcy5idWdJc3N1ZUZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy5idWdJc3N1ZVRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIGZlYXR1cmUgaXNzdWUuXG4gICAqL1xuICBwcml2YXRlIGNyZWF0ZUZlYXR1cmVJc3N1ZSgpOiB2b2lkIHtcbiAgICBuZXcgVGV4dEZpbGUodGhpcy5wcm9qZWN0LCB0aGlzLmZlYXR1cmVJc3N1ZUZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy5mZWF0dXJlSXNzdWVUZW1wbGF0ZSxcbiAgICB9KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSB0ZW1wbGF0ZSBmaWxlIGZvciBhIEdpdEh1YiBxdWVzdGlvbiBpc3N1ZS5cbiAgICovXG4gIHByaXZhdGUgY3JlYXRlUXVlc3Rpb25Jc3N1ZSgpOiB2b2lkIHtcbiAgICBuZXcgVGV4dEZpbGUodGhpcy5wcm9qZWN0LCB0aGlzLnF1ZXN0aW9uSXNzdWVGaWxlUGF0aCwge1xuICAgICAgbGluZXM6IHRoaXMucXVlc3Rpb25Jc3N1ZVRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIHJlbGVhc2Ugd29ya2Zsb3cuXG4gICAqL1xuICBwcml2YXRlIGNyZWF0ZVJlbGVhc2VXb3JrZmxvdygpOiB2b2lkIHtcbiAgICBjb25zdCB3b3JrZmxvdzogR2l0aHViV29ya2Zsb3cgfCB1bmRlZmluZWQgPSB0aGlzLnByb2plY3QuZ2l0aHViPy5hZGRXb3JrZmxvdygnUmVsZWFzZScpO1xuICAgIHdvcmtmbG93Py5vbih0aGlzLnJlbGVhc2VXb3JrZmxvd09wdGlvbnMub24pO1xuICAgIHdvcmtmbG93Py5hZGRKb2IoJ3JlbGVhc2UnLCB0aGlzLnJlbGVhc2VXb3JrZmxvd09wdGlvbnMuam9iKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSB0ZW1wbGF0ZSBmaWxlIGZvciBhIEdpdEh1YiBzdGFsZSB3b3JrZmxvdy5cbiAgICovXG4gIHByaXZhdGUgY3JlYXRlU3RhbGVXb3JrZmxvdygpOiB2b2lkIHtcbiAgICBjb25zdCB3b3JrZmxvdzogR2l0aHViV29ya2Zsb3cgfCB1bmRlZmluZWQgPSB0aGlzLnByb2plY3QuZ2l0aHViPy5hZGRXb3JrZmxvdygnU3RhbGUnKTtcbiAgICB3b3JrZmxvdz8ub24odGhpcy5zdGFsZVdvcmtmbG93T3B0aW9ucy5vbik7XG4gICAgd29ya2Zsb3c/LmFkZEpvYignc3RhbGUnLCB0aGlzLnN0YWxlV29ya2Zsb3dPcHRpb25zLmpvYik7XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgY29uZmlndXJhdGlvbiBmaWxlIGZvciB0aGUgY2xpZmYgdG9tbCBDSEFOR0VMT0cgY3JlYXRpb24gaW4gcmVsZWFzZSB3b3JrZmxvdy5cbiAgICovXG4gIHByaXZhdGUgY3JlYXRlQ2xpZmZUb21sQ29uZmlndXJhdGlvbigpOiB2b2lkIHtcbiAgICBuZXcgVGV4dEZpbGUodGhpcy5wcm9qZWN0LCB0aGlzLmNsaWZmVG9tbEZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy5jbGlmZlRvbWxDb25maWd1cmF0aW9uLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIEFkZHMgdGVtcGxhdGUgZmlsZXMgdG8gdGhlIEdpdEh1YiBjb21wb25lbnQuXG4gICAqL1xuICBwdWJsaWMgYWRkKCk6IHZvaWQge1xuICAgIHRoaXMuY3JlYXRlUHVsbFJlcXVlc3QoKTtcbiAgICB0aGlzLmNyZWF0ZUJ1Z0lzc3VlKCk7XG4gICAgdGhpcy5jcmVhdGVGZWF0dXJlSXNzdWUoKTtcbiAgICB0aGlzLmNyZWF0ZVF1ZXN0aW9uSXNzdWUoKTtcblxuICAgIHRoaXMuY3JlYXRlUmVsZWFzZVdvcmtmbG93KCk7XG4gICAgdGhpcy5jcmVhdGVTdGFsZVdvcmtmbG93KCk7XG4gICAgdGhpcy5jcmVhdGVDbGlmZlRvbWxDb25maWd1cmF0aW9uKCk7XG4gIH1cblxuICAvKipcbiAgICogQ29uZmlndXJlcyB0aGUgYC5naXRhdHRyaWJ1dGVzYCBmaWxlIHRvIHRyZWF0IEdpdEh1YiBjb21wb25lbnQgcmVsYXRlZCBmaWxlcyBhcyBnZW5lcmF0ZWQgY29kZSwgb3B0aW1pemluZyBkaWZmcy5cbiAgICovXG4gIHB1YmxpYyB1cGRhdGVHaXRBdHRyaWJ1dGVzKCk6IHZvaWQge1xuICAgIC8vIFB1bGwgcmVxdWVzdCB0ZW1wbGF0ZSBpcyBhZGRlZCBhdXRvbWF0aWNhbGx5XG4gICAgdGhpcy5wcm9qZWN0LmdpdGF0dHJpYnV0ZXMuYWRkQXR0cmlidXRlcyhgLyR7dGhpcy5idWdJc3N1ZUZpbGVQYXRofWAsICdsaW5ndWlzdC1nZW5lcmF0ZWQnKTtcbiAgICB0aGlzLnByb2plY3QuZ2l0YXR0cmlidXRlcy5hZGRBdHRyaWJ1dGVzKGAvJHt0aGlzLmZlYXR1cmVJc3N1ZUZpbGVQYXRofWAsICdsaW5ndWlzdC1nZW5lcmF0ZWQnKTtcbiAgICB0aGlzLnByb2plY3QuZ2l0YXR0cmlidXRlcy5hZGRBdHRyaWJ1dGVzKGAvJHt0aGlzLnF1ZXN0aW9uSXNzdWVGaWxlUGF0aH1gLCAnbGluZ3Vpc3QtZ2VuZXJhdGVkJyk7XG4gICAgdGhpcy5wcm9qZWN0LmdpdGF0dHJpYnV0ZXMuYWRkQXR0cmlidXRlcyhgLyR7dGhpcy5jbGlmZlRvbWxGaWxlUGF0aH1gLCAnbGluZ3Vpc3QtZ2VuZXJhdGVkJyk7XG4gICAgLy8gV29ya2Zsb3dzIHRlbXBsYXRlcyBhcmUgYWRkZWQgYXV0b21hdGljYWxseVxuICB9XG5cbiAgLyoqXG4gICAqIEV4ZWN1dGVzIHNldHVwIGZvciB0aGUgR2l0SHViIGNvbXBvbmVudC5cbiAgICovXG4gIHB1YmxpYyBzZXR1cCgpOiB2b2lkIHtcbiAgICB0aGlzLmFkZCgpO1xuICAgIHRoaXMudXBkYXRlR2l0QXR0cmlidXRlcygpO1xuICB9XG59XG4iXX0=