"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.GitHubComponent = void 0;
const JSII_RTTI_SYMBOL_1 = Symbol.for("jsii.rtti");
const projen_1 = require("projen");
const github_1 = require("projen/lib/github");
const workflows_model_1 = require("projen/lib/github/workflows-model");
/**
 * Configures the GitHub templates, settings and npm scripts for the project.
 */
class GitHubComponent {
    /**
     * Initializes the GitHub component.
     * @param project The project to configure GitHub for.
     */
    constructor(project) {
        this.project = project;
    }
    /**
     * Getter retrieving the file path for GitHub bug issue template.
     */
    get bugIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/bug.yml';
    }
    /**
     * Getter retrieving the file path for GitHub feature issue template.
     */
    get featureIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/feature.yml';
    }
    /**
     * Getter retrieving the file path for GitHub question issue template.
     */
    get questionIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/question.yml';
    }
    /**
     * Getter retrieving the file path for the Cliff toml configuration.
     * This file is used by release workflow to create the Changelog.
     */
    get cliffTomlFilePath() {
        return 'cliff.toml';
    }
    /**
     * Getter retrieving pull request template for the GitHub configuration.
     */
    get pullRequestTemplate() {
        return [
            '## Reviewers Checklist',
            '',
            'for complete review list refer to ABS Loop - Review Aspects',
            '',
            '### Organizational Section',
            '',
            '- [ ] PR is assigned to the according feature/bug',
            '- [ ] Feature/bug is descriptive',
            '- [ ] Feature/bug is assigned to according labels',
            '- [ ] Feature/bug is assigned to a developer',
            '',
            '### Structure',
            '',
            '- [ ] Readability: Code is easy to understand, with meaningful names for variables, functions, and classes',
            '- [ ] Comments: Meaningful and helpful comments. Code is documented without being over-commented',
            '- [ ] DRY, KISS and YAGNI: Code implements only necessary features; no over-engineering',
            '- [ ] No sensitive data (e.g., passwords, API keys) in the code',
            '- [ ] No major updates for used packages',
            '',
            '### Testing',
            '',
            '- [ ] Code is locally tested by developer (if applicable)',
            '- [ ] Automated tests pass successfully',
            '<!-- Generated by projen. To modify, edit .projenrc.ts and run "npx projen".-->',
        ];
    }
    /**
     * Getter retrieving bug issue template for the GitHub configuration.
     */
    get bugIssueTemplate() {
        return [
            'name: 🐞 Bug',
            'description: File a bug/issue',
            'title: "[BUG] <title>"',
            'labels: ["type: bug"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Current behavior',
            "      description: A description of what you're experiencing.",
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Expected behavior',
            '      description: A description of what you expected to happen.',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Getter retrieving feature issue template for the GitHub configuration.
     */
    get featureIssueTemplate() {
        return [
            'name: 💡 Feature',
            'description: Story related feature',
            'title: "[FEATURE] <title>"',
            'labels: ["type: feature"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Description',
            '      description: A description of the feature.',
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Task List',
            '      description: Describe the steps to fulfill the feature.',
            '      value: |',
            '        - [ ] My First Task',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Getter retrieving question issue template for the GitHub configuration.
     */
    get questionIssueTemplate() {
        return [
            'name: ❓ Question',
            'description: Ask a question',
            'title: "[QUESTION] <title>"',
            'labels: ["type: question"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Question',
            '      description: What would you like to know? If you encounter unusual behavior or identified a missing feature, consider opening a bug report instead.',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Getter retrieving cliff toml configuration for the GitHub configuration.
     * This file is used by release workflow to create the Changelog.
     */
    get cliffTomlConfiguration() {
        return [
            '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
            '',
            '[changelog]',
            '# changelog header',
            'header = """',
            '# Changelog\n',
            'All notable changes to this project will be documented in this file.\n',
            '"""',
            '# template for the changelog body',
            '# https://keats.github.io/tera/docs/#introduction',
            'body = """',
            '{% if version %}\\',
            '    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}',
            '{% else %}\\',
            '    ## [unreleased]',
            '{% endif %}\\',
            '{% for group, commits in commits | group_by(attribute="group") %}',
            '    ### {{ group | striptags | trim | upper_first }}',
            '    {% for commit in commits %}',
            '        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\\',
            '            {% if commit.breaking %}[**breaking**] {% endif %}\\',
            '            {{ commit.message | upper_first }}\\',
            '    {% endfor %}',
            '{% endfor %}\\',
            '"""',
            '# template for the changelog footer',
            'footer = """',
            '<!-- generated by git-cliff -->',
            '"""',
            '# remove the leading and trailing s',
            'trim = true',
            '# postprocessors',
            'postprocessors = [',
            '  # { pattern = "<REPO>", replace = "https://github.com/orhun/git-cliff" }, # replace repository URL',
            ']',
            '',
            '[git]',
            '# parse the commits based on https://www.conventionalcommits.org',
            'conventional_commits = true',
            '# filter out the commits that are not conventional',
            'filter_unconventional = true',
            '# process each line of a commit as an individual commit',
            'split_commits = false',
            '# regex for preprocessing the commit messages',
            'commit_preprocessors = [',
            '  # Replace issue numbers',
            '  #{ pattern = "\\((\\w+\\s)?#([0-9]+)\\)", replace = "([#${2}](<REPO>/issues/${2}))"},',
            '  # Check spelling of the commit with https://github.com/crate-ci/typos',
            '  # If the spelling is incorrect, it will be automatically fixed.',
            '  #{ pattern = ".*", replace_command = "typos --write-changes -" },',
            ']',
            '# regex for parsing and grouping commits',
            'commit_parsers = [',
            '  { message = "^feat", group = "<!-- 0 -->🚀 Features" },',
            '  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },',
            '  { message = "^doc", group = "<!-- 3 -->📚 Documentation" },',
            '  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },',
            '  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },',
            '  { message = "^style", group = "<!-- 5 -->🎨 Styling" },',
            '  { message = "^test", group = "<!-- 6 -->🧪 Testing" },',
            '  { message = "^chore\\(release\\): prepare for", skip = true },',
            '  { message = "^chore\\(deps.*\\)", skip = true },',
            '  { message = "^chore\\(pr\\)", skip = true },',
            '  { message = "^chore\\(pull\\)", skip = true },',
            '  { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },',
            '  { body = ".*security", group = "<!-- 8 -->🛡️ Security" },',
            '  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },',
            ']',
            '# protect breaking changes from being skipped due to matching a skipping commit_parser',
            'protect_breaking_commits = false',
            '# filter out the commits that are not matched by commit parsers',
            'filter_commits = false',
            '# regex for matching git tags',
            '# tag_pattern = "v[0-9].*"',
            '# regex for skipping tags',
            '# skip_tags = ""',
            '# regex for ignoring tags',
            '# ignore_tags = ""',
            '# sort the tags topologically',
            'topo_order = false',
            '# sort the commits inside sections by oldest/newest order',
            'sort_commits = "oldest"',
            '# limit the number of commits included in the changelog.',
            '# limit_commits = 42',
        ];
    }
    /**
     * Getter retrieving release workflow template options for the GitHub configuration.
     */
    get releaseWorkflowOptions() {
        return {
            on: {
                pullRequest: {
                    branches: ['main'],
                    types: ['closed'],
                },
            },
            job: {
                runsOn: ['ubuntu-latest'],
                permissions: {
                    contents: workflows_model_1.JobPermission.WRITE,
                    pullRequests: workflows_model_1.JobPermission.WRITE,
                },
                steps: [
                    {
                        name: 'Create release',
                        uses: 'dxfrontier/gh-action-release@main',
                        with: {
                            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
                            BRANCH: 'main',
                        },
                    },
                ],
            },
        };
    }
    /**
     * Getter retrieving stale workflow template options for the GitHub configuration.
     */
    get staleWorkflowOptions() {
        return {
            on: {
                schedule: [
                    {
                        cron: '36 18 * * *',
                    },
                ],
            },
            job: {
                runsOn: ['ubuntu-latest'],
                permissions: {
                    issues: workflows_model_1.JobPermission.WRITE,
                    pullRequests: workflows_model_1.JobPermission.WRITE,
                },
                steps: [
                    {
                        uses: 'actions/stale@v5',
                        with: {
                            'repo-token': '${{ secrets.GITHUB_TOKEN }}',
                            'days-before-issue-stale': 30,
                            'stale-issue-message': 'This issue has not been updated in a while. If it is still relevant, please comment on it to keep it open. The issue will be closed soon if it remains inactive.',
                            'close-issue-message': 'This issue has been closed automatically due to inactivity.',
                            'stale-pr-message': 'This PR has not been updated in a while. If it is still relevant, please comment on it to keep it open. The PR will be closed soon if it remains inactive.',
                            'close-pr-message': 'This PR has been closed automatically due to inactivity.',
                            'stale-issue-label': 'status: stale',
                            'stale-pr-label': 'status: stale',
                            'exempt-issue-labels': 'type: feature request',
                            'exempt-pr-labels': 'type: feature request',
                            'exempt-all-milestones': true,
                        },
                    },
                ],
            },
        };
    }
    /**
     * Creates the template file for a GitHub pull request.
     */
    createPullRequest() {
        new github_1.PullRequestTemplate(this.project.github, {
            lines: this.pullRequestTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub bug issue.
     */
    createBugIssue() {
        new projen_1.TextFile(this.project, this.bugIssueFilePath, {
            lines: this.bugIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub feature issue.
     */
    createFeatureIssue() {
        new projen_1.TextFile(this.project, this.featureIssueFilePath, {
            lines: this.featureIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub question issue.
     */
    createQuestionIssue() {
        new projen_1.TextFile(this.project, this.questionIssueFilePath, {
            lines: this.questionIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub release workflow.
     */
    createReleaseWorkflow() {
        const workflow = this.project.github?.addWorkflow('Release');
        workflow?.on(this.releaseWorkflowOptions.on);
        workflow?.addJob('release', this.releaseWorkflowOptions.job);
    }
    /**
     * Creates the template file for a GitHub stale workflow.
     */
    createStaleWorkflow() {
        const workflow = this.project.github?.addWorkflow('Stale');
        workflow?.on(this.staleWorkflowOptions.on);
        workflow?.addJob('stale', this.staleWorkflowOptions.job);
    }
    /**
     * Creates the configuration file for the cliff toml CHANGELOG creation in release workflow.
     */
    createCliffTomlConfiguration() {
        new projen_1.TextFile(this.project, this.cliffTomlFilePath, {
            lines: this.cliffTomlConfiguration,
        });
    }
    /**
     * Adds template files to the GitHub component.
     */
    add() {
        this.createPullRequest();
        this.createBugIssue();
        this.createFeatureIssue();
        this.createQuestionIssue();
        this.createReleaseWorkflow();
        this.createStaleWorkflow();
        this.createCliffTomlConfiguration();
    }
    /**
     * Configures the `.gitattributes` file to treat GitHub component related files as generated code, optimizing diffs.
     */
    updateGitAttributes() {
        // Pull request template is added automatically
        this.project.gitattributes.addAttributes(`/${this.bugIssueFilePath}`, 'linguist-generated');
        this.project.gitattributes.addAttributes(`/${this.featureIssueFilePath}`, 'linguist-generated');
        this.project.gitattributes.addAttributes(`/${this.questionIssueFilePath}`, 'linguist-generated');
        this.project.gitattributes.addAttributes(`/${this.cliffTomlFilePath}`, 'linguist-generated');
        // Workflows templates are added automatically
    }
    /**
     * Executes setup for the GitHub component.
     */
    setup() {
        this.add();
        this.updateGitAttributes();
    }
}
exports.GitHubComponent = GitHubComponent;
_a = JSII_RTTI_SYMBOL_1;
GitHubComponent[_a] = { fqn: "projen-template-github-action.GitHubComponent", version: "0.0.0" };
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2l0SHViQ29tcG9uZW50LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vc3JjL2NvbXBvbmVudHMvR2l0SHViQ29tcG9uZW50LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7O0FBQUEsbUNBQWtDO0FBQ2xDLDhDQUF3RTtBQUN4RSx1RUFBaUY7QUFJakY7O0dBRUc7QUFDSCxNQUFhLGVBQWU7SUFHMUI7OztPQUdHO0lBQ0gsWUFBWSxPQUEwQjtRQUNwQyxJQUFJLENBQUMsT0FBTyxHQUFHLE9BQU8sQ0FBQztJQUN6QixDQUFDO0lBRUQ7O09BRUc7SUFDSCxJQUFZLGdCQUFnQjtRQUMxQixPQUFPLGdDQUFnQyxDQUFDO0lBQzFDLENBQUM7SUFFRDs7T0FFRztJQUNILElBQVksb0JBQW9CO1FBQzlCLE9BQU8sb0NBQW9DLENBQUM7SUFDOUMsQ0FBQztJQUVEOztPQUVHO0lBQ0gsSUFBWSxxQkFBcUI7UUFDL0IsT0FBTyxxQ0FBcUMsQ0FBQztJQUMvQyxDQUFDO0lBRUQ7OztPQUdHO0lBQ0gsSUFBWSxpQkFBaUI7UUFDM0IsT0FBTyxZQUFZLENBQUM7SUFDdEIsQ0FBQztJQUVEOztPQUVHO0lBQ0gsSUFBWSxtQkFBbUI7UUFDN0IsT0FBTztZQUNMLHdCQUF3QjtZQUN4QixFQUFFO1lBQ0YsNkRBQTZEO1lBQzdELEVBQUU7WUFDRiw0QkFBNEI7WUFDNUIsRUFBRTtZQUNGLG1EQUFtRDtZQUNuRCxrQ0FBa0M7WUFDbEMsbURBQW1EO1lBQ25ELDhDQUE4QztZQUM5QyxFQUFFO1lBQ0YsZUFBZTtZQUNmLEVBQUU7WUFDRiw0R0FBNEc7WUFDNUcsa0dBQWtHO1lBQ2xHLHlGQUF5RjtZQUN6RixpRUFBaUU7WUFDakUsMENBQTBDO1lBQzFDLEVBQUU7WUFDRixhQUFhO1lBQ2IsRUFBRTtZQUNGLDJEQUEyRDtZQUMzRCx5Q0FBeUM7WUFDekMsaUZBQWlGO1NBQ2xGLENBQUM7SUFDSixDQUFDO0lBRUQ7O09BRUc7SUFDSCxJQUFZLGdCQUFnQjtRQUMxQixPQUFPO1lBQ0wsY0FBYztZQUNkLCtCQUErQjtZQUMvQix3QkFBd0I7WUFDeEIsdUJBQXVCO1lBQ3ZCLE9BQU87WUFDUCxvQkFBb0I7WUFDcEIsaUJBQWlCO1lBQ2pCLCtCQUErQjtZQUMvQiwrREFBK0Q7WUFDL0Qsa0JBQWtCO1lBQ2xCLHNCQUFzQjtZQUN0QixFQUFFO1lBQ0Ysb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQixnQ0FBZ0M7WUFDaEMsa0VBQWtFO1lBQ2xFLGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsMkVBQTJFO1NBQzVFLENBQUM7SUFDSixDQUFDO0lBRUQ7O09BRUc7SUFDSCxJQUFZLG9CQUFvQjtRQUM5QixPQUFPO1lBQ0wsa0JBQWtCO1lBQ2xCLG9DQUFvQztZQUNwQyw0QkFBNEI7WUFDNUIsMkJBQTJCO1lBQzNCLE9BQU87WUFDUCxvQkFBb0I7WUFDcEIsaUJBQWlCO1lBQ2pCLDBCQUEwQjtZQUMxQixrREFBa0Q7WUFDbEQsa0JBQWtCO1lBQ2xCLHNCQUFzQjtZQUN0QixFQUFFO1lBQ0Ysb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQix3QkFBd0I7WUFDeEIsK0RBQStEO1lBQy9ELGdCQUFnQjtZQUNoQiw2QkFBNkI7WUFDN0Isa0JBQWtCO1lBQ2xCLHNCQUFzQjtZQUN0QiwyRUFBMkU7U0FDNUUsQ0FBQztJQUNKLENBQUM7SUFFRDs7T0FFRztJQUNILElBQVkscUJBQXFCO1FBQy9CLE9BQU87WUFDTCxrQkFBa0I7WUFDbEIsNkJBQTZCO1lBQzdCLDZCQUE2QjtZQUM3Qiw0QkFBNEI7WUFDNUIsT0FBTztZQUNQLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsdUJBQXVCO1lBQ3ZCLDJKQUEySjtZQUMzSixrQkFBa0I7WUFDbEIsc0JBQXNCO1lBQ3RCLDJFQUEyRTtTQUM1RSxDQUFDO0lBQ0osQ0FBQztJQUVEOzs7T0FHRztJQUNILElBQVksc0JBQXNCO1FBQ2hDLE9BQU87WUFDTCw4RUFBOEU7WUFDOUUsRUFBRTtZQUNGLGFBQWE7WUFDYixvQkFBb0I7WUFDcEIsY0FBYztZQUNkLGVBQWU7WUFDZix3RUFBd0U7WUFDeEUsS0FBSztZQUNMLG1DQUFtQztZQUNuQyxtREFBbUQ7WUFDbkQsWUFBWTtZQUNaLG9CQUFvQjtZQUNwQixrR0FBa0c7WUFDbEcsY0FBYztZQUNkLHFCQUFxQjtZQUNyQixlQUFlO1lBQ2YsbUVBQW1FO1lBQ25FLHNEQUFzRDtZQUN0RCxpQ0FBaUM7WUFDakMscUVBQXFFO1lBQ3JFLGtFQUFrRTtZQUNsRSxrREFBa0Q7WUFDbEQsa0JBQWtCO1lBQ2xCLGdCQUFnQjtZQUNoQixLQUFLO1lBQ0wscUNBQXFDO1lBQ3JDLGNBQWM7WUFDZCxpQ0FBaUM7WUFDakMsS0FBSztZQUNMLHFDQUFxQztZQUNyQyxhQUFhO1lBQ2Isa0JBQWtCO1lBQ2xCLG9CQUFvQjtZQUNwQixzR0FBc0c7WUFDdEcsR0FBRztZQUNILEVBQUU7WUFDRixPQUFPO1lBQ1Asa0VBQWtFO1lBQ2xFLDZCQUE2QjtZQUM3QixvREFBb0Q7WUFDcEQsOEJBQThCO1lBQzlCLHlEQUF5RDtZQUN6RCx1QkFBdUI7WUFDdkIsK0NBQStDO1lBQy9DLDBCQUEwQjtZQUMxQiwyQkFBMkI7WUFDM0IseUZBQXlGO1lBQ3pGLHlFQUF5RTtZQUN6RSxtRUFBbUU7WUFDbkUscUVBQXFFO1lBQ3JFLEdBQUc7WUFDSCwwQ0FBMEM7WUFDMUMsb0JBQW9CO1lBQ3BCLDJEQUEyRDtZQUMzRCwyREFBMkQ7WUFDM0QsK0RBQStEO1lBQy9ELDZEQUE2RDtZQUM3RCwrREFBK0Q7WUFDL0QsMkRBQTJEO1lBQzNELDBEQUEwRDtZQUMxRCxrRUFBa0U7WUFDbEUsb0RBQW9EO1lBQ3BELGdEQUFnRDtZQUNoRCxrREFBa0Q7WUFDbEQsMkVBQTJFO1lBQzNFLDhEQUE4RDtZQUM5RCwyREFBMkQ7WUFDM0QsR0FBRztZQUNILHdGQUF3RjtZQUN4RixrQ0FBa0M7WUFDbEMsaUVBQWlFO1lBQ2pFLHdCQUF3QjtZQUN4QiwrQkFBK0I7WUFDL0IsNEJBQTRCO1lBQzVCLDJCQUEyQjtZQUMzQixrQkFBa0I7WUFDbEIsMkJBQTJCO1lBQzNCLG9CQUFvQjtZQUNwQiwrQkFBK0I7WUFDL0Isb0JBQW9CO1lBQ3BCLDJEQUEyRDtZQUMzRCx5QkFBeUI7WUFDekIsMERBQTBEO1lBQzFELHNCQUFzQjtTQUN2QixDQUFDO0lBQ0osQ0FBQztJQUVEOztPQUVHO0lBQ0gsSUFBWSxzQkFBc0I7UUFDaEMsT0FBTztZQUNMLEVBQUUsRUFBRTtnQkFDRixXQUFXLEVBQUU7b0JBQ1gsUUFBUSxFQUFFLENBQUMsTUFBTSxDQUFDO29CQUNsQixLQUFLLEVBQUUsQ0FBQyxRQUFRLENBQUM7aUJBQ2xCO2FBQ0Y7WUFDRCxHQUFHLEVBQUU7Z0JBQ0gsTUFBTSxFQUFFLENBQUMsZUFBZSxDQUFDO2dCQUN6QixXQUFXLEVBQUU7b0JBQ1gsUUFBUSxFQUFFLCtCQUFhLENBQUMsS0FBSztvQkFDN0IsWUFBWSxFQUFFLCtCQUFhLENBQUMsS0FBSztpQkFDbEM7Z0JBQ0QsS0FBSyxFQUFFO29CQUNMO3dCQUNFLElBQUksRUFBRSxnQkFBZ0I7d0JBQ3RCLElBQUksRUFBRSxtQ0FBbUM7d0JBQ3pDLElBQUksRUFBRTs0QkFDSixZQUFZLEVBQUUsNkJBQTZCOzRCQUMzQyxNQUFNLEVBQUUsTUFBTTt5QkFDZjtxQkFDRjtpQkFDRjthQUNGO1NBQ0YsQ0FBQztJQUNKLENBQUM7SUFFRDs7T0FFRztJQUNILElBQVksb0JBQW9CO1FBQzlCLE9BQU87WUFDTCxFQUFFLEVBQUU7Z0JBQ0YsUUFBUSxFQUFFO29CQUNSO3dCQUNFLElBQUksRUFBRSxhQUFhO3FCQUNwQjtpQkFDRjthQUNGO1lBQ0QsR0FBRyxFQUFFO2dCQUNILE1BQU0sRUFBRSxDQUFDLGVBQWUsQ0FBQztnQkFDekIsV0FBVyxFQUFFO29CQUNYLE1BQU0sRUFBRSwrQkFBYSxDQUFDLEtBQUs7b0JBQzNCLFlBQVksRUFBRSwrQkFBYSxDQUFDLEtBQUs7aUJBQ2xDO2dCQUNELEtBQUssRUFBRTtvQkFDTDt3QkFDRSxJQUFJLEVBQUUsa0JBQWtCO3dCQUN4QixJQUFJLEVBQUU7NEJBQ0osWUFBWSxFQUFFLDZCQUE2Qjs0QkFDM0MseUJBQXlCLEVBQUUsRUFBRTs0QkFDN0IscUJBQXFCLEVBQ25CLGtLQUFrSzs0QkFDcEsscUJBQXFCLEVBQUUsNkRBQTZEOzRCQUNwRixrQkFBa0IsRUFDaEIsNEpBQTRKOzRCQUM5SixrQkFBa0IsRUFBRSwwREFBMEQ7NEJBQzlFLG1CQUFtQixFQUFFLGVBQWU7NEJBQ3BDLGdCQUFnQixFQUFFLGVBQWU7NEJBQ2pDLHFCQUFxQixFQUFFLHVCQUF1Qjs0QkFDOUMsa0JBQWtCLEVBQUUsdUJBQXVCOzRCQUMzQyx1QkFBdUIsRUFBRSxJQUFJO3lCQUM5QjtxQkFDRjtpQkFDRjthQUNGO1NBQ0YsQ0FBQztJQUNKLENBQUM7SUFFRDs7T0FFRztJQUNLLGlCQUFpQjtRQUN2QixJQUFJLDRCQUFtQixDQUFDLElBQUksQ0FBQyxPQUFPLENBQUMsTUFBTyxFQUFFO1lBQzVDLEtBQUssRUFBRSxJQUFJLENBQUMsbUJBQW1CO1NBQ2hDLENBQUMsQ0FBQztJQUNMLENBQUM7SUFFRDs7T0FFRztJQUNLLGNBQWM7UUFDcEIsSUFBSSxpQkFBUSxDQUFDLElBQUksQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLGdCQUFnQixFQUFFO1lBQ2hELEtBQUssRUFBRSxJQUFJLENBQUMsZ0JBQWdCO1NBQzdCLENBQUMsQ0FBQztJQUNMLENBQUM7SUFFRDs7T0FFRztJQUNLLGtCQUFrQjtRQUN4QixJQUFJLGlCQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxJQUFJLENBQUMsb0JBQW9CLEVBQUU7WUFDcEQsS0FBSyxFQUFFLElBQUksQ0FBQyxvQkFBb0I7U0FDakMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOztPQUVHO0lBQ0ssbUJBQW1CO1FBQ3pCLElBQUksaUJBQVEsQ0FBQyxJQUFJLENBQUMsT0FBTyxFQUFFLElBQUksQ0FBQyxxQkFBcUIsRUFBRTtZQUNyRCxLQUFLLEVBQUUsSUFBSSxDQUFDLHFCQUFxQjtTQUNsQyxDQUFDLENBQUM7SUFDTCxDQUFDO0lBRUQ7O09BRUc7SUFDSyxxQkFBcUI7UUFDM0IsTUFBTSxRQUFRLEdBQStCLElBQUksQ0FBQyxPQUFPLENBQUMsTUFBTSxFQUFFLFdBQVcsQ0FBQyxTQUFTLENBQUMsQ0FBQztRQUN6RixRQUFRLEVBQUUsRUFBRSxDQUFDLElBQUksQ0FBQyxzQkFBc0IsQ0FBQyxFQUFFLENBQUMsQ0FBQztRQUM3QyxRQUFRLEVBQUUsTUFBTSxDQUFDLFNBQVMsRUFBRSxJQUFJLENBQUMsc0JBQXNCLENBQUMsR0FBRyxDQUFDLENBQUM7SUFDL0QsQ0FBQztJQUVEOztPQUVHO0lBQ0ssbUJBQW1CO1FBQ3pCLE1BQU0sUUFBUSxHQUErQixJQUFJLENBQUMsT0FBTyxDQUFDLE1BQU0sRUFBRSxXQUFXLENBQUMsT0FBTyxDQUFDLENBQUM7UUFDdkYsUUFBUSxFQUFFLEVBQUUsQ0FBQyxJQUFJLENBQUMsb0JBQW9CLENBQUMsRUFBRSxDQUFDLENBQUM7UUFDM0MsUUFBUSxFQUFFLE1BQU0sQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLG9CQUFvQixDQUFDLEdBQUcsQ0FBQyxDQUFDO0lBQzNELENBQUM7SUFFRDs7T0FFRztJQUNLLDRCQUE0QjtRQUNsQyxJQUFJLGlCQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxJQUFJLENBQUMsaUJBQWlCLEVBQUU7WUFDakQsS0FBSyxFQUFFLElBQUksQ0FBQyxzQkFBc0I7U0FDbkMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOztPQUVHO0lBQ0ksR0FBRztRQUNSLElBQUksQ0FBQyxpQkFBaUIsRUFBRSxDQUFDO1FBQ3pCLElBQUksQ0FBQyxjQUFjLEVBQUUsQ0FBQztRQUN0QixJQUFJLENBQUMsa0JBQWtCLEVBQUUsQ0FBQztRQUMxQixJQUFJLENBQUMsbUJBQW1CLEVBQUUsQ0FBQztRQUUzQixJQUFJLENBQUMscUJBQXFCLEVBQUUsQ0FBQztRQUM3QixJQUFJLENBQUMsbUJBQW1CLEVBQUUsQ0FBQztRQUMzQixJQUFJLENBQUMsNEJBQTRCLEVBQUUsQ0FBQztJQUN0QyxDQUFDO0lBRUQ7O09BRUc7SUFDSSxtQkFBbUI7UUFDeEIsK0NBQStDO1FBQy9DLElBQUksQ0FBQyxPQUFPLENBQUMsYUFBYSxDQUFDLGFBQWEsQ0FBQyxJQUFJLElBQUksQ0FBQyxnQkFBZ0IsRUFBRSxFQUFFLG9CQUFvQixDQUFDLENBQUM7UUFDNUYsSUFBSSxDQUFDLE9BQU8sQ0FBQyxhQUFhLENBQUMsYUFBYSxDQUFDLElBQUksSUFBSSxDQUFDLG9CQUFvQixFQUFFLEVBQUUsb0JBQW9CLENBQUMsQ0FBQztRQUNoRyxJQUFJLENBQUMsT0FBTyxDQUFDLGFBQWEsQ0FBQyxhQUFhLENBQUMsSUFBSSxJQUFJLENBQUMscUJBQXFCLEVBQUUsRUFBRSxvQkFBb0IsQ0FBQyxDQUFDO1FBQ2pHLElBQUksQ0FBQyxPQUFPLENBQUMsYUFBYSxDQUFDLGFBQWEsQ0FBQyxJQUFJLElBQUksQ0FBQyxpQkFBaUIsRUFBRSxFQUFFLG9CQUFvQixDQUFDLENBQUM7UUFDN0YsOENBQThDO0lBQ2hELENBQUM7SUFFRDs7T0FFRztJQUNJLEtBQUs7UUFDVixJQUFJLENBQUMsR0FBRyxFQUFFLENBQUM7UUFDWCxJQUFJLENBQUMsbUJBQW1CLEVBQUUsQ0FBQztJQUM3QixDQUFDOztBQXpaSCwwQ0EwWkMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBUZXh0RmlsZSB9IGZyb20gJ3Byb2plbic7XG5pbXBvcnQgeyBHaXRodWJXb3JrZmxvdywgUHVsbFJlcXVlc3RUZW1wbGF0ZSB9IGZyb20gJ3Byb2plbi9saWIvZ2l0aHViJztcbmltcG9ydCB7IEpvYiwgSm9iUGVybWlzc2lvbiwgVHJpZ2dlcnMgfSBmcm9tICdwcm9qZW4vbGliL2dpdGh1Yi93b3JrZmxvd3MtbW9kZWwnO1xuaW1wb3J0IHsgVHlwZVNjcmlwdFByb2plY3QgfSBmcm9tICdwcm9qZW4vbGliL3R5cGVzY3JpcHQnO1xuaW1wb3J0IHsgSVByb2plY3RDb21wb25lbnQgfSBmcm9tICcuLi90eXBlcyc7XG5cbi8qKlxuICogQ29uZmlndXJlcyB0aGUgR2l0SHViIHRlbXBsYXRlcywgc2V0dGluZ3MgYW5kIG5wbSBzY3JpcHRzIGZvciB0aGUgcHJvamVjdC5cbiAqL1xuZXhwb3J0IGNsYXNzIEdpdEh1YkNvbXBvbmVudCBpbXBsZW1lbnRzIElQcm9qZWN0Q29tcG9uZW50IHtcbiAgcHJpdmF0ZSBwcm9qZWN0OiBUeXBlU2NyaXB0UHJvamVjdDtcblxuICAvKipcbiAgICogSW5pdGlhbGl6ZXMgdGhlIEdpdEh1YiBjb21wb25lbnQuXG4gICAqIEBwYXJhbSBwcm9qZWN0IFRoZSBwcm9qZWN0IHRvIGNvbmZpZ3VyZSBHaXRIdWIgZm9yLlxuICAgKi9cbiAgY29uc3RydWN0b3IocHJvamVjdDogVHlwZVNjcmlwdFByb2plY3QpIHtcbiAgICB0aGlzLnByb2plY3QgPSBwcm9qZWN0O1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHRoZSBmaWxlIHBhdGggZm9yIEdpdEh1YiBidWcgaXNzdWUgdGVtcGxhdGUuXG4gICAqL1xuICBwcml2YXRlIGdldCBidWdJc3N1ZUZpbGVQYXRoKCk6IHN0cmluZyB7XG4gICAgcmV0dXJuICcuZ2l0aHViL0lTU1VFX1RFTVBMQVRFL2J1Zy55bWwnO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHRoZSBmaWxlIHBhdGggZm9yIEdpdEh1YiBmZWF0dXJlIGlzc3VlIHRlbXBsYXRlLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgZmVhdHVyZUlzc3VlRmlsZVBhdGgoKTogc3RyaW5nIHtcbiAgICByZXR1cm4gJy5naXRodWIvSVNTVUVfVEVNUExBVEUvZmVhdHVyZS55bWwnO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHRoZSBmaWxlIHBhdGggZm9yIEdpdEh1YiBxdWVzdGlvbiBpc3N1ZSB0ZW1wbGF0ZS5cbiAgICovXG4gIHByaXZhdGUgZ2V0IHF1ZXN0aW9uSXNzdWVGaWxlUGF0aCgpOiBzdHJpbmcge1xuICAgIHJldHVybiAnLmdpdGh1Yi9JU1NVRV9URU1QTEFURS9xdWVzdGlvbi55bWwnO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHRoZSBmaWxlIHBhdGggZm9yIHRoZSBDbGlmZiB0b21sIGNvbmZpZ3VyYXRpb24uXG4gICAqIFRoaXMgZmlsZSBpcyB1c2VkIGJ5IHJlbGVhc2Ugd29ya2Zsb3cgdG8gY3JlYXRlIHRoZSBDaGFuZ2Vsb2cuXG4gICAqL1xuICBwcml2YXRlIGdldCBjbGlmZlRvbWxGaWxlUGF0aCgpOiBzdHJpbmcge1xuICAgIHJldHVybiAnY2xpZmYudG9tbCc7XG4gIH1cblxuICAvKipcbiAgICogR2V0dGVyIHJldHJpZXZpbmcgcHVsbCByZXF1ZXN0IHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIGNvbmZpZ3VyYXRpb24uXG4gICAqL1xuICBwcml2YXRlIGdldCBwdWxsUmVxdWVzdFRlbXBsYXRlKCk6IHN0cmluZ1tdIHtcbiAgICByZXR1cm4gW1xuICAgICAgJyMjIFJldmlld2VycyBDaGVja2xpc3QnLFxuICAgICAgJycsXG4gICAgICAnZm9yIGNvbXBsZXRlIHJldmlldyBsaXN0IHJlZmVyIHRvIEFCUyBMb29wIC0gUmV2aWV3IEFzcGVjdHMnLFxuICAgICAgJycsXG4gICAgICAnIyMjIE9yZ2FuaXphdGlvbmFsIFNlY3Rpb24nLFxuICAgICAgJycsXG4gICAgICAnLSBbIF0gUFIgaXMgYXNzaWduZWQgdG8gdGhlIGFjY29yZGluZyBmZWF0dXJlL2J1ZycsXG4gICAgICAnLSBbIF0gRmVhdHVyZS9idWcgaXMgZGVzY3JpcHRpdmUnLFxuICAgICAgJy0gWyBdIEZlYXR1cmUvYnVnIGlzIGFzc2lnbmVkIHRvIGFjY29yZGluZyBsYWJlbHMnLFxuICAgICAgJy0gWyBdIEZlYXR1cmUvYnVnIGlzIGFzc2lnbmVkIHRvIGEgZGV2ZWxvcGVyJyxcbiAgICAgICcnLFxuICAgICAgJyMjIyBTdHJ1Y3R1cmUnLFxuICAgICAgJycsXG4gICAgICAnLSBbIF0gUmVhZGFiaWxpdHk6IENvZGUgaXMgZWFzeSB0byB1bmRlcnN0YW5kLCB3aXRoIG1lYW5pbmdmdWwgbmFtZXMgZm9yIHZhcmlhYmxlcywgZnVuY3Rpb25zLCBhbmQgY2xhc3NlcycsXG4gICAgICAnLSBbIF0gQ29tbWVudHM6IE1lYW5pbmdmdWwgYW5kIGhlbHBmdWwgY29tbWVudHMuIENvZGUgaXMgZG9jdW1lbnRlZCB3aXRob3V0IGJlaW5nIG92ZXItY29tbWVudGVkJyxcbiAgICAgICctIFsgXSBEUlksIEtJU1MgYW5kIFlBR05JOiBDb2RlIGltcGxlbWVudHMgb25seSBuZWNlc3NhcnkgZmVhdHVyZXM7IG5vIG92ZXItZW5naW5lZXJpbmcnLFxuICAgICAgJy0gWyBdIE5vIHNlbnNpdGl2ZSBkYXRhIChlLmcuLCBwYXNzd29yZHMsIEFQSSBrZXlzKSBpbiB0aGUgY29kZScsXG4gICAgICAnLSBbIF0gTm8gbWFqb3IgdXBkYXRlcyBmb3IgdXNlZCBwYWNrYWdlcycsXG4gICAgICAnJyxcbiAgICAgICcjIyMgVGVzdGluZycsXG4gICAgICAnJyxcbiAgICAgICctIFsgXSBDb2RlIGlzIGxvY2FsbHkgdGVzdGVkIGJ5IGRldmVsb3BlciAoaWYgYXBwbGljYWJsZSknLFxuICAgICAgJy0gWyBdIEF1dG9tYXRlZCB0ZXN0cyBwYXNzIHN1Y2Nlc3NmdWxseScsXG4gICAgICAnPCEtLSBHZW5lcmF0ZWQgYnkgcHJvamVuLiBUbyBtb2RpZnksIGVkaXQgLnByb2plbnJjLnRzIGFuZCBydW4gXCJucHggcHJvamVuXCIuLS0+JyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIGJ1ZyBpc3N1ZSB0ZW1wbGF0ZSBmb3IgdGhlIEdpdEh1YiBjb25maWd1cmF0aW9uLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgYnVnSXNzdWVUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICduYW1lOiDwn5CeIEJ1ZycsXG4gICAgICAnZGVzY3JpcHRpb246IEZpbGUgYSBidWcvaXNzdWUnLFxuICAgICAgJ3RpdGxlOiBcIltCVUddIDx0aXRsZT5cIicsXG4gICAgICAnbGFiZWxzOiBbXCJ0eXBlOiBidWdcIl0nLFxuICAgICAgJ2JvZHk6JyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IEN1cnJlbnQgYmVoYXZpb3InLFxuICAgICAgXCIgICAgICBkZXNjcmlwdGlvbjogQSBkZXNjcmlwdGlvbiBvZiB3aGF0IHlvdSdyZSBleHBlcmllbmNpbmcuXCIsXG4gICAgICAnICAgIHZhbGlkYXRpb25zOicsXG4gICAgICAnICAgICAgcmVxdWlyZWQ6IHRydWUnLFxuICAgICAgJycsXG4gICAgICAnICAtIHR5cGU6IHRleHRhcmVhJyxcbiAgICAgICcgICAgYXR0cmlidXRlczonLFxuICAgICAgJyAgICAgIGxhYmVsOiBFeHBlY3RlZCBiZWhhdmlvcicsXG4gICAgICAnICAgICAgZGVzY3JpcHRpb246IEEgZGVzY3JpcHRpb24gb2Ygd2hhdCB5b3UgZXhwZWN0ZWQgdG8gaGFwcGVuLicsXG4gICAgICAnICAgIHZhbGlkYXRpb25zOicsXG4gICAgICAnICAgICAgcmVxdWlyZWQ6IHRydWUnLFxuICAgICAgJyMgR2VuZXJhdGVkIGJ5IHByb2plbi4gVG8gbW9kaWZ5LCBlZGl0IC5wcm9qZW5yYy50cyBhbmQgcnVuIFwibnB4IHByb2plblwiLicsXG4gICAgXTtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXR0ZXIgcmV0cmlldmluZyBmZWF0dXJlIGlzc3VlIHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIGNvbmZpZ3VyYXRpb24uXG4gICAqL1xuICBwcml2YXRlIGdldCBmZWF0dXJlSXNzdWVUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICduYW1lOiDwn5KhIEZlYXR1cmUnLFxuICAgICAgJ2Rlc2NyaXB0aW9uOiBTdG9yeSByZWxhdGVkIGZlYXR1cmUnLFxuICAgICAgJ3RpdGxlOiBcIltGRUFUVVJFXSA8dGl0bGU+XCInLFxuICAgICAgJ2xhYmVsczogW1widHlwZTogZmVhdHVyZVwiXScsXG4gICAgICAnYm9keTonLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogRGVzY3JpcHRpb24nLFxuICAgICAgJyAgICAgIGRlc2NyaXB0aW9uOiBBIGRlc2NyaXB0aW9uIG9mIHRoZSBmZWF0dXJlLicsXG4gICAgICAnICAgIHZhbGlkYXRpb25zOicsXG4gICAgICAnICAgICAgcmVxdWlyZWQ6IHRydWUnLFxuICAgICAgJycsXG4gICAgICAnICAtIHR5cGU6IHRleHRhcmVhJyxcbiAgICAgICcgICAgYXR0cmlidXRlczonLFxuICAgICAgJyAgICAgIGxhYmVsOiBUYXNrIExpc3QnLFxuICAgICAgJyAgICAgIGRlc2NyaXB0aW9uOiBEZXNjcmliZSB0aGUgc3RlcHMgdG8gZnVsZmlsbCB0aGUgZmVhdHVyZS4nLFxuICAgICAgJyAgICAgIHZhbHVlOiB8JyxcbiAgICAgICcgICAgICAgIC0gWyBdIE15IEZpcnN0IFRhc2snLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcjIEdlbmVyYXRlZCBieSBwcm9qZW4uIFRvIG1vZGlmeSwgZWRpdCAucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4nLFxuICAgIF07XG4gIH1cblxuICAvKipcbiAgICogR2V0dGVyIHJldHJpZXZpbmcgcXVlc3Rpb24gaXNzdWUgdGVtcGxhdGUgZm9yIHRoZSBHaXRIdWIgY29uZmlndXJhdGlvbi5cbiAgICovXG4gIHByaXZhdGUgZ2V0IHF1ZXN0aW9uSXNzdWVUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICduYW1lOiDinZMgUXVlc3Rpb24nLFxuICAgICAgJ2Rlc2NyaXB0aW9uOiBBc2sgYSBxdWVzdGlvbicsXG4gICAgICAndGl0bGU6IFwiW1FVRVNUSU9OXSA8dGl0bGU+XCInLFxuICAgICAgJ2xhYmVsczogW1widHlwZTogcXVlc3Rpb25cIl0nLFxuICAgICAgJ2JvZHk6JyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IFF1ZXN0aW9uJyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogV2hhdCB3b3VsZCB5b3UgbGlrZSB0byBrbm93PyBJZiB5b3UgZW5jb3VudGVyIHVudXN1YWwgYmVoYXZpb3Igb3IgaWRlbnRpZmllZCBhIG1pc3NpbmcgZmVhdHVyZSwgY29uc2lkZXIgb3BlbmluZyBhIGJ1ZyByZXBvcnQgaW5zdGVhZC4nLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcjIEdlbmVyYXRlZCBieSBwcm9qZW4uIFRvIG1vZGlmeSwgZWRpdCAucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4nLFxuICAgIF07XG4gIH1cblxuICAvKipcbiAgICogR2V0dGVyIHJldHJpZXZpbmcgY2xpZmYgdG9tbCBjb25maWd1cmF0aW9uIGZvciB0aGUgR2l0SHViIGNvbmZpZ3VyYXRpb24uXG4gICAqIFRoaXMgZmlsZSBpcyB1c2VkIGJ5IHJlbGVhc2Ugd29ya2Zsb3cgdG8gY3JlYXRlIHRoZSBDaGFuZ2Vsb2cuXG4gICAqL1xuICBwcml2YXRlIGdldCBjbGlmZlRvbWxDb25maWd1cmF0aW9uKCk6IHN0cmluZ1tdIHtcbiAgICByZXR1cm4gW1xuICAgICAgJyMgfn4gR2VuZXJhdGVkIGJ5IHByb2plbi4gVG8gbW9kaWZ5LCBlZGl0IC5wcm9qZW5yYy50cyBhbmQgcnVuIFwibnB4IHByb2plblwiLicsXG4gICAgICAnJyxcbiAgICAgICdbY2hhbmdlbG9nXScsXG4gICAgICAnIyBjaGFuZ2Vsb2cgaGVhZGVyJyxcbiAgICAgICdoZWFkZXIgPSBcIlwiXCInLFxuICAgICAgJyMgQ2hhbmdlbG9nXFxuJyxcbiAgICAgICdBbGwgbm90YWJsZSBjaGFuZ2VzIHRvIHRoaXMgcHJvamVjdCB3aWxsIGJlIGRvY3VtZW50ZWQgaW4gdGhpcyBmaWxlLlxcbicsXG4gICAgICAnXCJcIlwiJyxcbiAgICAgICcjIHRlbXBsYXRlIGZvciB0aGUgY2hhbmdlbG9nIGJvZHknLFxuICAgICAgJyMgaHR0cHM6Ly9rZWF0cy5naXRodWIuaW8vdGVyYS9kb2NzLyNpbnRyb2R1Y3Rpb24nLFxuICAgICAgJ2JvZHkgPSBcIlwiXCInLFxuICAgICAgJ3slIGlmIHZlcnNpb24gJX1cXFxcJyxcbiAgICAgICcgICAgIyMgW3t7IHZlcnNpb24gfCB0cmltX3N0YXJ0X21hdGNoZXMocGF0PVwidlwiKSB9fV0gLSB7eyB0aW1lc3RhbXAgfCBkYXRlKGZvcm1hdD1cIiVZLSVtLSVkXCIpIH19JyxcbiAgICAgICd7JSBlbHNlICV9XFxcXCcsXG4gICAgICAnICAgICMjIFt1bnJlbGVhc2VkXScsXG4gICAgICAneyUgZW5kaWYgJX1cXFxcJyxcbiAgICAgICd7JSBmb3IgZ3JvdXAsIGNvbW1pdHMgaW4gY29tbWl0cyB8IGdyb3VwX2J5KGF0dHJpYnV0ZT1cImdyb3VwXCIpICV9JyxcbiAgICAgICcgICAgIyMjIHt7IGdyb3VwIHwgc3RyaXB0YWdzIHwgdHJpbSB8IHVwcGVyX2ZpcnN0IH19JyxcbiAgICAgICcgICAgeyUgZm9yIGNvbW1pdCBpbiBjb21taXRzICV9JyxcbiAgICAgICcgICAgICAgIC0geyUgaWYgY29tbWl0LnNjb3BlICV9Kih7eyBjb21taXQuc2NvcGUgfX0pKiB7JSBlbmRpZiAlfVxcXFwnLFxuICAgICAgJyAgICAgICAgICAgIHslIGlmIGNvbW1pdC5icmVha2luZyAlfVsqKmJyZWFraW5nKipdIHslIGVuZGlmICV9XFxcXCcsXG4gICAgICAnICAgICAgICAgICAge3sgY29tbWl0Lm1lc3NhZ2UgfCB1cHBlcl9maXJzdCB9fVxcXFwnLFxuICAgICAgJyAgICB7JSBlbmRmb3IgJX0nLFxuICAgICAgJ3slIGVuZGZvciAlfVxcXFwnLFxuICAgICAgJ1wiXCJcIicsXG4gICAgICAnIyB0ZW1wbGF0ZSBmb3IgdGhlIGNoYW5nZWxvZyBmb290ZXInLFxuICAgICAgJ2Zvb3RlciA9IFwiXCJcIicsXG4gICAgICAnPCEtLSBnZW5lcmF0ZWQgYnkgZ2l0LWNsaWZmIC0tPicsXG4gICAgICAnXCJcIlwiJyxcbiAgICAgICcjIHJlbW92ZSB0aGUgbGVhZGluZyBhbmQgdHJhaWxpbmcgcycsXG4gICAgICAndHJpbSA9IHRydWUnLFxuICAgICAgJyMgcG9zdHByb2Nlc3NvcnMnLFxuICAgICAgJ3Bvc3Rwcm9jZXNzb3JzID0gWycsXG4gICAgICAnICAjIHsgcGF0dGVybiA9IFwiPFJFUE8+XCIsIHJlcGxhY2UgPSBcImh0dHBzOi8vZ2l0aHViLmNvbS9vcmh1bi9naXQtY2xpZmZcIiB9LCAjIHJlcGxhY2UgcmVwb3NpdG9yeSBVUkwnLFxuICAgICAgJ10nLFxuICAgICAgJycsXG4gICAgICAnW2dpdF0nLFxuICAgICAgJyMgcGFyc2UgdGhlIGNvbW1pdHMgYmFzZWQgb24gaHR0cHM6Ly93d3cuY29udmVudGlvbmFsY29tbWl0cy5vcmcnLFxuICAgICAgJ2NvbnZlbnRpb25hbF9jb21taXRzID0gdHJ1ZScsXG4gICAgICAnIyBmaWx0ZXIgb3V0IHRoZSBjb21taXRzIHRoYXQgYXJlIG5vdCBjb252ZW50aW9uYWwnLFxuICAgICAgJ2ZpbHRlcl91bmNvbnZlbnRpb25hbCA9IHRydWUnLFxuICAgICAgJyMgcHJvY2VzcyBlYWNoIGxpbmUgb2YgYSBjb21taXQgYXMgYW4gaW5kaXZpZHVhbCBjb21taXQnLFxuICAgICAgJ3NwbGl0X2NvbW1pdHMgPSBmYWxzZScsXG4gICAgICAnIyByZWdleCBmb3IgcHJlcHJvY2Vzc2luZyB0aGUgY29tbWl0IG1lc3NhZ2VzJyxcbiAgICAgICdjb21taXRfcHJlcHJvY2Vzc29ycyA9IFsnLFxuICAgICAgJyAgIyBSZXBsYWNlIGlzc3VlIG51bWJlcnMnLFxuICAgICAgJyAgI3sgcGF0dGVybiA9IFwiXFxcXCgoXFxcXHcrXFxcXHMpPyMoWzAtOV0rKVxcXFwpXCIsIHJlcGxhY2UgPSBcIihbIyR7Mn1dKDxSRVBPPi9pc3N1ZXMvJHsyfSkpXCJ9LCcsXG4gICAgICAnICAjIENoZWNrIHNwZWxsaW5nIG9mIHRoZSBjb21taXQgd2l0aCBodHRwczovL2dpdGh1Yi5jb20vY3JhdGUtY2kvdHlwb3MnLFxuICAgICAgJyAgIyBJZiB0aGUgc3BlbGxpbmcgaXMgaW5jb3JyZWN0LCBpdCB3aWxsIGJlIGF1dG9tYXRpY2FsbHkgZml4ZWQuJyxcbiAgICAgICcgICN7IHBhdHRlcm4gPSBcIi4qXCIsIHJlcGxhY2VfY29tbWFuZCA9IFwidHlwb3MgLS13cml0ZS1jaGFuZ2VzIC1cIiB9LCcsXG4gICAgICAnXScsXG4gICAgICAnIyByZWdleCBmb3IgcGFyc2luZyBhbmQgZ3JvdXBpbmcgY29tbWl0cycsXG4gICAgICAnY29tbWl0X3BhcnNlcnMgPSBbJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmZlYXRcIiwgZ3JvdXAgPSBcIjwhLS0gMCAtLT7wn5qAIEZlYXR1cmVzXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeZml4XCIsIGdyb3VwID0gXCI8IS0tIDEgLS0+8J+QmyBCdWcgRml4ZXNcIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5kb2NcIiwgZ3JvdXAgPSBcIjwhLS0gMyAtLT7wn5OaIERvY3VtZW50YXRpb25cIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5wZXJmXCIsIGdyb3VwID0gXCI8IS0tIDQgLS0+4pqhIFBlcmZvcm1hbmNlXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJecmVmYWN0b3JcIiwgZ3JvdXAgPSBcIjwhLS0gMiAtLT7wn5qcIFJlZmFjdG9yXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJec3R5bGVcIiwgZ3JvdXAgPSBcIjwhLS0gNSAtLT7wn46oIFN0eWxpbmdcIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl50ZXN0XCIsIGdyb3VwID0gXCI8IS0tIDYgLS0+8J+nqiBUZXN0aW5nXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeY2hvcmVcXFxcKHJlbGVhc2VcXFxcKTogcHJlcGFyZSBmb3JcIiwgc2tpcCA9IHRydWUgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeY2hvcmVcXFxcKGRlcHMuKlxcXFwpXCIsIHNraXAgPSB0cnVlIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmNob3JlXFxcXChwclxcXFwpXCIsIHNraXAgPSB0cnVlIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmNob3JlXFxcXChwdWxsXFxcXClcIiwgc2tpcCA9IHRydWUgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeY2hvcmV8XmNpXCIsIGdyb3VwID0gXCI8IS0tIDcgLS0+4pqZ77iPIE1pc2NlbGxhbmVvdXMgVGFza3NcIiB9LCcsXG4gICAgICAnICB7IGJvZHkgPSBcIi4qc2VjdXJpdHlcIiwgZ3JvdXAgPSBcIjwhLS0gOCAtLT7wn5uh77iPIFNlY3VyaXR5XCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJecmV2ZXJ0XCIsIGdyb3VwID0gXCI8IS0tIDkgLS0+4peA77iPIFJldmVydFwiIH0sJyxcbiAgICAgICddJyxcbiAgICAgICcjIHByb3RlY3QgYnJlYWtpbmcgY2hhbmdlcyBmcm9tIGJlaW5nIHNraXBwZWQgZHVlIHRvIG1hdGNoaW5nIGEgc2tpcHBpbmcgY29tbWl0X3BhcnNlcicsXG4gICAgICAncHJvdGVjdF9icmVha2luZ19jb21taXRzID0gZmFsc2UnLFxuICAgICAgJyMgZmlsdGVyIG91dCB0aGUgY29tbWl0cyB0aGF0IGFyZSBub3QgbWF0Y2hlZCBieSBjb21taXQgcGFyc2VycycsXG4gICAgICAnZmlsdGVyX2NvbW1pdHMgPSBmYWxzZScsXG4gICAgICAnIyByZWdleCBmb3IgbWF0Y2hpbmcgZ2l0IHRhZ3MnLFxuICAgICAgJyMgdGFnX3BhdHRlcm4gPSBcInZbMC05XS4qXCInLFxuICAgICAgJyMgcmVnZXggZm9yIHNraXBwaW5nIHRhZ3MnLFxuICAgICAgJyMgc2tpcF90YWdzID0gXCJcIicsXG4gICAgICAnIyByZWdleCBmb3IgaWdub3JpbmcgdGFncycsXG4gICAgICAnIyBpZ25vcmVfdGFncyA9IFwiXCInLFxuICAgICAgJyMgc29ydCB0aGUgdGFncyB0b3BvbG9naWNhbGx5JyxcbiAgICAgICd0b3BvX29yZGVyID0gZmFsc2UnLFxuICAgICAgJyMgc29ydCB0aGUgY29tbWl0cyBpbnNpZGUgc2VjdGlvbnMgYnkgb2xkZXN0L25ld2VzdCBvcmRlcicsXG4gICAgICAnc29ydF9jb21taXRzID0gXCJvbGRlc3RcIicsXG4gICAgICAnIyBsaW1pdCB0aGUgbnVtYmVyIG9mIGNvbW1pdHMgaW5jbHVkZWQgaW4gdGhlIGNoYW5nZWxvZy4nLFxuICAgICAgJyMgbGltaXRfY29tbWl0cyA9IDQyJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHJlbGVhc2Ugd29ya2Zsb3cgdGVtcGxhdGUgb3B0aW9ucyBmb3IgdGhlIEdpdEh1YiBjb25maWd1cmF0aW9uLlxuICAgKi9cbiAgcHJpdmF0ZSBnZXQgcmVsZWFzZVdvcmtmbG93T3B0aW9ucygpOiB7IG9uOiBUcmlnZ2Vyczsgam9iOiBKb2IgfSB7XG4gICAgcmV0dXJuIHtcbiAgICAgIG9uOiB7XG4gICAgICAgIHB1bGxSZXF1ZXN0OiB7XG4gICAgICAgICAgYnJhbmNoZXM6IFsnbWFpbiddLFxuICAgICAgICAgIHR5cGVzOiBbJ2Nsb3NlZCddLFxuICAgICAgICB9LFxuICAgICAgfSxcbiAgICAgIGpvYjoge1xuICAgICAgICBydW5zT246IFsndWJ1bnR1LWxhdGVzdCddLFxuICAgICAgICBwZXJtaXNzaW9uczoge1xuICAgICAgICAgIGNvbnRlbnRzOiBKb2JQZXJtaXNzaW9uLldSSVRFLFxuICAgICAgICAgIHB1bGxSZXF1ZXN0czogSm9iUGVybWlzc2lvbi5XUklURSxcbiAgICAgICAgfSxcbiAgICAgICAgc3RlcHM6IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBuYW1lOiAnQ3JlYXRlIHJlbGVhc2UnLFxuICAgICAgICAgICAgdXNlczogJ2R4ZnJvbnRpZXIvZ2gtYWN0aW9uLXJlbGVhc2VAbWFpbicsXG4gICAgICAgICAgICB3aXRoOiB7XG4gICAgICAgICAgICAgIEdJVEhVQl9UT0tFTjogJyR7eyBzZWNyZXRzLkdJVEhVQl9UT0tFTiB9fScsXG4gICAgICAgICAgICAgIEJSQU5DSDogJ21haW4nLFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICB9O1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHRlciByZXRyaWV2aW5nIHN0YWxlIHdvcmtmbG93IHRlbXBsYXRlIG9wdGlvbnMgZm9yIHRoZSBHaXRIdWIgY29uZmlndXJhdGlvbi5cbiAgICovXG4gIHByaXZhdGUgZ2V0IHN0YWxlV29ya2Zsb3dPcHRpb25zKCk6IHsgb246IFRyaWdnZXJzOyBqb2I6IEpvYiB9IHtcbiAgICByZXR1cm4ge1xuICAgICAgb246IHtcbiAgICAgICAgc2NoZWR1bGU6IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBjcm9uOiAnMzYgMTggKiAqIConLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAgam9iOiB7XG4gICAgICAgIHJ1bnNPbjogWyd1YnVudHUtbGF0ZXN0J10sXG4gICAgICAgIHBlcm1pc3Npb25zOiB7XG4gICAgICAgICAgaXNzdWVzOiBKb2JQZXJtaXNzaW9uLldSSVRFLFxuICAgICAgICAgIHB1bGxSZXF1ZXN0czogSm9iUGVybWlzc2lvbi5XUklURSxcbiAgICAgICAgfSxcbiAgICAgICAgc3RlcHM6IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB1c2VzOiAnYWN0aW9ucy9zdGFsZUB2NScsXG4gICAgICAgICAgICB3aXRoOiB7XG4gICAgICAgICAgICAgICdyZXBvLXRva2VuJzogJyR7eyBzZWNyZXRzLkdJVEhVQl9UT0tFTiB9fScsXG4gICAgICAgICAgICAgICdkYXlzLWJlZm9yZS1pc3N1ZS1zdGFsZSc6IDMwLFxuICAgICAgICAgICAgICAnc3RhbGUtaXNzdWUtbWVzc2FnZSc6XG4gICAgICAgICAgICAgICAgJ1RoaXMgaXNzdWUgaGFzIG5vdCBiZWVuIHVwZGF0ZWQgaW4gYSB3aGlsZS4gSWYgaXQgaXMgc3RpbGwgcmVsZXZhbnQsIHBsZWFzZSBjb21tZW50IG9uIGl0IHRvIGtlZXAgaXQgb3Blbi4gVGhlIGlzc3VlIHdpbGwgYmUgY2xvc2VkIHNvb24gaWYgaXQgcmVtYWlucyBpbmFjdGl2ZS4nLFxuICAgICAgICAgICAgICAnY2xvc2UtaXNzdWUtbWVzc2FnZSc6ICdUaGlzIGlzc3VlIGhhcyBiZWVuIGNsb3NlZCBhdXRvbWF0aWNhbGx5IGR1ZSB0byBpbmFjdGl2aXR5LicsXG4gICAgICAgICAgICAgICdzdGFsZS1wci1tZXNzYWdlJzpcbiAgICAgICAgICAgICAgICAnVGhpcyBQUiBoYXMgbm90IGJlZW4gdXBkYXRlZCBpbiBhIHdoaWxlLiBJZiBpdCBpcyBzdGlsbCByZWxldmFudCwgcGxlYXNlIGNvbW1lbnQgb24gaXQgdG8ga2VlcCBpdCBvcGVuLiBUaGUgUFIgd2lsbCBiZSBjbG9zZWQgc29vbiBpZiBpdCByZW1haW5zIGluYWN0aXZlLicsXG4gICAgICAgICAgICAgICdjbG9zZS1wci1tZXNzYWdlJzogJ1RoaXMgUFIgaGFzIGJlZW4gY2xvc2VkIGF1dG9tYXRpY2FsbHkgZHVlIHRvIGluYWN0aXZpdHkuJyxcbiAgICAgICAgICAgICAgJ3N0YWxlLWlzc3VlLWxhYmVsJzogJ3N0YXR1czogc3RhbGUnLFxuICAgICAgICAgICAgICAnc3RhbGUtcHItbGFiZWwnOiAnc3RhdHVzOiBzdGFsZScsXG4gICAgICAgICAgICAgICdleGVtcHQtaXNzdWUtbGFiZWxzJzogJ3R5cGU6IGZlYXR1cmUgcmVxdWVzdCcsXG4gICAgICAgICAgICAgICdleGVtcHQtcHItbGFiZWxzJzogJ3R5cGU6IGZlYXR1cmUgcmVxdWVzdCcsXG4gICAgICAgICAgICAgICdleGVtcHQtYWxsLW1pbGVzdG9uZXMnOiB0cnVlLFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICB9O1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIHB1bGwgcmVxdWVzdC5cbiAgICovXG4gIHByaXZhdGUgY3JlYXRlUHVsbFJlcXVlc3QoKTogdm9pZCB7XG4gICAgbmV3IFB1bGxSZXF1ZXN0VGVtcGxhdGUodGhpcy5wcm9qZWN0LmdpdGh1YiEsIHtcbiAgICAgIGxpbmVzOiB0aGlzLnB1bGxSZXF1ZXN0VGVtcGxhdGUsXG4gICAgfSk7XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgdGVtcGxhdGUgZmlsZSBmb3IgYSBHaXRIdWIgYnVnIGlzc3VlLlxuICAgKi9cbiAgcHJpdmF0ZSBjcmVhdGVCdWdJc3N1ZSgpOiB2b2lkIHtcbiAgICBuZXcgVGV4dEZpbGUodGhpcy5wcm9qZWN0LCB0aGlzLmJ1Z0lzc3VlRmlsZVBhdGgsIHtcbiAgICAgIGxpbmVzOiB0aGlzLmJ1Z0lzc3VlVGVtcGxhdGUsXG4gICAgfSk7XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgdGVtcGxhdGUgZmlsZSBmb3IgYSBHaXRIdWIgZmVhdHVyZSBpc3N1ZS5cbiAgICovXG4gIHByaXZhdGUgY3JlYXRlRmVhdHVyZUlzc3VlKCk6IHZvaWQge1xuICAgIG5ldyBUZXh0RmlsZSh0aGlzLnByb2plY3QsIHRoaXMuZmVhdHVyZUlzc3VlRmlsZVBhdGgsIHtcbiAgICAgIGxpbmVzOiB0aGlzLmZlYXR1cmVJc3N1ZVRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIHF1ZXN0aW9uIGlzc3VlLlxuICAgKi9cbiAgcHJpdmF0ZSBjcmVhdGVRdWVzdGlvbklzc3VlKCk6IHZvaWQge1xuICAgIG5ldyBUZXh0RmlsZSh0aGlzLnByb2plY3QsIHRoaXMucXVlc3Rpb25Jc3N1ZUZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy5xdWVzdGlvbklzc3VlVGVtcGxhdGUsXG4gICAgfSk7XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgdGVtcGxhdGUgZmlsZSBmb3IgYSBHaXRIdWIgcmVsZWFzZSB3b3JrZmxvdy5cbiAgICovXG4gIHByaXZhdGUgY3JlYXRlUmVsZWFzZVdvcmtmbG93KCk6IHZvaWQge1xuICAgIGNvbnN0IHdvcmtmbG93OiBHaXRodWJXb3JrZmxvdyB8IHVuZGVmaW5lZCA9IHRoaXMucHJvamVjdC5naXRodWI/LmFkZFdvcmtmbG93KCdSZWxlYXNlJyk7XG4gICAgd29ya2Zsb3c/Lm9uKHRoaXMucmVsZWFzZVdvcmtmbG93T3B0aW9ucy5vbik7XG4gICAgd29ya2Zsb3c/LmFkZEpvYigncmVsZWFzZScsIHRoaXMucmVsZWFzZVdvcmtmbG93T3B0aW9ucy5qb2IpO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIHN0YWxlIHdvcmtmbG93LlxuICAgKi9cbiAgcHJpdmF0ZSBjcmVhdGVTdGFsZVdvcmtmbG93KCk6IHZvaWQge1xuICAgIGNvbnN0IHdvcmtmbG93OiBHaXRodWJXb3JrZmxvdyB8IHVuZGVmaW5lZCA9IHRoaXMucHJvamVjdC5naXRodWI/LmFkZFdvcmtmbG93KCdTdGFsZScpO1xuICAgIHdvcmtmbG93Py5vbih0aGlzLnN0YWxlV29ya2Zsb3dPcHRpb25zLm9uKTtcbiAgICB3b3JrZmxvdz8uYWRkSm9iKCdzdGFsZScsIHRoaXMuc3RhbGVXb3JrZmxvd09wdGlvbnMuam9iKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSBjb25maWd1cmF0aW9uIGZpbGUgZm9yIHRoZSBjbGlmZiB0b21sIENIQU5HRUxPRyBjcmVhdGlvbiBpbiByZWxlYXNlIHdvcmtmbG93LlxuICAgKi9cbiAgcHJpdmF0ZSBjcmVhdGVDbGlmZlRvbWxDb25maWd1cmF0aW9uKCk6IHZvaWQge1xuICAgIG5ldyBUZXh0RmlsZSh0aGlzLnByb2plY3QsIHRoaXMuY2xpZmZUb21sRmlsZVBhdGgsIHtcbiAgICAgIGxpbmVzOiB0aGlzLmNsaWZmVG9tbENvbmZpZ3VyYXRpb24sXG4gICAgfSk7XG4gIH1cblxuICAvKipcbiAgICogQWRkcyB0ZW1wbGF0ZSBmaWxlcyB0byB0aGUgR2l0SHViIGNvbXBvbmVudC5cbiAgICovXG4gIHB1YmxpYyBhZGQoKTogdm9pZCB7XG4gICAgdGhpcy5jcmVhdGVQdWxsUmVxdWVzdCgpO1xuICAgIHRoaXMuY3JlYXRlQnVnSXNzdWUoKTtcbiAgICB0aGlzLmNyZWF0ZUZlYXR1cmVJc3N1ZSgpO1xuICAgIHRoaXMuY3JlYXRlUXVlc3Rpb25Jc3N1ZSgpO1xuXG4gICAgdGhpcy5jcmVhdGVSZWxlYXNlV29ya2Zsb3coKTtcbiAgICB0aGlzLmNyZWF0ZVN0YWxlV29ya2Zsb3coKTtcbiAgICB0aGlzLmNyZWF0ZUNsaWZmVG9tbENvbmZpZ3VyYXRpb24oKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDb25maWd1cmVzIHRoZSBgLmdpdGF0dHJpYnV0ZXNgIGZpbGUgdG8gdHJlYXQgR2l0SHViIGNvbXBvbmVudCByZWxhdGVkIGZpbGVzIGFzIGdlbmVyYXRlZCBjb2RlLCBvcHRpbWl6aW5nIGRpZmZzLlxuICAgKi9cbiAgcHVibGljIHVwZGF0ZUdpdEF0dHJpYnV0ZXMoKTogdm9pZCB7XG4gICAgLy8gUHVsbCByZXF1ZXN0IHRlbXBsYXRlIGlzIGFkZGVkIGF1dG9tYXRpY2FsbHlcbiAgICB0aGlzLnByb2plY3QuZ2l0YXR0cmlidXRlcy5hZGRBdHRyaWJ1dGVzKGAvJHt0aGlzLmJ1Z0lzc3VlRmlsZVBhdGh9YCwgJ2xpbmd1aXN0LWdlbmVyYXRlZCcpO1xuICAgIHRoaXMucHJvamVjdC5naXRhdHRyaWJ1dGVzLmFkZEF0dHJpYnV0ZXMoYC8ke3RoaXMuZmVhdHVyZUlzc3VlRmlsZVBhdGh9YCwgJ2xpbmd1aXN0LWdlbmVyYXRlZCcpO1xuICAgIHRoaXMucHJvamVjdC5naXRhdHRyaWJ1dGVzLmFkZEF0dHJpYnV0ZXMoYC8ke3RoaXMucXVlc3Rpb25Jc3N1ZUZpbGVQYXRofWAsICdsaW5ndWlzdC1nZW5lcmF0ZWQnKTtcbiAgICB0aGlzLnByb2plY3QuZ2l0YXR0cmlidXRlcy5hZGRBdHRyaWJ1dGVzKGAvJHt0aGlzLmNsaWZmVG9tbEZpbGVQYXRofWAsICdsaW5ndWlzdC1nZW5lcmF0ZWQnKTtcbiAgICAvLyBXb3JrZmxvd3MgdGVtcGxhdGVzIGFyZSBhZGRlZCBhdXRvbWF0aWNhbGx5XG4gIH1cblxuICAvKipcbiAgICogRXhlY3V0ZXMgc2V0dXAgZm9yIHRoZSBHaXRIdWIgY29tcG9uZW50LlxuICAgKi9cbiAgcHVibGljIHNldHVwKCk6IHZvaWQge1xuICAgIHRoaXMuYWRkKCk7XG4gICAgdGhpcy51cGRhdGVHaXRBdHRyaWJ1dGVzKCk7XG4gIH1cbn1cbiJdfQ==