"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.GitHubBase = void 0;
const JSII_RTTI_SYMBOL_1 = Symbol.for("jsii.rtti");
const projen_1 = require("projen");
const github_1 = require("projen/lib/github");
const workflows_model_1 = require("projen/lib/github/workflows-model");
const builder_1 = require("./builder");
/**
 * Base class for GitHub builder implementing all relevant configuration.
 * @abstract
 */
class GitHubBase extends builder_1.Builder {
    /**
     * Initializes the base GitHub builder.
     * @param project The project to configure GitHub builder for.
     */
    constructor(project) {
        super(project);
    }
    /**
     * File path to GitHub bug issue template.
     * @return File path to bug issue file.
     * @protected
     */
    get bugIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/bug.yml';
    }
    /**
     *File path to GitHub feature issue template.
     @return File path to feature issue file.
     @protected
     */
    get featureIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/feature.yml';
    }
    /**
     *File path to GitHub housekeeping issue template.
     @return File path to housekeeping issue file.
     @protected
     */
    get housekeepingIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/housekeeping.yml';
    }
    /**
     * File path to GitHub question issue template.
     * @return File path to question issue file.
     * @protected
     */
    get questionIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/question.yml';
    }
    /**
     * File path to the Cliff toml configuration.
     * This file is used by release workflow to create the Changelog.
     * @return File path to cliff toml file.
     * @protected
     */
    get cliffTomlFilePath() {
        return 'cliff.toml';
    }
    /**
     * Pull Request template for the GitHub configuration.
     * @return File path to pull request template file.
     * @protected
     */
    get pullRequestTemplate() {
        return [
            '## Reviewers Checklist',
            '',
            'for complete review list refer to ABS Loop - Review Aspects',
            '',
            '### Organizational Section',
            '',
            '- [ ] PR is assigned to the according feature/bug',
            '- [ ] Feature/bug is descriptive',
            '- [ ] Feature/bug is assigned to according labels',
            '- [ ] Feature/bug is assigned to a developer',
            '',
            '### Structure',
            '',
            '- [ ] Readability: Code is easy to understand, with meaningful names for variables, functions, and classes',
            '- [ ] Comments: Meaningful and helpful comments. Code is documented without being over-commented',
            '- [ ] DRY, KISS and YAGNI: Code implements only necessary features; no over-engineering',
            '- [ ] No sensitive data (e.g., passwords, API keys) in the code',
            '- [ ] No major updates for used packages',
            '',
            '### Testing',
            '',
            '- [ ] Code is locally tested by developer (if applicable)',
            '- [ ] Automated tests pass successfully',
            '<!-- Generated by projen. To modify, edit .projenrc.ts and run "npx projen".-->',
        ];
    }
    /**
     * Issue template for the GitHub Bug configuration.
     * @return Template for the bug issue template file.
     * @protected
     */
    get bugIssueTemplate() {
        return [
            'name: 🐞 Bug',
            'description: File a bug/issue',
            'title: "[BUG] <title>"',
            'labels: ["type: bug"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Current behavior',
            "      description: A description of what you're experiencing.",
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Expected behavior',
            '      description: A description of what you expected to happen.',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Issue template for the GitHub feature configuration.
     * @return Template for the feature issue template file.
     * @protected
     */
    get featureIssueTemplate() {
        return [
            'name: 💡 Feature',
            'description: Request for a new feature',
            'title: "[FEATURE] <title>"',
            'labels: ["type: feature"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Description',
            '      description: A description of the feature.',
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Task List',
            '      description: Describe the steps to fulfill the feature.',
            '      value: |',
            '        - [ ] My First Task',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Issue template for the GitHub housekeeping configuration.
     * @return Template for the housekeeping issue template file.
     * @protected
     */
    get housekeepingIssueTemplate() {
        return [
            'name: 💡 Housekeeping',
            'description: Maintenance or refactoring task',
            'title: "[HOUSEKEEPING] <title>"',
            'labels: ["type: housekeeping"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Description',
            '      description: A description of the housekeeping task.',
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Task List',
            '      description: Describe the steps to fulfill the housekeeping task.',
            '      value: |',
            '        - [ ] My First Task',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Template for the GitHub Question Issue configuration.
     * @return Template for the question issue template file.
     * @protected
     */
    get questionIssueTemplate() {
        return [
            'name: ❓ Question',
            'description: Ask a question',
            'title: "[QUESTION] <title>"',
            'labels: ["type: question"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Question',
            '      description: What would you like to know? If you encounter unusual behavior or identified a missing feature, consider opening a bug report instead.',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Cliff toml configuration for the GitHub configuration.
     * This file is used by release workflow to create the Changelog.
     * @return Template for the cliff toml file.
     * @protected
     */
    get cliffTomlConfiguration() {
        return [
            '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
            '',
            '[changelog]',
            '# changelog header',
            'header = """',
            '# Changelog\n',
            'All notable changes to this project will be documented in this file.\n',
            '"""',
            '# template for the changelog body',
            '# https://keats.github.io/tera/docs/#introduction',
            'body = """',
            '{% if version %}\\',
            '    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}',
            '{% else %}\\',
            '    ## [unreleased]',
            '{% endif %}\\',
            '{% for group, commits in commits | group_by(attribute="group") %}',
            '    ### {{ group | striptags | trim | upper_first }}',
            '    {% for commit in commits %}',
            '        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\\',
            '            {% if commit.breaking %}[**breaking**] {% endif %}\\',
            '            {{ commit.message | upper_first }}\\',
            '    {% endfor %}',
            '{% endfor %}\\',
            '"""',
            '# template for the changelog footer',
            'footer = """',
            '<!-- generated by git-cliff -->',
            '"""',
            '# remove the leading and trailing s',
            'trim = true',
            '# postprocessors',
            'postprocessors = [',
            '  # { pattern = "<REPO>", replace = "https://github.com/orhun/git-cliff" }, # replace repository URL',
            ']',
            '',
            '[git]',
            '# parse the commits based on https://www.conventionalcommits.org',
            'conventional_commits = true',
            '# filter out the commits that are not conventional',
            'filter_unconventional = true',
            '# process each line of a commit as an individual commit',
            'split_commits = false',
            '# regex for preprocessing the commit messages',
            'commit_preprocessors = [',
            '  # Replace issue numbers',
            '  #{ pattern = "\\((\\w+\\s)?#([0-9]+)\\)", replace = "([#${2}](<REPO>/issues/${2}))"},',
            '  # Check spelling of the commit with https://github.com/crate-ci/typos',
            '  # If the spelling is incorrect, it will be automatically fixed.',
            '  #{ pattern = ".*", replace_command = "typos --write-changes -" },',
            ']',
            '# regex for parsing and grouping commits',
            'commit_parsers = [',
            '  { message = "^feat", group = "<!-- 0 -->🚀 Features" },',
            '  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },',
            '  { message = "^doc", group = "<!-- 3 -->📚 Documentation" },',
            '  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },',
            '  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },',
            '  { message = "^style", group = "<!-- 5 -->🎨 Styling" },',
            '  { message = "^test", group = "<!-- 6 -->🧪 Testing" },',
            '  { message = "^chore\\(release\\): prepare for", skip = true },',
            '  { message = "^chore\\(deps.*\\)", skip = true },',
            '  { message = "^chore\\(pr\\)", skip = true },',
            '  { message = "^chore\\(pull\\)", skip = true },',
            '  { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },',
            '  { body = ".*security", group = "<!-- 8 -->🛡️ Security" },',
            '  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },',
            ']',
            '# protect breaking changes from being skipped due to matching a skipping commit_parser',
            'protect_breaking_commits = false',
            '# filter out the commits that are not matched by commit parsers',
            'filter_commits = false',
            '# regex for matching git tags',
            '# tag_pattern = "v[0-9].*"',
            '# regex for skipping tags',
            '# skip_tags = ""',
            '# regex for ignoring tags',
            '# ignore_tags = ""',
            '# sort the tags topologically',
            'topo_order = false',
            '# sort the commits inside sections by oldest/newest order',
            'sort_commits = "oldest"',
            '# limit the number of commits included in the changelog.',
            '# limit_commits = 42',
        ];
    }
    /**
     * Workflow release template for the GitHub configuration.
     * @return Options for release workflow
     * @protected
     */
    get releaseWorkflowOptions() {
        return {
            on: {
                pullRequest: {
                    branches: ['main'],
                    types: ['closed'],
                },
            },
            job: {
                runsOn: ['ubuntu-latest'],
                permissions: {
                    contents: workflows_model_1.JobPermission.WRITE,
                    pullRequests: workflows_model_1.JobPermission.WRITE,
                },
                steps: [
                    {
                        name: 'Create release',
                        uses: 'dxfrontier/gh-action-release@main',
                        with: {
                            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
                            BRANCH: 'main',
                        },
                    },
                ],
            },
        };
    }
    /**
     * Workflow stale template options for the GitHub configuration.
     * @return Options for stale workflow
     * @protected
     */
    get staleWorkflowOptions() {
        return {
            on: {
                schedule: [
                    {
                        cron: '36 18 * * *',
                    },
                ],
            },
            job: {
                runsOn: ['ubuntu-latest'],
                permissions: {
                    issues: workflows_model_1.JobPermission.WRITE,
                    pullRequests: workflows_model_1.JobPermission.WRITE,
                },
                steps: [
                    {
                        uses: 'actions/stale@v5',
                        with: {
                            'repo-token': '${{ secrets.GITHUB_TOKEN }}',
                            'days-before-issue-stale': 30,
                            'stale-issue-message': 'This issue has not been updated in a while. If it is still relevant, please comment on it to keep it open. The issue will be closed soon if it remains inactive.',
                            'close-issue-message': 'This issue has been closed automatically due to inactivity.',
                            'stale-pr-message': 'This PR has not been updated in a while. If it is still relevant, please comment on it to keep it open. The PR will be closed soon if it remains inactive.',
                            'close-pr-message': 'This PR has been closed automatically due to inactivity.',
                            'stale-issue-label': 'status: stale',
                            'stale-pr-label': 'status: stale',
                            'exempt-issue-labels': 'type: feature request',
                            'exempt-pr-labels': 'type: feature request',
                            'exempt-all-milestones': true,
                        },
                    },
                ],
            },
        };
    }
    /**
     * Creates the template file for a GitHub pull request.
     * @protected
     */
    createPullRequest() {
        new github_1.PullRequestTemplate(this.project.github, {
            lines: this.pullRequestTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub bug issue.
     * @protected
     */
    createBugIssue() {
        new projen_1.TextFile(this.project, this.bugIssueFilePath, {
            lines: this.bugIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub feature issue.
     * @protected
     */
    createFeatureIssue() {
        new projen_1.TextFile(this.project, this.featureIssueFilePath, {
            lines: this.featureIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub housekeeping issue.
     * @protected
     */
    createHousekeepingIssue() {
        new projen_1.TextFile(this.project, this.housekeepingIssueFilePath, {
            lines: this.housekeepingIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub question issue.
     * @protected
     */
    createQuestionIssue() {
        new projen_1.TextFile(this.project, this.questionIssueFilePath, {
            lines: this.questionIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub release workflow.
     * @protected
     */
    createReleaseWorkflow() {
        const workflow = this.project.github?.addWorkflow('Release');
        workflow?.on(this.releaseWorkflowOptions.on);
        workflow?.addJob('release', this.releaseWorkflowOptions.job);
    }
    /**
     * Creates the template file for a GitHub stale workflow.
     * @protected
     */
    createStaleWorkflow() {
        const workflow = this.project.github?.addWorkflow('Stale');
        workflow?.on(this.staleWorkflowOptions.on);
        workflow?.addJob('stale', this.staleWorkflowOptions.job);
    }
    /**
     * Creates the configuration file for the cliff toml CHANGELOG creation in release workflow.
     * @protected
     */
    createCliffTomlConfiguration() {
        new projen_1.TextFile(this.project, this.cliffTomlFilePath, {
            lines: this.cliffTomlConfiguration,
        });
    }
    /**
     * @override
     */
    addTemplates() {
        this.createPullRequest();
        this.createBugIssue();
        this.createFeatureIssue();
        this.createHousekeepingIssue();
        this.createQuestionIssue();
        this.createReleaseWorkflow();
        this.createStaleWorkflow();
        this.createCliffTomlConfiguration();
    }
}
exports.GitHubBase = GitHubBase;
_a = JSII_RTTI_SYMBOL_1;
GitHubBase[_a] = { fqn: "@dxfrontier/projen-template-projects.GitHubBase", version: "0.0.0" };
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZ2l0aHViLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vc3JjL2Jhc2UvZ2l0aHViLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7O0FBQUEsbUNBQWtDO0FBQ2xDLDhDQUF3RTtBQUN4RSx1RUFBa0U7QUFDbEUsdUNBQW9DO0FBSXBDOzs7R0FHRztBQUNILE1BQXNCLFVBQVcsU0FBUSxpQkFBTztJQUM5Qzs7O09BR0c7SUFDSCxZQUFZLE9BQThCO1FBQ3hDLEtBQUssQ0FBQyxPQUFPLENBQUMsQ0FBQztJQUNqQixDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMsZ0JBQWdCO1FBQzVCLE9BQU8sZ0NBQWdDLENBQUM7SUFDMUMsQ0FBQztJQUVEOzs7O09BSUc7SUFDSCxJQUFjLG9CQUFvQjtRQUNoQyxPQUFPLG9DQUFvQyxDQUFDO0lBQzlDLENBQUM7SUFFRDs7OztPQUlHO0lBQ0gsSUFBYyx5QkFBeUI7UUFDckMsT0FBTyx5Q0FBeUMsQ0FBQztJQUNuRCxDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMscUJBQXFCO1FBQ2pDLE9BQU8scUNBQXFDLENBQUM7SUFDL0MsQ0FBQztJQUVEOzs7OztPQUtHO0lBQ0gsSUFBYyxpQkFBaUI7UUFDN0IsT0FBTyxZQUFZLENBQUM7SUFDdEIsQ0FBQztJQUVEOzs7O09BSUc7SUFDSCxJQUFjLG1CQUFtQjtRQUMvQixPQUFPO1lBQ0wsd0JBQXdCO1lBQ3hCLEVBQUU7WUFDRiw2REFBNkQ7WUFDN0QsRUFBRTtZQUNGLDRCQUE0QjtZQUM1QixFQUFFO1lBQ0YsbURBQW1EO1lBQ25ELGtDQUFrQztZQUNsQyxtREFBbUQ7WUFDbkQsOENBQThDO1lBQzlDLEVBQUU7WUFDRixlQUFlO1lBQ2YsRUFBRTtZQUNGLDRHQUE0RztZQUM1RyxrR0FBa0c7WUFDbEcseUZBQXlGO1lBQ3pGLGlFQUFpRTtZQUNqRSwwQ0FBMEM7WUFDMUMsRUFBRTtZQUNGLGFBQWE7WUFDYixFQUFFO1lBQ0YsMkRBQTJEO1lBQzNELHlDQUF5QztZQUN6QyxpRkFBaUY7U0FDbEYsQ0FBQztJQUNKLENBQUM7SUFFRDs7OztPQUlHO0lBQ0gsSUFBYyxnQkFBZ0I7UUFDNUIsT0FBTztZQUNMLGNBQWM7WUFDZCwrQkFBK0I7WUFDL0Isd0JBQXdCO1lBQ3hCLHVCQUF1QjtZQUN2QixPQUFPO1lBQ1Asb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQiwrQkFBK0I7WUFDL0IsK0RBQStEO1lBQy9ELGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsRUFBRTtZQUNGLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsZ0NBQWdDO1lBQ2hDLGtFQUFrRTtZQUNsRSxrQkFBa0I7WUFDbEIsc0JBQXNCO1lBQ3RCLDJFQUEyRTtTQUM1RSxDQUFDO0lBQ0osQ0FBQztJQUVEOzs7O09BSUc7SUFDSCxJQUFjLG9CQUFvQjtRQUNoQyxPQUFPO1lBQ0wsa0JBQWtCO1lBQ2xCLHdDQUF3QztZQUN4Qyw0QkFBNEI7WUFDNUIsMkJBQTJCO1lBQzNCLE9BQU87WUFDUCxvQkFBb0I7WUFDcEIsaUJBQWlCO1lBQ2pCLDBCQUEwQjtZQUMxQixrREFBa0Q7WUFDbEQsa0JBQWtCO1lBQ2xCLHNCQUFzQjtZQUN0QixFQUFFO1lBQ0Ysb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQix3QkFBd0I7WUFDeEIsK0RBQStEO1lBQy9ELGdCQUFnQjtZQUNoQiw2QkFBNkI7WUFDN0Isa0JBQWtCO1lBQ2xCLHNCQUFzQjtZQUN0QiwyRUFBMkU7U0FDNUUsQ0FBQztJQUNKLENBQUM7SUFFRDs7OztPQUlHO0lBQ0gsSUFBYyx5QkFBeUI7UUFDckMsT0FBTztZQUNMLHVCQUF1QjtZQUN2Qiw4Q0FBOEM7WUFDOUMsaUNBQWlDO1lBQ2pDLGdDQUFnQztZQUNoQyxPQUFPO1lBQ1Asb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQiwwQkFBMEI7WUFDMUIsNERBQTREO1lBQzVELGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsRUFBRTtZQUNGLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsd0JBQXdCO1lBQ3hCLHlFQUF5RTtZQUN6RSxnQkFBZ0I7WUFDaEIsNkJBQTZCO1lBQzdCLGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsMkVBQTJFO1NBQzVFLENBQUM7SUFDSixDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMscUJBQXFCO1FBQ2pDLE9BQU87WUFDTCxrQkFBa0I7WUFDbEIsNkJBQTZCO1lBQzdCLDZCQUE2QjtZQUM3Qiw0QkFBNEI7WUFDNUIsT0FBTztZQUNQLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsdUJBQXVCO1lBQ3ZCLDJKQUEySjtZQUMzSixrQkFBa0I7WUFDbEIsc0JBQXNCO1lBQ3RCLDJFQUEyRTtTQUM1RSxDQUFDO0lBQ0osQ0FBQztJQUVEOzs7OztPQUtHO0lBQ0gsSUFBYyxzQkFBc0I7UUFDbEMsT0FBTztZQUNMLDhFQUE4RTtZQUM5RSxFQUFFO1lBQ0YsYUFBYTtZQUNiLG9CQUFvQjtZQUNwQixjQUFjO1lBQ2QsZUFBZTtZQUNmLHdFQUF3RTtZQUN4RSxLQUFLO1lBQ0wsbUNBQW1DO1lBQ25DLG1EQUFtRDtZQUNuRCxZQUFZO1lBQ1osb0JBQW9CO1lBQ3BCLGtHQUFrRztZQUNsRyxjQUFjO1lBQ2QscUJBQXFCO1lBQ3JCLGVBQWU7WUFDZixtRUFBbUU7WUFDbkUsc0RBQXNEO1lBQ3RELGlDQUFpQztZQUNqQyxxRUFBcUU7WUFDckUsa0VBQWtFO1lBQ2xFLGtEQUFrRDtZQUNsRCxrQkFBa0I7WUFDbEIsZ0JBQWdCO1lBQ2hCLEtBQUs7WUFDTCxxQ0FBcUM7WUFDckMsY0FBYztZQUNkLGlDQUFpQztZQUNqQyxLQUFLO1lBQ0wscUNBQXFDO1lBQ3JDLGFBQWE7WUFDYixrQkFBa0I7WUFDbEIsb0JBQW9CO1lBQ3BCLHNHQUFzRztZQUN0RyxHQUFHO1lBQ0gsRUFBRTtZQUNGLE9BQU87WUFDUCxrRUFBa0U7WUFDbEUsNkJBQTZCO1lBQzdCLG9EQUFvRDtZQUNwRCw4QkFBOEI7WUFDOUIseURBQXlEO1lBQ3pELHVCQUF1QjtZQUN2QiwrQ0FBK0M7WUFDL0MsMEJBQTBCO1lBQzFCLDJCQUEyQjtZQUMzQix5RkFBeUY7WUFDekYseUVBQXlFO1lBQ3pFLG1FQUFtRTtZQUNuRSxxRUFBcUU7WUFDckUsR0FBRztZQUNILDBDQUEwQztZQUMxQyxvQkFBb0I7WUFDcEIsMkRBQTJEO1lBQzNELDJEQUEyRDtZQUMzRCwrREFBK0Q7WUFDL0QsNkRBQTZEO1lBQzdELCtEQUErRDtZQUMvRCwyREFBMkQ7WUFDM0QsMERBQTBEO1lBQzFELGtFQUFrRTtZQUNsRSxvREFBb0Q7WUFDcEQsZ0RBQWdEO1lBQ2hELGtEQUFrRDtZQUNsRCwyRUFBMkU7WUFDM0UsOERBQThEO1lBQzlELDJEQUEyRDtZQUMzRCxHQUFHO1lBQ0gsd0ZBQXdGO1lBQ3hGLGtDQUFrQztZQUNsQyxpRUFBaUU7WUFDakUsd0JBQXdCO1lBQ3hCLCtCQUErQjtZQUMvQiw0QkFBNEI7WUFDNUIsMkJBQTJCO1lBQzNCLGtCQUFrQjtZQUNsQiwyQkFBMkI7WUFDM0Isb0JBQW9CO1lBQ3BCLCtCQUErQjtZQUMvQixvQkFBb0I7WUFDcEIsMkRBQTJEO1lBQzNELHlCQUF5QjtZQUN6QiwwREFBMEQ7WUFDMUQsc0JBQXNCO1NBQ3ZCLENBQUM7SUFDSixDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMsc0JBQXNCO1FBQ2xDLE9BQU87WUFDTCxFQUFFLEVBQUU7Z0JBQ0YsV0FBVyxFQUFFO29CQUNYLFFBQVEsRUFBRSxDQUFDLE1BQU0sQ0FBQztvQkFDbEIsS0FBSyxFQUFFLENBQUMsUUFBUSxDQUFDO2lCQUNsQjthQUNGO1lBQ0QsR0FBRyxFQUFFO2dCQUNILE1BQU0sRUFBRSxDQUFDLGVBQWUsQ0FBQztnQkFDekIsV0FBVyxFQUFFO29CQUNYLFFBQVEsRUFBRSwrQkFBYSxDQUFDLEtBQUs7b0JBQzdCLFlBQVksRUFBRSwrQkFBYSxDQUFDLEtBQUs7aUJBQ2xDO2dCQUNELEtBQUssRUFBRTtvQkFDTDt3QkFDRSxJQUFJLEVBQUUsZ0JBQWdCO3dCQUN0QixJQUFJLEVBQUUsbUNBQW1DO3dCQUN6QyxJQUFJLEVBQUU7NEJBQ0osWUFBWSxFQUFFLDZCQUE2Qjs0QkFDM0MsTUFBTSxFQUFFLE1BQU07eUJBQ2Y7cUJBQ0Y7aUJBQ0Y7YUFDRjtTQUNGLENBQUM7SUFDSixDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMsb0JBQW9CO1FBQ2hDLE9BQU87WUFDTCxFQUFFLEVBQUU7Z0JBQ0YsUUFBUSxFQUFFO29CQUNSO3dCQUNFLElBQUksRUFBRSxhQUFhO3FCQUNwQjtpQkFDRjthQUNGO1lBQ0QsR0FBRyxFQUFFO2dCQUNILE1BQU0sRUFBRSxDQUFDLGVBQWUsQ0FBQztnQkFDekIsV0FBVyxFQUFFO29CQUNYLE1BQU0sRUFBRSwrQkFBYSxDQUFDLEtBQUs7b0JBQzNCLFlBQVksRUFBRSwrQkFBYSxDQUFDLEtBQUs7aUJBQ2xDO2dCQUNELEtBQUssRUFBRTtvQkFDTDt3QkFDRSxJQUFJLEVBQUUsa0JBQWtCO3dCQUN4QixJQUFJLEVBQUU7NEJBQ0osWUFBWSxFQUFFLDZCQUE2Qjs0QkFDM0MseUJBQXlCLEVBQUUsRUFBRTs0QkFDN0IscUJBQXFCLEVBQ25CLGtLQUFrSzs0QkFDcEsscUJBQXFCLEVBQUUsNkRBQTZEOzRCQUNwRixrQkFBa0IsRUFDaEIsNEpBQTRKOzRCQUM5SixrQkFBa0IsRUFBRSwwREFBMEQ7NEJBQzlFLG1CQUFtQixFQUFFLGVBQWU7NEJBQ3BDLGdCQUFnQixFQUFFLGVBQWU7NEJBQ2pDLHFCQUFxQixFQUFFLHVCQUF1Qjs0QkFDOUMsa0JBQWtCLEVBQUUsdUJBQXVCOzRCQUMzQyx1QkFBdUIsRUFBRSxJQUFJO3lCQUM5QjtxQkFDRjtpQkFDRjthQUNGO1NBQ0YsQ0FBQztJQUNKLENBQUM7SUFFRDs7O09BR0c7SUFDTyxpQkFBaUI7UUFDekIsSUFBSSw0QkFBbUIsQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUFDLE1BQU8sRUFBRTtZQUM1QyxLQUFLLEVBQUUsSUFBSSxDQUFDLG1CQUFtQjtTQUNoQyxDQUFDLENBQUM7SUFDTCxDQUFDO0lBRUQ7OztPQUdHO0lBQ08sY0FBYztRQUN0QixJQUFJLGlCQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxJQUFJLENBQUMsZ0JBQWdCLEVBQUU7WUFDaEQsS0FBSyxFQUFFLElBQUksQ0FBQyxnQkFBZ0I7U0FDN0IsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOzs7T0FHRztJQUNPLGtCQUFrQjtRQUMxQixJQUFJLGlCQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxJQUFJLENBQUMsb0JBQW9CLEVBQUU7WUFDcEQsS0FBSyxFQUFFLElBQUksQ0FBQyxvQkFBb0I7U0FDakMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOzs7T0FHRztJQUNPLHVCQUF1QjtRQUMvQixJQUFJLGlCQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxJQUFJLENBQUMseUJBQXlCLEVBQUU7WUFDekQsS0FBSyxFQUFFLElBQUksQ0FBQyx5QkFBeUI7U0FDdEMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOzs7T0FHRztJQUNPLG1CQUFtQjtRQUMzQixJQUFJLGlCQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxJQUFJLENBQUMscUJBQXFCLEVBQUU7WUFDckQsS0FBSyxFQUFFLElBQUksQ0FBQyxxQkFBcUI7U0FDbEMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOzs7T0FHRztJQUNPLHFCQUFxQjtRQUM3QixNQUFNLFFBQVEsR0FBK0IsSUFBSSxDQUFDLE9BQU8sQ0FBQyxNQUFNLEVBQUUsV0FBVyxDQUFDLFNBQVMsQ0FBQyxDQUFDO1FBQ3pGLFFBQVEsRUFBRSxFQUFFLENBQUMsSUFBSSxDQUFDLHNCQUFzQixDQUFDLEVBQUUsQ0FBQyxDQUFDO1FBQzdDLFFBQVEsRUFBRSxNQUFNLENBQUMsU0FBUyxFQUFFLElBQUksQ0FBQyxzQkFBc0IsQ0FBQyxHQUFHLENBQUMsQ0FBQztJQUMvRCxDQUFDO0lBRUQ7OztPQUdHO0lBQ08sbUJBQW1CO1FBQzNCLE1BQU0sUUFBUSxHQUErQixJQUFJLENBQUMsT0FBTyxDQUFDLE1BQU0sRUFBRSxXQUFXLENBQUMsT0FBTyxDQUFDLENBQUM7UUFDdkYsUUFBUSxFQUFFLEVBQUUsQ0FBQyxJQUFJLENBQUMsb0JBQW9CLENBQUMsRUFBRSxDQUFDLENBQUM7UUFDM0MsUUFBUSxFQUFFLE1BQU0sQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLG9CQUFvQixDQUFDLEdBQUcsQ0FBQyxDQUFDO0lBQzNELENBQUM7SUFFRDs7O09BR0c7SUFDTyw0QkFBNEI7UUFDcEMsSUFBSSxpQkFBUSxDQUFDLElBQUksQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLGlCQUFpQixFQUFFO1lBQ2pELEtBQUssRUFBRSxJQUFJLENBQUMsc0JBQXNCO1NBQ25DLENBQUMsQ0FBQztJQUNMLENBQUM7SUFFRDs7T0FFRztJQUNPLFlBQVk7UUFDcEIsSUFBSSxDQUFDLGlCQUFpQixFQUFFLENBQUM7UUFDekIsSUFBSSxDQUFDLGNBQWMsRUFBRSxDQUFDO1FBQ3RCLElBQUksQ0FBQyxrQkFBa0IsRUFBRSxDQUFDO1FBQzFCLElBQUksQ0FBQyx1QkFBdUIsRUFBRSxDQUFDO1FBQy9CLElBQUksQ0FBQyxtQkFBbUIsRUFBRSxDQUFDO1FBRTNCLElBQUksQ0FBQyxxQkFBcUIsRUFBRSxDQUFDO1FBQzdCLElBQUksQ0FBQyxtQkFBbUIsRUFBRSxDQUFDO1FBQzNCLElBQUksQ0FBQyw0QkFBNEIsRUFBRSxDQUFDO0lBQ3RDLENBQUM7O0FBbmRILGdDQW9kQyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IFRleHRGaWxlIH0gZnJvbSAncHJvamVuJztcbmltcG9ydCB7IEdpdGh1YldvcmtmbG93LCBQdWxsUmVxdWVzdFRlbXBsYXRlIH0gZnJvbSAncHJvamVuL2xpYi9naXRodWInO1xuaW1wb3J0IHsgSm9iUGVybWlzc2lvbiB9IGZyb20gJ3Byb2plbi9saWIvZ2l0aHViL3dvcmtmbG93cy1tb2RlbCc7XG5pbXBvcnQgeyBCdWlsZGVyIH0gZnJvbSAnLi9idWlsZGVyJztcbmltcG9ydCB7IFdvcmtmbG93T3B0aW9ucyB9IGZyb20gJy4uL3R5cGVzJztcbmltcG9ydCB7IFR5cGVTY3JpcHRQcm9qZWN0QmFzZSB9IGZyb20gJy4vcHJvamVjdCc7XG5cbi8qKlxuICogQmFzZSBjbGFzcyBmb3IgR2l0SHViIGJ1aWxkZXIgaW1wbGVtZW50aW5nIGFsbCByZWxldmFudCBjb25maWd1cmF0aW9uLlxuICogQGFic3RyYWN0XG4gKi9cbmV4cG9ydCBhYnN0cmFjdCBjbGFzcyBHaXRIdWJCYXNlIGV4dGVuZHMgQnVpbGRlciB7XG4gIC8qKlxuICAgKiBJbml0aWFsaXplcyB0aGUgYmFzZSBHaXRIdWIgYnVpbGRlci5cbiAgICogQHBhcmFtIHByb2plY3QgVGhlIHByb2plY3QgdG8gY29uZmlndXJlIEdpdEh1YiBidWlsZGVyIGZvci5cbiAgICovXG4gIGNvbnN0cnVjdG9yKHByb2plY3Q6IFR5cGVTY3JpcHRQcm9qZWN0QmFzZSkge1xuICAgIHN1cGVyKHByb2plY3QpO1xuICB9XG5cbiAgLyoqXG4gICAqIEZpbGUgcGF0aCB0byBHaXRIdWIgYnVnIGlzc3VlIHRlbXBsYXRlLlxuICAgKiBAcmV0dXJuIEZpbGUgcGF0aCB0byBidWcgaXNzdWUgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBidWdJc3N1ZUZpbGVQYXRoKCk6IHN0cmluZyB7XG4gICAgcmV0dXJuICcuZ2l0aHViL0lTU1VFX1RFTVBMQVRFL2J1Zy55bWwnO1xuICB9XG5cbiAgLyoqXG4gICAqRmlsZSBwYXRoIHRvIEdpdEh1YiBmZWF0dXJlIGlzc3VlIHRlbXBsYXRlLlxuICAgQHJldHVybiBGaWxlIHBhdGggdG8gZmVhdHVyZSBpc3N1ZSBmaWxlLlxuICAgQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBmZWF0dXJlSXNzdWVGaWxlUGF0aCgpOiBzdHJpbmcge1xuICAgIHJldHVybiAnLmdpdGh1Yi9JU1NVRV9URU1QTEFURS9mZWF0dXJlLnltbCc7XG4gIH1cblxuICAvKipcbiAgICpGaWxlIHBhdGggdG8gR2l0SHViIGhvdXNla2VlcGluZyBpc3N1ZSB0ZW1wbGF0ZS5cbiAgIEByZXR1cm4gRmlsZSBwYXRoIHRvIGhvdXNla2VlcGluZyBpc3N1ZSBmaWxlLlxuICAgQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBob3VzZWtlZXBpbmdJc3N1ZUZpbGVQYXRoKCk6IHN0cmluZyB7XG4gICAgcmV0dXJuICcuZ2l0aHViL0lTU1VFX1RFTVBMQVRFL2hvdXNla2VlcGluZy55bWwnO1xuICB9XG5cbiAgLyoqXG4gICAqIEZpbGUgcGF0aCB0byBHaXRIdWIgcXVlc3Rpb24gaXNzdWUgdGVtcGxhdGUuXG4gICAqIEByZXR1cm4gRmlsZSBwYXRoIHRvIHF1ZXN0aW9uIGlzc3VlIGZpbGUuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBnZXQgcXVlc3Rpb25Jc3N1ZUZpbGVQYXRoKCk6IHN0cmluZyB7XG4gICAgcmV0dXJuICcuZ2l0aHViL0lTU1VFX1RFTVBMQVRFL3F1ZXN0aW9uLnltbCc7XG4gIH1cblxuICAvKipcbiAgICogRmlsZSBwYXRoIHRvIHRoZSBDbGlmZiB0b21sIGNvbmZpZ3VyYXRpb24uXG4gICAqIFRoaXMgZmlsZSBpcyB1c2VkIGJ5IHJlbGVhc2Ugd29ya2Zsb3cgdG8gY3JlYXRlIHRoZSBDaGFuZ2Vsb2cuXG4gICAqIEByZXR1cm4gRmlsZSBwYXRoIHRvIGNsaWZmIHRvbWwgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBjbGlmZlRvbWxGaWxlUGF0aCgpOiBzdHJpbmcge1xuICAgIHJldHVybiAnY2xpZmYudG9tbCc7XG4gIH1cblxuICAvKipcbiAgICogUHVsbCBSZXF1ZXN0IHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIGNvbmZpZ3VyYXRpb24uXG4gICAqIEByZXR1cm4gRmlsZSBwYXRoIHRvIHB1bGwgcmVxdWVzdCB0ZW1wbGF0ZSBmaWxlLlxuICAgKiBAcHJvdGVjdGVkXG4gICAqL1xuICBwcm90ZWN0ZWQgZ2V0IHB1bGxSZXF1ZXN0VGVtcGxhdGUoKTogc3RyaW5nW10ge1xuICAgIHJldHVybiBbXG4gICAgICAnIyMgUmV2aWV3ZXJzIENoZWNrbGlzdCcsXG4gICAgICAnJyxcbiAgICAgICdmb3IgY29tcGxldGUgcmV2aWV3IGxpc3QgcmVmZXIgdG8gQUJTIExvb3AgLSBSZXZpZXcgQXNwZWN0cycsXG4gICAgICAnJyxcbiAgICAgICcjIyMgT3JnYW5pemF0aW9uYWwgU2VjdGlvbicsXG4gICAgICAnJyxcbiAgICAgICctIFsgXSBQUiBpcyBhc3NpZ25lZCB0byB0aGUgYWNjb3JkaW5nIGZlYXR1cmUvYnVnJyxcbiAgICAgICctIFsgXSBGZWF0dXJlL2J1ZyBpcyBkZXNjcmlwdGl2ZScsXG4gICAgICAnLSBbIF0gRmVhdHVyZS9idWcgaXMgYXNzaWduZWQgdG8gYWNjb3JkaW5nIGxhYmVscycsXG4gICAgICAnLSBbIF0gRmVhdHVyZS9idWcgaXMgYXNzaWduZWQgdG8gYSBkZXZlbG9wZXInLFxuICAgICAgJycsXG4gICAgICAnIyMjIFN0cnVjdHVyZScsXG4gICAgICAnJyxcbiAgICAgICctIFsgXSBSZWFkYWJpbGl0eTogQ29kZSBpcyBlYXN5IHRvIHVuZGVyc3RhbmQsIHdpdGggbWVhbmluZ2Z1bCBuYW1lcyBmb3IgdmFyaWFibGVzLCBmdW5jdGlvbnMsIGFuZCBjbGFzc2VzJyxcbiAgICAgICctIFsgXSBDb21tZW50czogTWVhbmluZ2Z1bCBhbmQgaGVscGZ1bCBjb21tZW50cy4gQ29kZSBpcyBkb2N1bWVudGVkIHdpdGhvdXQgYmVpbmcgb3Zlci1jb21tZW50ZWQnLFxuICAgICAgJy0gWyBdIERSWSwgS0lTUyBhbmQgWUFHTkk6IENvZGUgaW1wbGVtZW50cyBvbmx5IG5lY2Vzc2FyeSBmZWF0dXJlczsgbm8gb3Zlci1lbmdpbmVlcmluZycsXG4gICAgICAnLSBbIF0gTm8gc2Vuc2l0aXZlIGRhdGEgKGUuZy4sIHBhc3N3b3JkcywgQVBJIGtleXMpIGluIHRoZSBjb2RlJyxcbiAgICAgICctIFsgXSBObyBtYWpvciB1cGRhdGVzIGZvciB1c2VkIHBhY2thZ2VzJyxcbiAgICAgICcnLFxuICAgICAgJyMjIyBUZXN0aW5nJyxcbiAgICAgICcnLFxuICAgICAgJy0gWyBdIENvZGUgaXMgbG9jYWxseSB0ZXN0ZWQgYnkgZGV2ZWxvcGVyIChpZiBhcHBsaWNhYmxlKScsXG4gICAgICAnLSBbIF0gQXV0b21hdGVkIHRlc3RzIHBhc3Mgc3VjY2Vzc2Z1bGx5JyxcbiAgICAgICc8IS0tIEdlbmVyYXRlZCBieSBwcm9qZW4uIFRvIG1vZGlmeSwgZWRpdCAucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4tLT4nLFxuICAgIF07XG4gIH1cblxuICAvKipcbiAgICogSXNzdWUgdGVtcGxhdGUgZm9yIHRoZSBHaXRIdWIgQnVnIGNvbmZpZ3VyYXRpb24uXG4gICAqIEByZXR1cm4gVGVtcGxhdGUgZm9yIHRoZSBidWcgaXNzdWUgdGVtcGxhdGUgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBidWdJc3N1ZVRlbXBsYXRlKCk6IHN0cmluZ1tdIHtcbiAgICByZXR1cm4gW1xuICAgICAgJ25hbWU6IPCfkJ4gQnVnJyxcbiAgICAgICdkZXNjcmlwdGlvbjogRmlsZSBhIGJ1Zy9pc3N1ZScsXG4gICAgICAndGl0bGU6IFwiW0JVR10gPHRpdGxlPlwiJyxcbiAgICAgICdsYWJlbHM6IFtcInR5cGU6IGJ1Z1wiXScsXG4gICAgICAnYm9keTonLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogQ3VycmVudCBiZWhhdmlvcicsXG4gICAgICBcIiAgICAgIGRlc2NyaXB0aW9uOiBBIGRlc2NyaXB0aW9uIG9mIHdoYXQgeW91J3JlIGV4cGVyaWVuY2luZy5cIixcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnJyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IEV4cGVjdGVkIGJlaGF2aW9yJyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogQSBkZXNjcmlwdGlvbiBvZiB3aGF0IHlvdSBleHBlY3RlZCB0byBoYXBwZW4uJyxcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnIyBHZW5lcmF0ZWQgYnkgcHJvamVuLiBUbyBtb2RpZnksIGVkaXQgLnByb2plbnJjLnRzIGFuZCBydW4gXCJucHggcHJvamVuXCIuJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIElzc3VlIHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIGZlYXR1cmUgY29uZmlndXJhdGlvbi5cbiAgICogQHJldHVybiBUZW1wbGF0ZSBmb3IgdGhlIGZlYXR1cmUgaXNzdWUgdGVtcGxhdGUgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBmZWF0dXJlSXNzdWVUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICduYW1lOiDwn5KhIEZlYXR1cmUnLFxuICAgICAgJ2Rlc2NyaXB0aW9uOiBSZXF1ZXN0IGZvciBhIG5ldyBmZWF0dXJlJyxcbiAgICAgICd0aXRsZTogXCJbRkVBVFVSRV0gPHRpdGxlPlwiJyxcbiAgICAgICdsYWJlbHM6IFtcInR5cGU6IGZlYXR1cmVcIl0nLFxuICAgICAgJ2JvZHk6JyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IERlc2NyaXB0aW9uJyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogQSBkZXNjcmlwdGlvbiBvZiB0aGUgZmVhdHVyZS4nLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcnLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogVGFzayBMaXN0JyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogRGVzY3JpYmUgdGhlIHN0ZXBzIHRvIGZ1bGZpbGwgdGhlIGZlYXR1cmUuJyxcbiAgICAgICcgICAgICB2YWx1ZTogfCcsXG4gICAgICAnICAgICAgICAtIFsgXSBNeSBGaXJzdCBUYXNrJyxcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnIyBHZW5lcmF0ZWQgYnkgcHJvamVuLiBUbyBtb2RpZnksIGVkaXQgLnByb2plbnJjLnRzIGFuZCBydW4gXCJucHggcHJvamVuXCIuJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIElzc3VlIHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIGhvdXNla2VlcGluZyBjb25maWd1cmF0aW9uLlxuICAgKiBAcmV0dXJuIFRlbXBsYXRlIGZvciB0aGUgaG91c2VrZWVwaW5nIGlzc3VlIHRlbXBsYXRlIGZpbGUuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBnZXQgaG91c2VrZWVwaW5nSXNzdWVUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICduYW1lOiDwn5KhIEhvdXNla2VlcGluZycsXG4gICAgICAnZGVzY3JpcHRpb246IE1haW50ZW5hbmNlIG9yIHJlZmFjdG9yaW5nIHRhc2snLFxuICAgICAgJ3RpdGxlOiBcIltIT1VTRUtFRVBJTkddIDx0aXRsZT5cIicsXG4gICAgICAnbGFiZWxzOiBbXCJ0eXBlOiBob3VzZWtlZXBpbmdcIl0nLFxuICAgICAgJ2JvZHk6JyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IERlc2NyaXB0aW9uJyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogQSBkZXNjcmlwdGlvbiBvZiB0aGUgaG91c2VrZWVwaW5nIHRhc2suJyxcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnJyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IFRhc2sgTGlzdCcsXG4gICAgICAnICAgICAgZGVzY3JpcHRpb246IERlc2NyaWJlIHRoZSBzdGVwcyB0byBmdWxmaWxsIHRoZSBob3VzZWtlZXBpbmcgdGFzay4nLFxuICAgICAgJyAgICAgIHZhbHVlOiB8JyxcbiAgICAgICcgICAgICAgIC0gWyBdIE15IEZpcnN0IFRhc2snLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcjIEdlbmVyYXRlZCBieSBwcm9qZW4uIFRvIG1vZGlmeSwgZWRpdCAucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4nLFxuICAgIF07XG4gIH1cblxuICAvKipcbiAgICogVGVtcGxhdGUgZm9yIHRoZSBHaXRIdWIgUXVlc3Rpb24gSXNzdWUgY29uZmlndXJhdGlvbi5cbiAgICogQHJldHVybiBUZW1wbGF0ZSBmb3IgdGhlIHF1ZXN0aW9uIGlzc3VlIHRlbXBsYXRlIGZpbGUuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBnZXQgcXVlc3Rpb25Jc3N1ZVRlbXBsYXRlKCk6IHN0cmluZ1tdIHtcbiAgICByZXR1cm4gW1xuICAgICAgJ25hbWU6IOKdkyBRdWVzdGlvbicsXG4gICAgICAnZGVzY3JpcHRpb246IEFzayBhIHF1ZXN0aW9uJyxcbiAgICAgICd0aXRsZTogXCJbUVVFU1RJT05dIDx0aXRsZT5cIicsXG4gICAgICAnbGFiZWxzOiBbXCJ0eXBlOiBxdWVzdGlvblwiXScsXG4gICAgICAnYm9keTonLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogUXVlc3Rpb24nLFxuICAgICAgJyAgICAgIGRlc2NyaXB0aW9uOiBXaGF0IHdvdWxkIHlvdSBsaWtlIHRvIGtub3c/IElmIHlvdSBlbmNvdW50ZXIgdW51c3VhbCBiZWhhdmlvciBvciBpZGVudGlmaWVkIGEgbWlzc2luZyBmZWF0dXJlLCBjb25zaWRlciBvcGVuaW5nIGEgYnVnIHJlcG9ydCBpbnN0ZWFkLicsXG4gICAgICAnICAgIHZhbGlkYXRpb25zOicsXG4gICAgICAnICAgICAgcmVxdWlyZWQ6IHRydWUnLFxuICAgICAgJyMgR2VuZXJhdGVkIGJ5IHByb2plbi4gVG8gbW9kaWZ5LCBlZGl0IC5wcm9qZW5yYy50cyBhbmQgcnVuIFwibnB4IHByb2plblwiLicsXG4gICAgXTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDbGlmZiB0b21sIGNvbmZpZ3VyYXRpb24gZm9yIHRoZSBHaXRIdWIgY29uZmlndXJhdGlvbi5cbiAgICogVGhpcyBmaWxlIGlzIHVzZWQgYnkgcmVsZWFzZSB3b3JrZmxvdyB0byBjcmVhdGUgdGhlIENoYW5nZWxvZy5cbiAgICogQHJldHVybiBUZW1wbGF0ZSBmb3IgdGhlIGNsaWZmIHRvbWwgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBjbGlmZlRvbWxDb25maWd1cmF0aW9uKCk6IHN0cmluZ1tdIHtcbiAgICByZXR1cm4gW1xuICAgICAgJyMgfn4gR2VuZXJhdGVkIGJ5IHByb2plbi4gVG8gbW9kaWZ5LCBlZGl0IC5wcm9qZW5yYy50cyBhbmQgcnVuIFwibnB4IHByb2plblwiLicsXG4gICAgICAnJyxcbiAgICAgICdbY2hhbmdlbG9nXScsXG4gICAgICAnIyBjaGFuZ2Vsb2cgaGVhZGVyJyxcbiAgICAgICdoZWFkZXIgPSBcIlwiXCInLFxuICAgICAgJyMgQ2hhbmdlbG9nXFxuJyxcbiAgICAgICdBbGwgbm90YWJsZSBjaGFuZ2VzIHRvIHRoaXMgcHJvamVjdCB3aWxsIGJlIGRvY3VtZW50ZWQgaW4gdGhpcyBmaWxlLlxcbicsXG4gICAgICAnXCJcIlwiJyxcbiAgICAgICcjIHRlbXBsYXRlIGZvciB0aGUgY2hhbmdlbG9nIGJvZHknLFxuICAgICAgJyMgaHR0cHM6Ly9rZWF0cy5naXRodWIuaW8vdGVyYS9kb2NzLyNpbnRyb2R1Y3Rpb24nLFxuICAgICAgJ2JvZHkgPSBcIlwiXCInLFxuICAgICAgJ3slIGlmIHZlcnNpb24gJX1cXFxcJyxcbiAgICAgICcgICAgIyMgW3t7IHZlcnNpb24gfCB0cmltX3N0YXJ0X21hdGNoZXMocGF0PVwidlwiKSB9fV0gLSB7eyB0aW1lc3RhbXAgfCBkYXRlKGZvcm1hdD1cIiVZLSVtLSVkXCIpIH19JyxcbiAgICAgICd7JSBlbHNlICV9XFxcXCcsXG4gICAgICAnICAgICMjIFt1bnJlbGVhc2VkXScsXG4gICAgICAneyUgZW5kaWYgJX1cXFxcJyxcbiAgICAgICd7JSBmb3IgZ3JvdXAsIGNvbW1pdHMgaW4gY29tbWl0cyB8IGdyb3VwX2J5KGF0dHJpYnV0ZT1cImdyb3VwXCIpICV9JyxcbiAgICAgICcgICAgIyMjIHt7IGdyb3VwIHwgc3RyaXB0YWdzIHwgdHJpbSB8IHVwcGVyX2ZpcnN0IH19JyxcbiAgICAgICcgICAgeyUgZm9yIGNvbW1pdCBpbiBjb21taXRzICV9JyxcbiAgICAgICcgICAgICAgIC0geyUgaWYgY29tbWl0LnNjb3BlICV9Kih7eyBjb21taXQuc2NvcGUgfX0pKiB7JSBlbmRpZiAlfVxcXFwnLFxuICAgICAgJyAgICAgICAgICAgIHslIGlmIGNvbW1pdC5icmVha2luZyAlfVsqKmJyZWFraW5nKipdIHslIGVuZGlmICV9XFxcXCcsXG4gICAgICAnICAgICAgICAgICAge3sgY29tbWl0Lm1lc3NhZ2UgfCB1cHBlcl9maXJzdCB9fVxcXFwnLFxuICAgICAgJyAgICB7JSBlbmRmb3IgJX0nLFxuICAgICAgJ3slIGVuZGZvciAlfVxcXFwnLFxuICAgICAgJ1wiXCJcIicsXG4gICAgICAnIyB0ZW1wbGF0ZSBmb3IgdGhlIGNoYW5nZWxvZyBmb290ZXInLFxuICAgICAgJ2Zvb3RlciA9IFwiXCJcIicsXG4gICAgICAnPCEtLSBnZW5lcmF0ZWQgYnkgZ2l0LWNsaWZmIC0tPicsXG4gICAgICAnXCJcIlwiJyxcbiAgICAgICcjIHJlbW92ZSB0aGUgbGVhZGluZyBhbmQgdHJhaWxpbmcgcycsXG4gICAgICAndHJpbSA9IHRydWUnLFxuICAgICAgJyMgcG9zdHByb2Nlc3NvcnMnLFxuICAgICAgJ3Bvc3Rwcm9jZXNzb3JzID0gWycsXG4gICAgICAnICAjIHsgcGF0dGVybiA9IFwiPFJFUE8+XCIsIHJlcGxhY2UgPSBcImh0dHBzOi8vZ2l0aHViLmNvbS9vcmh1bi9naXQtY2xpZmZcIiB9LCAjIHJlcGxhY2UgcmVwb3NpdG9yeSBVUkwnLFxuICAgICAgJ10nLFxuICAgICAgJycsXG4gICAgICAnW2dpdF0nLFxuICAgICAgJyMgcGFyc2UgdGhlIGNvbW1pdHMgYmFzZWQgb24gaHR0cHM6Ly93d3cuY29udmVudGlvbmFsY29tbWl0cy5vcmcnLFxuICAgICAgJ2NvbnZlbnRpb25hbF9jb21taXRzID0gdHJ1ZScsXG4gICAgICAnIyBmaWx0ZXIgb3V0IHRoZSBjb21taXRzIHRoYXQgYXJlIG5vdCBjb252ZW50aW9uYWwnLFxuICAgICAgJ2ZpbHRlcl91bmNvbnZlbnRpb25hbCA9IHRydWUnLFxuICAgICAgJyMgcHJvY2VzcyBlYWNoIGxpbmUgb2YgYSBjb21taXQgYXMgYW4gaW5kaXZpZHVhbCBjb21taXQnLFxuICAgICAgJ3NwbGl0X2NvbW1pdHMgPSBmYWxzZScsXG4gICAgICAnIyByZWdleCBmb3IgcHJlcHJvY2Vzc2luZyB0aGUgY29tbWl0IG1lc3NhZ2VzJyxcbiAgICAgICdjb21taXRfcHJlcHJvY2Vzc29ycyA9IFsnLFxuICAgICAgJyAgIyBSZXBsYWNlIGlzc3VlIG51bWJlcnMnLFxuICAgICAgJyAgI3sgcGF0dGVybiA9IFwiXFxcXCgoXFxcXHcrXFxcXHMpPyMoWzAtOV0rKVxcXFwpXCIsIHJlcGxhY2UgPSBcIihbIyR7Mn1dKDxSRVBPPi9pc3N1ZXMvJHsyfSkpXCJ9LCcsXG4gICAgICAnICAjIENoZWNrIHNwZWxsaW5nIG9mIHRoZSBjb21taXQgd2l0aCBodHRwczovL2dpdGh1Yi5jb20vY3JhdGUtY2kvdHlwb3MnLFxuICAgICAgJyAgIyBJZiB0aGUgc3BlbGxpbmcgaXMgaW5jb3JyZWN0LCBpdCB3aWxsIGJlIGF1dG9tYXRpY2FsbHkgZml4ZWQuJyxcbiAgICAgICcgICN7IHBhdHRlcm4gPSBcIi4qXCIsIHJlcGxhY2VfY29tbWFuZCA9IFwidHlwb3MgLS13cml0ZS1jaGFuZ2VzIC1cIiB9LCcsXG4gICAgICAnXScsXG4gICAgICAnIyByZWdleCBmb3IgcGFyc2luZyBhbmQgZ3JvdXBpbmcgY29tbWl0cycsXG4gICAgICAnY29tbWl0X3BhcnNlcnMgPSBbJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmZlYXRcIiwgZ3JvdXAgPSBcIjwhLS0gMCAtLT7wn5qAIEZlYXR1cmVzXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeZml4XCIsIGdyb3VwID0gXCI8IS0tIDEgLS0+8J+QmyBCdWcgRml4ZXNcIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5kb2NcIiwgZ3JvdXAgPSBcIjwhLS0gMyAtLT7wn5OaIERvY3VtZW50YXRpb25cIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5wZXJmXCIsIGdyb3VwID0gXCI8IS0tIDQgLS0+4pqhIFBlcmZvcm1hbmNlXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJecmVmYWN0b3JcIiwgZ3JvdXAgPSBcIjwhLS0gMiAtLT7wn5qcIFJlZmFjdG9yXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJec3R5bGVcIiwgZ3JvdXAgPSBcIjwhLS0gNSAtLT7wn46oIFN0eWxpbmdcIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl50ZXN0XCIsIGdyb3VwID0gXCI8IS0tIDYgLS0+8J+nqiBUZXN0aW5nXCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeY2hvcmVcXFxcKHJlbGVhc2VcXFxcKTogcHJlcGFyZSBmb3JcIiwgc2tpcCA9IHRydWUgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeY2hvcmVcXFxcKGRlcHMuKlxcXFwpXCIsIHNraXAgPSB0cnVlIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmNob3JlXFxcXChwclxcXFwpXCIsIHNraXAgPSB0cnVlIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmNob3JlXFxcXChwdWxsXFxcXClcIiwgc2tpcCA9IHRydWUgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeY2hvcmV8XmNpXCIsIGdyb3VwID0gXCI8IS0tIDcgLS0+4pqZ77iPIE1pc2NlbGxhbmVvdXMgVGFza3NcIiB9LCcsXG4gICAgICAnICB7IGJvZHkgPSBcIi4qc2VjdXJpdHlcIiwgZ3JvdXAgPSBcIjwhLS0gOCAtLT7wn5uh77iPIFNlY3VyaXR5XCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJecmV2ZXJ0XCIsIGdyb3VwID0gXCI8IS0tIDkgLS0+4peA77iPIFJldmVydFwiIH0sJyxcbiAgICAgICddJyxcbiAgICAgICcjIHByb3RlY3QgYnJlYWtpbmcgY2hhbmdlcyBmcm9tIGJlaW5nIHNraXBwZWQgZHVlIHRvIG1hdGNoaW5nIGEgc2tpcHBpbmcgY29tbWl0X3BhcnNlcicsXG4gICAgICAncHJvdGVjdF9icmVha2luZ19jb21taXRzID0gZmFsc2UnLFxuICAgICAgJyMgZmlsdGVyIG91dCB0aGUgY29tbWl0cyB0aGF0IGFyZSBub3QgbWF0Y2hlZCBieSBjb21taXQgcGFyc2VycycsXG4gICAgICAnZmlsdGVyX2NvbW1pdHMgPSBmYWxzZScsXG4gICAgICAnIyByZWdleCBmb3IgbWF0Y2hpbmcgZ2l0IHRhZ3MnLFxuICAgICAgJyMgdGFnX3BhdHRlcm4gPSBcInZbMC05XS4qXCInLFxuICAgICAgJyMgcmVnZXggZm9yIHNraXBwaW5nIHRhZ3MnLFxuICAgICAgJyMgc2tpcF90YWdzID0gXCJcIicsXG4gICAgICAnIyByZWdleCBmb3IgaWdub3JpbmcgdGFncycsXG4gICAgICAnIyBpZ25vcmVfdGFncyA9IFwiXCInLFxuICAgICAgJyMgc29ydCB0aGUgdGFncyB0b3BvbG9naWNhbGx5JyxcbiAgICAgICd0b3BvX29yZGVyID0gZmFsc2UnLFxuICAgICAgJyMgc29ydCB0aGUgY29tbWl0cyBpbnNpZGUgc2VjdGlvbnMgYnkgb2xkZXN0L25ld2VzdCBvcmRlcicsXG4gICAgICAnc29ydF9jb21taXRzID0gXCJvbGRlc3RcIicsXG4gICAgICAnIyBsaW1pdCB0aGUgbnVtYmVyIG9mIGNvbW1pdHMgaW5jbHVkZWQgaW4gdGhlIGNoYW5nZWxvZy4nLFxuICAgICAgJyMgbGltaXRfY29tbWl0cyA9IDQyJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIFdvcmtmbG93IHJlbGVhc2UgdGVtcGxhdGUgZm9yIHRoZSBHaXRIdWIgY29uZmlndXJhdGlvbi5cbiAgICogQHJldHVybiBPcHRpb25zIGZvciByZWxlYXNlIHdvcmtmbG93XG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBnZXQgcmVsZWFzZVdvcmtmbG93T3B0aW9ucygpOiBXb3JrZmxvd09wdGlvbnMge1xuICAgIHJldHVybiB7XG4gICAgICBvbjoge1xuICAgICAgICBwdWxsUmVxdWVzdDoge1xuICAgICAgICAgIGJyYW5jaGVzOiBbJ21haW4nXSxcbiAgICAgICAgICB0eXBlczogWydjbG9zZWQnXSxcbiAgICAgICAgfSxcbiAgICAgIH0sXG4gICAgICBqb2I6IHtcbiAgICAgICAgcnVuc09uOiBbJ3VidW50dS1sYXRlc3QnXSxcbiAgICAgICAgcGVybWlzc2lvbnM6IHtcbiAgICAgICAgICBjb250ZW50czogSm9iUGVybWlzc2lvbi5XUklURSxcbiAgICAgICAgICBwdWxsUmVxdWVzdHM6IEpvYlBlcm1pc3Npb24uV1JJVEUsXG4gICAgICAgIH0sXG4gICAgICAgIHN0ZXBzOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogJ0NyZWF0ZSByZWxlYXNlJyxcbiAgICAgICAgICAgIHVzZXM6ICdkeGZyb250aWVyL2doLWFjdGlvbi1yZWxlYXNlQG1haW4nLFxuICAgICAgICAgICAgd2l0aDoge1xuICAgICAgICAgICAgICBHSVRIVUJfVE9LRU46ICcke3sgc2VjcmV0cy5HSVRIVUJfVE9LRU4gfX0nLFxuICAgICAgICAgICAgICBCUkFOQ0g6ICdtYWluJyxcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgfTtcbiAgfVxuXG4gIC8qKlxuICAgKiBXb3JrZmxvdyBzdGFsZSB0ZW1wbGF0ZSBvcHRpb25zIGZvciB0aGUgR2l0SHViIGNvbmZpZ3VyYXRpb24uXG4gICAqIEByZXR1cm4gT3B0aW9ucyBmb3Igc3RhbGUgd29ya2Zsb3dcbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBzdGFsZVdvcmtmbG93T3B0aW9ucygpOiBXb3JrZmxvd09wdGlvbnMge1xuICAgIHJldHVybiB7XG4gICAgICBvbjoge1xuICAgICAgICBzY2hlZHVsZTogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGNyb246ICczNiAxOCAqICogKicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICBqb2I6IHtcbiAgICAgICAgcnVuc09uOiBbJ3VidW50dS1sYXRlc3QnXSxcbiAgICAgICAgcGVybWlzc2lvbnM6IHtcbiAgICAgICAgICBpc3N1ZXM6IEpvYlBlcm1pc3Npb24uV1JJVEUsXG4gICAgICAgICAgcHVsbFJlcXVlc3RzOiBKb2JQZXJtaXNzaW9uLldSSVRFLFxuICAgICAgICB9LFxuICAgICAgICBzdGVwczogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHVzZXM6ICdhY3Rpb25zL3N0YWxlQHY1JyxcbiAgICAgICAgICAgIHdpdGg6IHtcbiAgICAgICAgICAgICAgJ3JlcG8tdG9rZW4nOiAnJHt7IHNlY3JldHMuR0lUSFVCX1RPS0VOIH19JyxcbiAgICAgICAgICAgICAgJ2RheXMtYmVmb3JlLWlzc3VlLXN0YWxlJzogMzAsXG4gICAgICAgICAgICAgICdzdGFsZS1pc3N1ZS1tZXNzYWdlJzpcbiAgICAgICAgICAgICAgICAnVGhpcyBpc3N1ZSBoYXMgbm90IGJlZW4gdXBkYXRlZCBpbiBhIHdoaWxlLiBJZiBpdCBpcyBzdGlsbCByZWxldmFudCwgcGxlYXNlIGNvbW1lbnQgb24gaXQgdG8ga2VlcCBpdCBvcGVuLiBUaGUgaXNzdWUgd2lsbCBiZSBjbG9zZWQgc29vbiBpZiBpdCByZW1haW5zIGluYWN0aXZlLicsXG4gICAgICAgICAgICAgICdjbG9zZS1pc3N1ZS1tZXNzYWdlJzogJ1RoaXMgaXNzdWUgaGFzIGJlZW4gY2xvc2VkIGF1dG9tYXRpY2FsbHkgZHVlIHRvIGluYWN0aXZpdHkuJyxcbiAgICAgICAgICAgICAgJ3N0YWxlLXByLW1lc3NhZ2UnOlxuICAgICAgICAgICAgICAgICdUaGlzIFBSIGhhcyBub3QgYmVlbiB1cGRhdGVkIGluIGEgd2hpbGUuIElmIGl0IGlzIHN0aWxsIHJlbGV2YW50LCBwbGVhc2UgY29tbWVudCBvbiBpdCB0byBrZWVwIGl0IG9wZW4uIFRoZSBQUiB3aWxsIGJlIGNsb3NlZCBzb29uIGlmIGl0IHJlbWFpbnMgaW5hY3RpdmUuJyxcbiAgICAgICAgICAgICAgJ2Nsb3NlLXByLW1lc3NhZ2UnOiAnVGhpcyBQUiBoYXMgYmVlbiBjbG9zZWQgYXV0b21hdGljYWxseSBkdWUgdG8gaW5hY3Rpdml0eS4nLFxuICAgICAgICAgICAgICAnc3RhbGUtaXNzdWUtbGFiZWwnOiAnc3RhdHVzOiBzdGFsZScsXG4gICAgICAgICAgICAgICdzdGFsZS1wci1sYWJlbCc6ICdzdGF0dXM6IHN0YWxlJyxcbiAgICAgICAgICAgICAgJ2V4ZW1wdC1pc3N1ZS1sYWJlbHMnOiAndHlwZTogZmVhdHVyZSByZXF1ZXN0JyxcbiAgICAgICAgICAgICAgJ2V4ZW1wdC1wci1sYWJlbHMnOiAndHlwZTogZmVhdHVyZSByZXF1ZXN0JyxcbiAgICAgICAgICAgICAgJ2V4ZW1wdC1hbGwtbWlsZXN0b25lcyc6IHRydWUsXG4gICAgICAgICAgICB9LFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIH07XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgdGVtcGxhdGUgZmlsZSBmb3IgYSBHaXRIdWIgcHVsbCByZXF1ZXN0LlxuICAgKiBAcHJvdGVjdGVkXG4gICAqL1xuICBwcm90ZWN0ZWQgY3JlYXRlUHVsbFJlcXVlc3QoKTogdm9pZCB7XG4gICAgbmV3IFB1bGxSZXF1ZXN0VGVtcGxhdGUodGhpcy5wcm9qZWN0LmdpdGh1YiEsIHtcbiAgICAgIGxpbmVzOiB0aGlzLnB1bGxSZXF1ZXN0VGVtcGxhdGUsXG4gICAgfSk7XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgdGVtcGxhdGUgZmlsZSBmb3IgYSBHaXRIdWIgYnVnIGlzc3VlLlxuICAgKiBAcHJvdGVjdGVkXG4gICAqL1xuICBwcm90ZWN0ZWQgY3JlYXRlQnVnSXNzdWUoKTogdm9pZCB7XG4gICAgbmV3IFRleHRGaWxlKHRoaXMucHJvamVjdCwgdGhpcy5idWdJc3N1ZUZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy5idWdJc3N1ZVRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIGZlYXR1cmUgaXNzdWUuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBjcmVhdGVGZWF0dXJlSXNzdWUoKTogdm9pZCB7XG4gICAgbmV3IFRleHRGaWxlKHRoaXMucHJvamVjdCwgdGhpcy5mZWF0dXJlSXNzdWVGaWxlUGF0aCwge1xuICAgICAgbGluZXM6IHRoaXMuZmVhdHVyZUlzc3VlVGVtcGxhdGUsXG4gICAgfSk7XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgdGVtcGxhdGUgZmlsZSBmb3IgYSBHaXRIdWIgaG91c2VrZWVwaW5nIGlzc3VlLlxuICAgKiBAcHJvdGVjdGVkXG4gICAqL1xuICBwcm90ZWN0ZWQgY3JlYXRlSG91c2VrZWVwaW5nSXNzdWUoKTogdm9pZCB7XG4gICAgbmV3IFRleHRGaWxlKHRoaXMucHJvamVjdCwgdGhpcy5ob3VzZWtlZXBpbmdJc3N1ZUZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy5ob3VzZWtlZXBpbmdJc3N1ZVRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIHF1ZXN0aW9uIGlzc3VlLlxuICAgKiBAcHJvdGVjdGVkXG4gICAqL1xuICBwcm90ZWN0ZWQgY3JlYXRlUXVlc3Rpb25Jc3N1ZSgpOiB2b2lkIHtcbiAgICBuZXcgVGV4dEZpbGUodGhpcy5wcm9qZWN0LCB0aGlzLnF1ZXN0aW9uSXNzdWVGaWxlUGF0aCwge1xuICAgICAgbGluZXM6IHRoaXMucXVlc3Rpb25Jc3N1ZVRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIHJlbGVhc2Ugd29ya2Zsb3cuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBjcmVhdGVSZWxlYXNlV29ya2Zsb3coKTogdm9pZCB7XG4gICAgY29uc3Qgd29ya2Zsb3c6IEdpdGh1YldvcmtmbG93IHwgdW5kZWZpbmVkID0gdGhpcy5wcm9qZWN0LmdpdGh1Yj8uYWRkV29ya2Zsb3coJ1JlbGVhc2UnKTtcbiAgICB3b3JrZmxvdz8ub24odGhpcy5yZWxlYXNlV29ya2Zsb3dPcHRpb25zLm9uKTtcbiAgICB3b3JrZmxvdz8uYWRkSm9iKCdyZWxlYXNlJywgdGhpcy5yZWxlYXNlV29ya2Zsb3dPcHRpb25zLmpvYik7XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyB0aGUgdGVtcGxhdGUgZmlsZSBmb3IgYSBHaXRIdWIgc3RhbGUgd29ya2Zsb3cuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBjcmVhdGVTdGFsZVdvcmtmbG93KCk6IHZvaWQge1xuICAgIGNvbnN0IHdvcmtmbG93OiBHaXRodWJXb3JrZmxvdyB8IHVuZGVmaW5lZCA9IHRoaXMucHJvamVjdC5naXRodWI/LmFkZFdvcmtmbG93KCdTdGFsZScpO1xuICAgIHdvcmtmbG93Py5vbih0aGlzLnN0YWxlV29ya2Zsb3dPcHRpb25zLm9uKTtcbiAgICB3b3JrZmxvdz8uYWRkSm9iKCdzdGFsZScsIHRoaXMuc3RhbGVXb3JrZmxvd09wdGlvbnMuam9iKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSBjb25maWd1cmF0aW9uIGZpbGUgZm9yIHRoZSBjbGlmZiB0b21sIENIQU5HRUxPRyBjcmVhdGlvbiBpbiByZWxlYXNlIHdvcmtmbG93LlxuICAgKiBAcHJvdGVjdGVkXG4gICAqL1xuICBwcm90ZWN0ZWQgY3JlYXRlQ2xpZmZUb21sQ29uZmlndXJhdGlvbigpOiB2b2lkIHtcbiAgICBuZXcgVGV4dEZpbGUodGhpcy5wcm9qZWN0LCB0aGlzLmNsaWZmVG9tbEZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy5jbGlmZlRvbWxDb25maWd1cmF0aW9uLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIEBvdmVycmlkZVxuICAgKi9cbiAgcHJvdGVjdGVkIGFkZFRlbXBsYXRlcygpOiB2b2lkIHtcbiAgICB0aGlzLmNyZWF0ZVB1bGxSZXF1ZXN0KCk7XG4gICAgdGhpcy5jcmVhdGVCdWdJc3N1ZSgpO1xuICAgIHRoaXMuY3JlYXRlRmVhdHVyZUlzc3VlKCk7XG4gICAgdGhpcy5jcmVhdGVIb3VzZWtlZXBpbmdJc3N1ZSgpO1xuICAgIHRoaXMuY3JlYXRlUXVlc3Rpb25Jc3N1ZSgpO1xuXG4gICAgdGhpcy5jcmVhdGVSZWxlYXNlV29ya2Zsb3coKTtcbiAgICB0aGlzLmNyZWF0ZVN0YWxlV29ya2Zsb3coKTtcbiAgICB0aGlzLmNyZWF0ZUNsaWZmVG9tbENvbmZpZ3VyYXRpb24oKTtcbiAgfVxufVxuIl19