"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.GitHubBase = void 0;
const JSII_RTTI_SYMBOL_1 = Symbol.for("jsii.rtti");
const projen_1 = require("projen");
const github_1 = require("projen/lib/github");
const workflows_model_1 = require("projen/lib/github/workflows-model");
const builder_1 = require("./builder");
/**
 * Base class for GitHub builder implementing all relevant configuration.
 * @abstract
 */
class GitHubBase extends builder_1.Builder {
    /**
     * Initializes the base GitHub builder.
     * @param project The project to configure GitHub builder for.
     */
    constructor(project) {
        super(project);
    }
    /**
     * File path to GitHub bug issue template.
     * @return File path to bug issue file.
     * @protected
     */
    get bugIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/bug.yml';
    }
    /**
     *File path to GitHub feature issue template.
     @return File path to feature issue file.
     @protected
     */
    get featureIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/feature.yml';
    }
    /**
     *File path to GitHub housekeeping issue template.
     @return File path to housekeeping issue file.
     @protected
     */
    get housekeepingIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/housekeeping.yml';
    }
    /**
     * File path to GitHub question issue template.
     * @return File path to question issue file.
     * @protected
     */
    get questionIssueFilePath() {
        return '.github/ISSUE_TEMPLATE/question.yml';
    }
    /**
     * File path to the Cliff toml configuration.
     * This file is used by release workflow to create the Changelog.
     * @return File path to cliff toml file.
     * @protected
     */
    get cliffTomlFilePath() {
        return 'cliff.toml';
    }
    /**
     * Pull Request template for the GitHub configuration.
     * @return File path to pull request template file.
     * @protected
     */
    get pullRequestTemplate() {
        return [
            '## Reviewers Checklist',
            '',
            'for complete review list refer to ABS Loop - Review Aspects',
            '',
            '### Organizational Section',
            '',
            '- [ ] PR is assigned to the according feature/bug',
            '- [ ] Feature/bug is descriptive',
            '- [ ] Feature/bug is assigned to according labels',
            '- [ ] Feature/bug is assigned to a developer',
            '',
            '### Structure',
            '',
            '- [ ] Readability: Code is easy to understand, with meaningful names for variables, functions, and classes',
            '- [ ] Comments: Meaningful and helpful comments. Code is documented without being over-commented',
            '- [ ] DRY, KISS and YAGNI: Code implements only necessary features; no over-engineering',
            '- [ ] No sensitive data (e.g., passwords, API keys) in the code',
            '- [ ] No major updates for used packages',
            '',
            '### Testing',
            '',
            '- [ ] Code is locally tested by developer (if applicable)',
            '- [ ] Automated tests pass successfully',
            '<!-- Generated by projen. To modify, edit .projenrc.ts and run "npx projen".-->',
        ];
    }
    /**
     * Issue template for the GitHub Bug configuration.
     * @return Template for the bug issue template file.
     * @protected
     */
    get bugIssueTemplate() {
        return [
            'name: 🐞 Bug',
            'description: File a bug/issue',
            'title: "[BUG] <title>"',
            'labels: ["type: bug"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Current behavior',
            "      description: A description of what you're experiencing.",
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Expected behavior',
            '      description: A description of what you expected to happen.',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Issue template for the GitHub feature configuration.
     * @return Template for the feature issue template file.
     * @protected
     */
    get featureIssueTemplate() {
        return [
            'name: 💡 Feature',
            'description: Request for a new feature',
            'title: "[FEATURE] <title>"',
            'labels: ["type: feature"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Description',
            '      description: A description of the feature.',
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Task List',
            '      description: Describe the steps to fulfill the feature.',
            '      value: |',
            '        - [ ] My First Task',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Issue template for the GitHub housekeeping configuration.
     * @return Template for the housekeeping issue template file.
     * @protected
     */
    get housekeepingIssueTemplate() {
        return [
            'name: 💡 Housekeeping',
            'description: Maintenance or refactoring task',
            'title: "[HOUSEKEEPING] <title>"',
            'labels: ["type: housekeeping"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Description',
            '      description: A description of the housekeeping task.',
            '    validations:',
            '      required: true',
            '',
            '  - type: textarea',
            '    attributes:',
            '      label: Task List',
            '      description: Describe the steps to fulfill the housekeeping task.',
            '      value: |',
            '        - [ ] My First Task',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Template for the GitHub Question Issue configuration.
     * @return Template for the question issue template file.
     * @protected
     */
    get questionIssueTemplate() {
        return [
            'name: ❓ Question',
            'description: Ask a question',
            'title: "[QUESTION] <title>"',
            'labels: ["type: question"]',
            'body:',
            '  - type: textarea',
            '    attributes:',
            '      label: Question',
            '      description: What would you like to know? If you encounter unusual behavior or identified a missing feature, consider opening a bug report instead.',
            '    validations:',
            '      required: true',
            '# Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
        ];
    }
    /**
     * Cliff toml configuration for the GitHub configuration.
     * This file is used by release workflow to create the Changelog.
     * @return Template for the cliff toml file.
     * @protected
     */
    get cliffTomlConfiguration() {
        return [
            '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
            '',
            '[changelog]',
            '# changelog header',
            'header = """',
            '# Changelog\n',
            'All notable changes to this project will be documented in this file.\n',
            '"""',
            '# template for the changelog body',
            '# https://keats.github.io/tera/docs/#introduction',
            'body = """',
            '{% if version %}\\',
            '    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}',
            '{% else %}\\',
            '    ## [unreleased]',
            '{% endif %}\\',
            '{% for group, commits in commits | group_by(attribute="group") %}',
            '    ### {{ group | striptags | trim | upper_first }}',
            '    {% for commit in commits %}',
            '        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\\',
            '            {% if commit.breaking %}[**breaking**] {% endif %}\\',
            '            {{ commit.message | upper_first }}\\',
            '    {% endfor %}',
            '{% endfor %}\\',
            '"""',
            '# template for the changelog footer',
            'footer = """',
            '<!-- generated by git-cliff -->',
            '"""',
            '# remove the leading and trailing s',
            'trim = true',
            '# postprocessors',
            'postprocessors = [',
            '  # { pattern = "<REPO>", replace = "https://github.com/orhun/git-cliff" }, # replace repository URL',
            ']',
            '',
            '[git]',
            '# parse the commits based on https://www.conventionalcommits.org',
            'conventional_commits = true',
            '# filter out the commits that are not conventional',
            'filter_unconventional = true',
            '# process each line of a commit as an individual commit',
            'split_commits = false',
            '# regex for preprocessing the commit messages',
            'commit_preprocessors = [',
            '  # Replace issue numbers',
            '  #{ pattern = "((w+s)?#([0-9]+))", replace = "([#${2}](<REPO>/issues/${2}))"},',
            '  # Check spelling of the commit with https://github.com/crate-ci/typos',
            '  # If the spelling is incorrect, it will be automatically fixed.',
            '  #{ pattern = ".*", replace_command = "typos --write-changes -" },',
            ']',
            '# regex for parsing and grouping commits',
            'commit_parsers = [',
            '  { message = "^feat", group = "<!-- 0 -->🚀 Features" },',
            '  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },',
            '  { message = "^doc", group = "<!-- 3 -->📚 Documentation" },',
            '  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },',
            '  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },',
            '  { message = "^style", group = "<!-- 5 -->🎨 Styling" },',
            '  { message = "^test", group = "<!-- 6 -->🧪 Testing" },',
            '  { message = "^chore(release): prepare for", skip = true },',
            '  { message = "^chore(deps.*)", skip = true },',
            '  { message = "^chore(pr)", skip = true },',
            '  { message = "^chore(pull)", skip = true },',
            '  { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },',
            '  { body = ".*security", group = "<!-- 8 -->🛡️ Security" },',
            '  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },',
            ']',
            '# protect breaking changes from being skipped due to matching a skipping commit_parser',
            'protect_breaking_commits = false',
            '# filter out the commits that are not matched by commit parsers',
            'filter_commits = false',
            '# regex for matching git tags',
            '# tag_pattern = "v[0-9].*"',
            '# regex for skipping tags',
            '# skip_tags = ""',
            '# regex for ignoring tags',
            '# ignore_tags = ""',
            '# sort the tags topologically',
            'topo_order = false',
            '# sort the commits inside sections by oldest/newest order',
            'sort_commits = "oldest"',
            '# limit the number of commits included in the changelog.',
            '# limit_commits = 42',
        ];
    }
    /**
     * Workflow release template for the GitHub configuration.
     * @return Options for release workflow
     * @protected
     */
    get releaseWorkflowOptions() {
        return {
            on: {
                pullRequest: {
                    branches: ['main'],
                    types: ['closed'],
                },
            },
            job: {
                runsOn: ['ubuntu-latest'],
                permissions: {
                    contents: workflows_model_1.JobPermission.WRITE,
                    pullRequests: workflows_model_1.JobPermission.WRITE,
                },
                steps: [
                    {
                        name: 'Create release',
                        uses: 'dxfrontier/gh-action-release@main',
                        with: {
                            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
                            BRANCH: 'main',
                        },
                    },
                ],
            },
        };
    }
    /**
     * Creates the template file for a GitHub pull request.
     * @private
     */
    createPullRequest() {
        new github_1.PullRequestTemplate(this.project.github, {
            lines: this.pullRequestTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub bug issue.
     * @private
     */
    createBugIssue() {
        new projen_1.TextFile(this.project, this.bugIssueFilePath, {
            lines: this.bugIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub feature issue.
     * @private
     */
    createFeatureIssue() {
        new projen_1.TextFile(this.project, this.featureIssueFilePath, {
            lines: this.featureIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub housekeeping issue.
     * @private
     */
    createHousekeepingIssue() {
        new projen_1.TextFile(this.project, this.housekeepingIssueFilePath, {
            lines: this.housekeepingIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub question issue.
     * @private
     */
    createQuestionIssue() {
        new projen_1.TextFile(this.project, this.questionIssueFilePath, {
            lines: this.questionIssueTemplate,
        });
    }
    /**
     * Creates the template file for a GitHub release workflow.
     * @private
     */
    createReleaseWorkflow() {
        const workflow = this.project.github?.addWorkflow('Release');
        workflow?.on(this.releaseWorkflowOptions.on);
        workflow?.addJob('release', this.releaseWorkflowOptions.job);
    }
    /**
     * Creates the configuration file for the cliff toml CHANGELOG creation in release workflow.
     * @private
     */
    createCliffTomlConfiguration() {
        new projen_1.TextFile(this.project, this.cliffTomlFilePath, {
            lines: this.cliffTomlConfiguration,
        });
    }
    addTemplates() {
        this.createPullRequest();
        this.createBugIssue();
        this.createFeatureIssue();
        this.createHousekeepingIssue();
        this.createQuestionIssue();
        this.createReleaseWorkflow();
        this.createCliffTomlConfiguration();
    }
}
exports.GitHubBase = GitHubBase;
_a = JSII_RTTI_SYMBOL_1;
GitHubBase[_a] = { fqn: "@dxfrontier/projen-template-projects.GitHubBase", version: "0.0.0" };
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZ2l0aHViLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vc3JjL2Jhc2UvZ2l0aHViLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7O0FBQUEsbUNBQWtDO0FBQ2xDLDhDQUF3RTtBQUN4RSx1RUFBa0U7QUFDbEUsdUNBQW9DO0FBSXBDOzs7R0FHRztBQUNILE1BQXNCLFVBQVcsU0FBUSxpQkFBTztJQUM5Qzs7O09BR0c7SUFDSCxZQUFZLE9BQThCO1FBQ3hDLEtBQUssQ0FBQyxPQUFPLENBQUMsQ0FBQztJQUNqQixDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMsZ0JBQWdCO1FBQzVCLE9BQU8sZ0NBQWdDLENBQUM7SUFDMUMsQ0FBQztJQUVEOzs7O09BSUc7SUFDSCxJQUFjLG9CQUFvQjtRQUNoQyxPQUFPLG9DQUFvQyxDQUFDO0lBQzlDLENBQUM7SUFFRDs7OztPQUlHO0lBQ0gsSUFBYyx5QkFBeUI7UUFDckMsT0FBTyx5Q0FBeUMsQ0FBQztJQUNuRCxDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMscUJBQXFCO1FBQ2pDLE9BQU8scUNBQXFDLENBQUM7SUFDL0MsQ0FBQztJQUVEOzs7OztPQUtHO0lBQ0gsSUFBYyxpQkFBaUI7UUFDN0IsT0FBTyxZQUFZLENBQUM7SUFDdEIsQ0FBQztJQUVEOzs7O09BSUc7SUFDSCxJQUFjLG1CQUFtQjtRQUMvQixPQUFPO1lBQ0wsd0JBQXdCO1lBQ3hCLEVBQUU7WUFDRiw2REFBNkQ7WUFDN0QsRUFBRTtZQUNGLDRCQUE0QjtZQUM1QixFQUFFO1lBQ0YsbURBQW1EO1lBQ25ELGtDQUFrQztZQUNsQyxtREFBbUQ7WUFDbkQsOENBQThDO1lBQzlDLEVBQUU7WUFDRixlQUFlO1lBQ2YsRUFBRTtZQUNGLDRHQUE0RztZQUM1RyxrR0FBa0c7WUFDbEcseUZBQXlGO1lBQ3pGLGlFQUFpRTtZQUNqRSwwQ0FBMEM7WUFDMUMsRUFBRTtZQUNGLGFBQWE7WUFDYixFQUFFO1lBQ0YsMkRBQTJEO1lBQzNELHlDQUF5QztZQUN6QyxpRkFBaUY7U0FDbEYsQ0FBQztJQUNKLENBQUM7SUFFRDs7OztPQUlHO0lBQ0gsSUFBYyxnQkFBZ0I7UUFDNUIsT0FBTztZQUNMLGNBQWM7WUFDZCwrQkFBK0I7WUFDL0Isd0JBQXdCO1lBQ3hCLHVCQUF1QjtZQUN2QixPQUFPO1lBQ1Asb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQiwrQkFBK0I7WUFDL0IsK0RBQStEO1lBQy9ELGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsRUFBRTtZQUNGLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsZ0NBQWdDO1lBQ2hDLGtFQUFrRTtZQUNsRSxrQkFBa0I7WUFDbEIsc0JBQXNCO1lBQ3RCLDJFQUEyRTtTQUM1RSxDQUFDO0lBQ0osQ0FBQztJQUVEOzs7O09BSUc7SUFDSCxJQUFjLG9CQUFvQjtRQUNoQyxPQUFPO1lBQ0wsa0JBQWtCO1lBQ2xCLHdDQUF3QztZQUN4Qyw0QkFBNEI7WUFDNUIsMkJBQTJCO1lBQzNCLE9BQU87WUFDUCxvQkFBb0I7WUFDcEIsaUJBQWlCO1lBQ2pCLDBCQUEwQjtZQUMxQixrREFBa0Q7WUFDbEQsa0JBQWtCO1lBQ2xCLHNCQUFzQjtZQUN0QixFQUFFO1lBQ0Ysb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQix3QkFBd0I7WUFDeEIsK0RBQStEO1lBQy9ELGdCQUFnQjtZQUNoQiw2QkFBNkI7WUFDN0Isa0JBQWtCO1lBQ2xCLHNCQUFzQjtZQUN0QiwyRUFBMkU7U0FDNUUsQ0FBQztJQUNKLENBQUM7SUFFRDs7OztPQUlHO0lBQ0gsSUFBYyx5QkFBeUI7UUFDckMsT0FBTztZQUNMLHVCQUF1QjtZQUN2Qiw4Q0FBOEM7WUFDOUMsaUNBQWlDO1lBQ2pDLGdDQUFnQztZQUNoQyxPQUFPO1lBQ1Asb0JBQW9CO1lBQ3BCLGlCQUFpQjtZQUNqQiwwQkFBMEI7WUFDMUIsNERBQTREO1lBQzVELGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsRUFBRTtZQUNGLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsd0JBQXdCO1lBQ3hCLHlFQUF5RTtZQUN6RSxnQkFBZ0I7WUFDaEIsNkJBQTZCO1lBQzdCLGtCQUFrQjtZQUNsQixzQkFBc0I7WUFDdEIsMkVBQTJFO1NBQzVFLENBQUM7SUFDSixDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMscUJBQXFCO1FBQ2pDLE9BQU87WUFDTCxrQkFBa0I7WUFDbEIsNkJBQTZCO1lBQzdCLDZCQUE2QjtZQUM3Qiw0QkFBNEI7WUFDNUIsT0FBTztZQUNQLG9CQUFvQjtZQUNwQixpQkFBaUI7WUFDakIsdUJBQXVCO1lBQ3ZCLDJKQUEySjtZQUMzSixrQkFBa0I7WUFDbEIsc0JBQXNCO1lBQ3RCLDJFQUEyRTtTQUM1RSxDQUFDO0lBQ0osQ0FBQztJQUVEOzs7OztPQUtHO0lBQ0gsSUFBYyxzQkFBc0I7UUFDbEMsT0FBTztZQUNMLDhFQUE4RTtZQUM5RSxFQUFFO1lBQ0YsYUFBYTtZQUNiLG9CQUFvQjtZQUNwQixjQUFjO1lBQ2QsZUFBZTtZQUNmLHdFQUF3RTtZQUN4RSxLQUFLO1lBQ0wsbUNBQW1DO1lBQ25DLG1EQUFtRDtZQUNuRCxZQUFZO1lBQ1osb0JBQW9CO1lBQ3BCLGtHQUFrRztZQUNsRyxjQUFjO1lBQ2QscUJBQXFCO1lBQ3JCLGVBQWU7WUFDZixtRUFBbUU7WUFDbkUsc0RBQXNEO1lBQ3RELGlDQUFpQztZQUNqQyxxRUFBcUU7WUFDckUsa0VBQWtFO1lBQ2xFLGtEQUFrRDtZQUNsRCxrQkFBa0I7WUFDbEIsZ0JBQWdCO1lBQ2hCLEtBQUs7WUFDTCxxQ0FBcUM7WUFDckMsY0FBYztZQUNkLGlDQUFpQztZQUNqQyxLQUFLO1lBQ0wscUNBQXFDO1lBQ3JDLGFBQWE7WUFDYixrQkFBa0I7WUFDbEIsb0JBQW9CO1lBQ3BCLHNHQUFzRztZQUN0RyxHQUFHO1lBQ0gsRUFBRTtZQUNGLE9BQU87WUFDUCxrRUFBa0U7WUFDbEUsNkJBQTZCO1lBQzdCLG9EQUFvRDtZQUNwRCw4QkFBOEI7WUFDOUIseURBQXlEO1lBQ3pELHVCQUF1QjtZQUN2QiwrQ0FBK0M7WUFDL0MsMEJBQTBCO1lBQzFCLDJCQUEyQjtZQUMzQixpRkFBaUY7WUFDakYseUVBQXlFO1lBQ3pFLG1FQUFtRTtZQUNuRSxxRUFBcUU7WUFDckUsR0FBRztZQUNILDBDQUEwQztZQUMxQyxvQkFBb0I7WUFDcEIsMkRBQTJEO1lBQzNELDJEQUEyRDtZQUMzRCwrREFBK0Q7WUFDL0QsNkRBQTZEO1lBQzdELCtEQUErRDtZQUMvRCwyREFBMkQ7WUFDM0QsMERBQTBEO1lBQzFELDhEQUE4RDtZQUM5RCxnREFBZ0Q7WUFDaEQsNENBQTRDO1lBQzVDLDhDQUE4QztZQUM5QywyRUFBMkU7WUFDM0UsOERBQThEO1lBQzlELDJEQUEyRDtZQUMzRCxHQUFHO1lBQ0gsd0ZBQXdGO1lBQ3hGLGtDQUFrQztZQUNsQyxpRUFBaUU7WUFDakUsd0JBQXdCO1lBQ3hCLCtCQUErQjtZQUMvQiw0QkFBNEI7WUFDNUIsMkJBQTJCO1lBQzNCLGtCQUFrQjtZQUNsQiwyQkFBMkI7WUFDM0Isb0JBQW9CO1lBQ3BCLCtCQUErQjtZQUMvQixvQkFBb0I7WUFDcEIsMkRBQTJEO1lBQzNELHlCQUF5QjtZQUN6QiwwREFBMEQ7WUFDMUQsc0JBQXNCO1NBQ3ZCLENBQUM7SUFDSixDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILElBQWMsc0JBQXNCO1FBQ2xDLE9BQU87WUFDTCxFQUFFLEVBQUU7Z0JBQ0YsV0FBVyxFQUFFO29CQUNYLFFBQVEsRUFBRSxDQUFDLE1BQU0sQ0FBQztvQkFDbEIsS0FBSyxFQUFFLENBQUMsUUFBUSxDQUFDO2lCQUNsQjthQUNGO1lBQ0QsR0FBRyxFQUFFO2dCQUNILE1BQU0sRUFBRSxDQUFDLGVBQWUsQ0FBQztnQkFDekIsV0FBVyxFQUFFO29CQUNYLFFBQVEsRUFBRSwrQkFBYSxDQUFDLEtBQUs7b0JBQzdCLFlBQVksRUFBRSwrQkFBYSxDQUFDLEtBQUs7aUJBQ2xDO2dCQUNELEtBQUssRUFBRTtvQkFDTDt3QkFDRSxJQUFJLEVBQUUsZ0JBQWdCO3dCQUN0QixJQUFJLEVBQUUsbUNBQW1DO3dCQUN6QyxJQUFJLEVBQUU7NEJBQ0osWUFBWSxFQUFFLDZCQUE2Qjs0QkFDM0MsTUFBTSxFQUFFLE1BQU07eUJBQ2Y7cUJBQ0Y7aUJBQ0Y7YUFDRjtTQUNGLENBQUM7SUFDSixDQUFDO0lBRUQ7OztPQUdHO0lBQ0ssaUJBQWlCO1FBQ3ZCLElBQUksNEJBQW1CLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBQyxNQUFPLEVBQUU7WUFDNUMsS0FBSyxFQUFFLElBQUksQ0FBQyxtQkFBbUI7U0FDaEMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOzs7T0FHRztJQUNLLGNBQWM7UUFDcEIsSUFBSSxpQkFBUSxDQUFDLElBQUksQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLGdCQUFnQixFQUFFO1lBQ2hELEtBQUssRUFBRSxJQUFJLENBQUMsZ0JBQWdCO1NBQzdCLENBQUMsQ0FBQztJQUNMLENBQUM7SUFFRDs7O09BR0c7SUFDSyxrQkFBa0I7UUFDeEIsSUFBSSxpQkFBUSxDQUFDLElBQUksQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLG9CQUFvQixFQUFFO1lBQ3BELEtBQUssRUFBRSxJQUFJLENBQUMsb0JBQW9CO1NBQ2pDLENBQUMsQ0FBQztJQUNMLENBQUM7SUFFRDs7O09BR0c7SUFDSyx1QkFBdUI7UUFDN0IsSUFBSSxpQkFBUSxDQUFDLElBQUksQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLHlCQUF5QixFQUFFO1lBQ3pELEtBQUssRUFBRSxJQUFJLENBQUMseUJBQXlCO1NBQ3RDLENBQUMsQ0FBQztJQUNMLENBQUM7SUFFRDs7O09BR0c7SUFDSyxtQkFBbUI7UUFDekIsSUFBSSxpQkFBUSxDQUFDLElBQUksQ0FBQyxPQUFPLEVBQUUsSUFBSSxDQUFDLHFCQUFxQixFQUFFO1lBQ3JELEtBQUssRUFBRSxJQUFJLENBQUMscUJBQXFCO1NBQ2xDLENBQUMsQ0FBQztJQUNMLENBQUM7SUFFRDs7O09BR0c7SUFDSyxxQkFBcUI7UUFDM0IsTUFBTSxRQUFRLEdBQStCLElBQUksQ0FBQyxPQUFPLENBQUMsTUFBTSxFQUFFLFdBQVcsQ0FBQyxTQUFTLENBQUMsQ0FBQztRQUN6RixRQUFRLEVBQUUsRUFBRSxDQUFDLElBQUksQ0FBQyxzQkFBc0IsQ0FBQyxFQUFFLENBQUMsQ0FBQztRQUM3QyxRQUFRLEVBQUUsTUFBTSxDQUFDLFNBQVMsRUFBRSxJQUFJLENBQUMsc0JBQXNCLENBQUMsR0FBRyxDQUFDLENBQUM7SUFDL0QsQ0FBQztJQUVEOzs7T0FHRztJQUNLLDRCQUE0QjtRQUNsQyxJQUFJLGlCQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxJQUFJLENBQUMsaUJBQWlCLEVBQUU7WUFDakQsS0FBSyxFQUFFLElBQUksQ0FBQyxzQkFBc0I7U0FDbkMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVTLFlBQVk7UUFDcEIsSUFBSSxDQUFDLGlCQUFpQixFQUFFLENBQUM7UUFDekIsSUFBSSxDQUFDLGNBQWMsRUFBRSxDQUFDO1FBQ3RCLElBQUksQ0FBQyxrQkFBa0IsRUFBRSxDQUFDO1FBQzFCLElBQUksQ0FBQyx1QkFBdUIsRUFBRSxDQUFDO1FBQy9CLElBQUksQ0FBQyxtQkFBbUIsRUFBRSxDQUFDO1FBRTNCLElBQUksQ0FBQyxxQkFBcUIsRUFBRSxDQUFDO1FBQzdCLElBQUksQ0FBQyw0QkFBNEIsRUFBRSxDQUFDO0lBQ3RDLENBQUM7O0FBelpILGdDQTBaQyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IFRleHRGaWxlIH0gZnJvbSAncHJvamVuJztcbmltcG9ydCB7IEdpdGh1YldvcmtmbG93LCBQdWxsUmVxdWVzdFRlbXBsYXRlIH0gZnJvbSAncHJvamVuL2xpYi9naXRodWInO1xuaW1wb3J0IHsgSm9iUGVybWlzc2lvbiB9IGZyb20gJ3Byb2plbi9saWIvZ2l0aHViL3dvcmtmbG93cy1tb2RlbCc7XG5pbXBvcnQgeyBCdWlsZGVyIH0gZnJvbSAnLi9idWlsZGVyJztcbmltcG9ydCB7IFdvcmtmbG93T3B0aW9ucyB9IGZyb20gJy4uL3R5cGVzJztcbmltcG9ydCB7IFR5cGVTY3JpcHRQcm9qZWN0QmFzZSB9IGZyb20gJy4vcHJvamVjdCc7XG5cbi8qKlxuICogQmFzZSBjbGFzcyBmb3IgR2l0SHViIGJ1aWxkZXIgaW1wbGVtZW50aW5nIGFsbCByZWxldmFudCBjb25maWd1cmF0aW9uLlxuICogQGFic3RyYWN0XG4gKi9cbmV4cG9ydCBhYnN0cmFjdCBjbGFzcyBHaXRIdWJCYXNlIGV4dGVuZHMgQnVpbGRlciB7XG4gIC8qKlxuICAgKiBJbml0aWFsaXplcyB0aGUgYmFzZSBHaXRIdWIgYnVpbGRlci5cbiAgICogQHBhcmFtIHByb2plY3QgVGhlIHByb2plY3QgdG8gY29uZmlndXJlIEdpdEh1YiBidWlsZGVyIGZvci5cbiAgICovXG4gIGNvbnN0cnVjdG9yKHByb2plY3Q6IFR5cGVTY3JpcHRQcm9qZWN0QmFzZSkge1xuICAgIHN1cGVyKHByb2plY3QpO1xuICB9XG5cbiAgLyoqXG4gICAqIEZpbGUgcGF0aCB0byBHaXRIdWIgYnVnIGlzc3VlIHRlbXBsYXRlLlxuICAgKiBAcmV0dXJuIEZpbGUgcGF0aCB0byBidWcgaXNzdWUgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBidWdJc3N1ZUZpbGVQYXRoKCk6IHN0cmluZyB7XG4gICAgcmV0dXJuICcuZ2l0aHViL0lTU1VFX1RFTVBMQVRFL2J1Zy55bWwnO1xuICB9XG5cbiAgLyoqXG4gICAqRmlsZSBwYXRoIHRvIEdpdEh1YiBmZWF0dXJlIGlzc3VlIHRlbXBsYXRlLlxuICAgQHJldHVybiBGaWxlIHBhdGggdG8gZmVhdHVyZSBpc3N1ZSBmaWxlLlxuICAgQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBmZWF0dXJlSXNzdWVGaWxlUGF0aCgpOiBzdHJpbmcge1xuICAgIHJldHVybiAnLmdpdGh1Yi9JU1NVRV9URU1QTEFURS9mZWF0dXJlLnltbCc7XG4gIH1cblxuICAvKipcbiAgICpGaWxlIHBhdGggdG8gR2l0SHViIGhvdXNla2VlcGluZyBpc3N1ZSB0ZW1wbGF0ZS5cbiAgIEByZXR1cm4gRmlsZSBwYXRoIHRvIGhvdXNla2VlcGluZyBpc3N1ZSBmaWxlLlxuICAgQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBob3VzZWtlZXBpbmdJc3N1ZUZpbGVQYXRoKCk6IHN0cmluZyB7XG4gICAgcmV0dXJuICcuZ2l0aHViL0lTU1VFX1RFTVBMQVRFL2hvdXNla2VlcGluZy55bWwnO1xuICB9XG5cbiAgLyoqXG4gICAqIEZpbGUgcGF0aCB0byBHaXRIdWIgcXVlc3Rpb24gaXNzdWUgdGVtcGxhdGUuXG4gICAqIEByZXR1cm4gRmlsZSBwYXRoIHRvIHF1ZXN0aW9uIGlzc3VlIGZpbGUuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBnZXQgcXVlc3Rpb25Jc3N1ZUZpbGVQYXRoKCk6IHN0cmluZyB7XG4gICAgcmV0dXJuICcuZ2l0aHViL0lTU1VFX1RFTVBMQVRFL3F1ZXN0aW9uLnltbCc7XG4gIH1cblxuICAvKipcbiAgICogRmlsZSBwYXRoIHRvIHRoZSBDbGlmZiB0b21sIGNvbmZpZ3VyYXRpb24uXG4gICAqIFRoaXMgZmlsZSBpcyB1c2VkIGJ5IHJlbGVhc2Ugd29ya2Zsb3cgdG8gY3JlYXRlIHRoZSBDaGFuZ2Vsb2cuXG4gICAqIEByZXR1cm4gRmlsZSBwYXRoIHRvIGNsaWZmIHRvbWwgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBjbGlmZlRvbWxGaWxlUGF0aCgpOiBzdHJpbmcge1xuICAgIHJldHVybiAnY2xpZmYudG9tbCc7XG4gIH1cblxuICAvKipcbiAgICogUHVsbCBSZXF1ZXN0IHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIGNvbmZpZ3VyYXRpb24uXG4gICAqIEByZXR1cm4gRmlsZSBwYXRoIHRvIHB1bGwgcmVxdWVzdCB0ZW1wbGF0ZSBmaWxlLlxuICAgKiBAcHJvdGVjdGVkXG4gICAqL1xuICBwcm90ZWN0ZWQgZ2V0IHB1bGxSZXF1ZXN0VGVtcGxhdGUoKTogc3RyaW5nW10ge1xuICAgIHJldHVybiBbXG4gICAgICAnIyMgUmV2aWV3ZXJzIENoZWNrbGlzdCcsXG4gICAgICAnJyxcbiAgICAgICdmb3IgY29tcGxldGUgcmV2aWV3IGxpc3QgcmVmZXIgdG8gQUJTIExvb3AgLSBSZXZpZXcgQXNwZWN0cycsXG4gICAgICAnJyxcbiAgICAgICcjIyMgT3JnYW5pemF0aW9uYWwgU2VjdGlvbicsXG4gICAgICAnJyxcbiAgICAgICctIFsgXSBQUiBpcyBhc3NpZ25lZCB0byB0aGUgYWNjb3JkaW5nIGZlYXR1cmUvYnVnJyxcbiAgICAgICctIFsgXSBGZWF0dXJlL2J1ZyBpcyBkZXNjcmlwdGl2ZScsXG4gICAgICAnLSBbIF0gRmVhdHVyZS9idWcgaXMgYXNzaWduZWQgdG8gYWNjb3JkaW5nIGxhYmVscycsXG4gICAgICAnLSBbIF0gRmVhdHVyZS9idWcgaXMgYXNzaWduZWQgdG8gYSBkZXZlbG9wZXInLFxuICAgICAgJycsXG4gICAgICAnIyMjIFN0cnVjdHVyZScsXG4gICAgICAnJyxcbiAgICAgICctIFsgXSBSZWFkYWJpbGl0eTogQ29kZSBpcyBlYXN5IHRvIHVuZGVyc3RhbmQsIHdpdGggbWVhbmluZ2Z1bCBuYW1lcyBmb3IgdmFyaWFibGVzLCBmdW5jdGlvbnMsIGFuZCBjbGFzc2VzJyxcbiAgICAgICctIFsgXSBDb21tZW50czogTWVhbmluZ2Z1bCBhbmQgaGVscGZ1bCBjb21tZW50cy4gQ29kZSBpcyBkb2N1bWVudGVkIHdpdGhvdXQgYmVpbmcgb3Zlci1jb21tZW50ZWQnLFxuICAgICAgJy0gWyBdIERSWSwgS0lTUyBhbmQgWUFHTkk6IENvZGUgaW1wbGVtZW50cyBvbmx5IG5lY2Vzc2FyeSBmZWF0dXJlczsgbm8gb3Zlci1lbmdpbmVlcmluZycsXG4gICAgICAnLSBbIF0gTm8gc2Vuc2l0aXZlIGRhdGEgKGUuZy4sIHBhc3N3b3JkcywgQVBJIGtleXMpIGluIHRoZSBjb2RlJyxcbiAgICAgICctIFsgXSBObyBtYWpvciB1cGRhdGVzIGZvciB1c2VkIHBhY2thZ2VzJyxcbiAgICAgICcnLFxuICAgICAgJyMjIyBUZXN0aW5nJyxcbiAgICAgICcnLFxuICAgICAgJy0gWyBdIENvZGUgaXMgbG9jYWxseSB0ZXN0ZWQgYnkgZGV2ZWxvcGVyIChpZiBhcHBsaWNhYmxlKScsXG4gICAgICAnLSBbIF0gQXV0b21hdGVkIHRlc3RzIHBhc3Mgc3VjY2Vzc2Z1bGx5JyxcbiAgICAgICc8IS0tIEdlbmVyYXRlZCBieSBwcm9qZW4uIFRvIG1vZGlmeSwgZWRpdCAucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4tLT4nLFxuICAgIF07XG4gIH1cblxuICAvKipcbiAgICogSXNzdWUgdGVtcGxhdGUgZm9yIHRoZSBHaXRIdWIgQnVnIGNvbmZpZ3VyYXRpb24uXG4gICAqIEByZXR1cm4gVGVtcGxhdGUgZm9yIHRoZSBidWcgaXNzdWUgdGVtcGxhdGUgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBidWdJc3N1ZVRlbXBsYXRlKCk6IHN0cmluZ1tdIHtcbiAgICByZXR1cm4gW1xuICAgICAgJ25hbWU6IPCfkJ4gQnVnJyxcbiAgICAgICdkZXNjcmlwdGlvbjogRmlsZSBhIGJ1Zy9pc3N1ZScsXG4gICAgICAndGl0bGU6IFwiW0JVR10gPHRpdGxlPlwiJyxcbiAgICAgICdsYWJlbHM6IFtcInR5cGU6IGJ1Z1wiXScsXG4gICAgICAnYm9keTonLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogQ3VycmVudCBiZWhhdmlvcicsXG4gICAgICBcIiAgICAgIGRlc2NyaXB0aW9uOiBBIGRlc2NyaXB0aW9uIG9mIHdoYXQgeW91J3JlIGV4cGVyaWVuY2luZy5cIixcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnJyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IEV4cGVjdGVkIGJlaGF2aW9yJyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogQSBkZXNjcmlwdGlvbiBvZiB3aGF0IHlvdSBleHBlY3RlZCB0byBoYXBwZW4uJyxcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnIyBHZW5lcmF0ZWQgYnkgcHJvamVuLiBUbyBtb2RpZnksIGVkaXQgLnByb2plbnJjLnRzIGFuZCBydW4gXCJucHggcHJvamVuXCIuJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIElzc3VlIHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIGZlYXR1cmUgY29uZmlndXJhdGlvbi5cbiAgICogQHJldHVybiBUZW1wbGF0ZSBmb3IgdGhlIGZlYXR1cmUgaXNzdWUgdGVtcGxhdGUgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBmZWF0dXJlSXNzdWVUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICduYW1lOiDwn5KhIEZlYXR1cmUnLFxuICAgICAgJ2Rlc2NyaXB0aW9uOiBSZXF1ZXN0IGZvciBhIG5ldyBmZWF0dXJlJyxcbiAgICAgICd0aXRsZTogXCJbRkVBVFVSRV0gPHRpdGxlPlwiJyxcbiAgICAgICdsYWJlbHM6IFtcInR5cGU6IGZlYXR1cmVcIl0nLFxuICAgICAgJ2JvZHk6JyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IERlc2NyaXB0aW9uJyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogQSBkZXNjcmlwdGlvbiBvZiB0aGUgZmVhdHVyZS4nLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcnLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogVGFzayBMaXN0JyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogRGVzY3JpYmUgdGhlIHN0ZXBzIHRvIGZ1bGZpbGwgdGhlIGZlYXR1cmUuJyxcbiAgICAgICcgICAgICB2YWx1ZTogfCcsXG4gICAgICAnICAgICAgICAtIFsgXSBNeSBGaXJzdCBUYXNrJyxcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnIyBHZW5lcmF0ZWQgYnkgcHJvamVuLiBUbyBtb2RpZnksIGVkaXQgLnByb2plbnJjLnRzIGFuZCBydW4gXCJucHggcHJvamVuXCIuJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIElzc3VlIHRlbXBsYXRlIGZvciB0aGUgR2l0SHViIGhvdXNla2VlcGluZyBjb25maWd1cmF0aW9uLlxuICAgKiBAcmV0dXJuIFRlbXBsYXRlIGZvciB0aGUgaG91c2VrZWVwaW5nIGlzc3VlIHRlbXBsYXRlIGZpbGUuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBnZXQgaG91c2VrZWVwaW5nSXNzdWVUZW1wbGF0ZSgpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIFtcbiAgICAgICduYW1lOiDwn5KhIEhvdXNla2VlcGluZycsXG4gICAgICAnZGVzY3JpcHRpb246IE1haW50ZW5hbmNlIG9yIHJlZmFjdG9yaW5nIHRhc2snLFxuICAgICAgJ3RpdGxlOiBcIltIT1VTRUtFRVBJTkddIDx0aXRsZT5cIicsXG4gICAgICAnbGFiZWxzOiBbXCJ0eXBlOiBob3VzZWtlZXBpbmdcIl0nLFxuICAgICAgJ2JvZHk6JyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IERlc2NyaXB0aW9uJyxcbiAgICAgICcgICAgICBkZXNjcmlwdGlvbjogQSBkZXNjcmlwdGlvbiBvZiB0aGUgaG91c2VrZWVwaW5nIHRhc2suJyxcbiAgICAgICcgICAgdmFsaWRhdGlvbnM6JyxcbiAgICAgICcgICAgICByZXF1aXJlZDogdHJ1ZScsXG4gICAgICAnJyxcbiAgICAgICcgIC0gdHlwZTogdGV4dGFyZWEnLFxuICAgICAgJyAgICBhdHRyaWJ1dGVzOicsXG4gICAgICAnICAgICAgbGFiZWw6IFRhc2sgTGlzdCcsXG4gICAgICAnICAgICAgZGVzY3JpcHRpb246IERlc2NyaWJlIHRoZSBzdGVwcyB0byBmdWxmaWxsIHRoZSBob3VzZWtlZXBpbmcgdGFzay4nLFxuICAgICAgJyAgICAgIHZhbHVlOiB8JyxcbiAgICAgICcgICAgICAgIC0gWyBdIE15IEZpcnN0IFRhc2snLFxuICAgICAgJyAgICB2YWxpZGF0aW9uczonLFxuICAgICAgJyAgICAgIHJlcXVpcmVkOiB0cnVlJyxcbiAgICAgICcjIEdlbmVyYXRlZCBieSBwcm9qZW4uIFRvIG1vZGlmeSwgZWRpdCAucHJvamVucmMudHMgYW5kIHJ1biBcIm5weCBwcm9qZW5cIi4nLFxuICAgIF07XG4gIH1cblxuICAvKipcbiAgICogVGVtcGxhdGUgZm9yIHRoZSBHaXRIdWIgUXVlc3Rpb24gSXNzdWUgY29uZmlndXJhdGlvbi5cbiAgICogQHJldHVybiBUZW1wbGF0ZSBmb3IgdGhlIHF1ZXN0aW9uIGlzc3VlIHRlbXBsYXRlIGZpbGUuXG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBnZXQgcXVlc3Rpb25Jc3N1ZVRlbXBsYXRlKCk6IHN0cmluZ1tdIHtcbiAgICByZXR1cm4gW1xuICAgICAgJ25hbWU6IOKdkyBRdWVzdGlvbicsXG4gICAgICAnZGVzY3JpcHRpb246IEFzayBhIHF1ZXN0aW9uJyxcbiAgICAgICd0aXRsZTogXCJbUVVFU1RJT05dIDx0aXRsZT5cIicsXG4gICAgICAnbGFiZWxzOiBbXCJ0eXBlOiBxdWVzdGlvblwiXScsXG4gICAgICAnYm9keTonLFxuICAgICAgJyAgLSB0eXBlOiB0ZXh0YXJlYScsXG4gICAgICAnICAgIGF0dHJpYnV0ZXM6JyxcbiAgICAgICcgICAgICBsYWJlbDogUXVlc3Rpb24nLFxuICAgICAgJyAgICAgIGRlc2NyaXB0aW9uOiBXaGF0IHdvdWxkIHlvdSBsaWtlIHRvIGtub3c/IElmIHlvdSBlbmNvdW50ZXIgdW51c3VhbCBiZWhhdmlvciBvciBpZGVudGlmaWVkIGEgbWlzc2luZyBmZWF0dXJlLCBjb25zaWRlciBvcGVuaW5nIGEgYnVnIHJlcG9ydCBpbnN0ZWFkLicsXG4gICAgICAnICAgIHZhbGlkYXRpb25zOicsXG4gICAgICAnICAgICAgcmVxdWlyZWQ6IHRydWUnLFxuICAgICAgJyMgR2VuZXJhdGVkIGJ5IHByb2plbi4gVG8gbW9kaWZ5LCBlZGl0IC5wcm9qZW5yYy50cyBhbmQgcnVuIFwibnB4IHByb2plblwiLicsXG4gICAgXTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDbGlmZiB0b21sIGNvbmZpZ3VyYXRpb24gZm9yIHRoZSBHaXRIdWIgY29uZmlndXJhdGlvbi5cbiAgICogVGhpcyBmaWxlIGlzIHVzZWQgYnkgcmVsZWFzZSB3b3JrZmxvdyB0byBjcmVhdGUgdGhlIENoYW5nZWxvZy5cbiAgICogQHJldHVybiBUZW1wbGF0ZSBmb3IgdGhlIGNsaWZmIHRvbWwgZmlsZS5cbiAgICogQHByb3RlY3RlZFxuICAgKi9cbiAgcHJvdGVjdGVkIGdldCBjbGlmZlRvbWxDb25maWd1cmF0aW9uKCk6IHN0cmluZ1tdIHtcbiAgICByZXR1cm4gW1xuICAgICAgJyMgfn4gR2VuZXJhdGVkIGJ5IHByb2plbi4gVG8gbW9kaWZ5LCBlZGl0IC5wcm9qZW5yYy50cyBhbmQgcnVuIFwibnB4IHByb2plblwiLicsXG4gICAgICAnJyxcbiAgICAgICdbY2hhbmdlbG9nXScsXG4gICAgICAnIyBjaGFuZ2Vsb2cgaGVhZGVyJyxcbiAgICAgICdoZWFkZXIgPSBcIlwiXCInLFxuICAgICAgJyMgQ2hhbmdlbG9nXFxuJyxcbiAgICAgICdBbGwgbm90YWJsZSBjaGFuZ2VzIHRvIHRoaXMgcHJvamVjdCB3aWxsIGJlIGRvY3VtZW50ZWQgaW4gdGhpcyBmaWxlLlxcbicsXG4gICAgICAnXCJcIlwiJyxcbiAgICAgICcjIHRlbXBsYXRlIGZvciB0aGUgY2hhbmdlbG9nIGJvZHknLFxuICAgICAgJyMgaHR0cHM6Ly9rZWF0cy5naXRodWIuaW8vdGVyYS9kb2NzLyNpbnRyb2R1Y3Rpb24nLFxuICAgICAgJ2JvZHkgPSBcIlwiXCInLFxuICAgICAgJ3slIGlmIHZlcnNpb24gJX1cXFxcJyxcbiAgICAgICcgICAgIyMgW3t7IHZlcnNpb24gfCB0cmltX3N0YXJ0X21hdGNoZXMocGF0PVwidlwiKSB9fV0gLSB7eyB0aW1lc3RhbXAgfCBkYXRlKGZvcm1hdD1cIiVZLSVtLSVkXCIpIH19JyxcbiAgICAgICd7JSBlbHNlICV9XFxcXCcsXG4gICAgICAnICAgICMjIFt1bnJlbGVhc2VkXScsXG4gICAgICAneyUgZW5kaWYgJX1cXFxcJyxcbiAgICAgICd7JSBmb3IgZ3JvdXAsIGNvbW1pdHMgaW4gY29tbWl0cyB8IGdyb3VwX2J5KGF0dHJpYnV0ZT1cImdyb3VwXCIpICV9JyxcbiAgICAgICcgICAgIyMjIHt7IGdyb3VwIHwgc3RyaXB0YWdzIHwgdHJpbSB8IHVwcGVyX2ZpcnN0IH19JyxcbiAgICAgICcgICAgeyUgZm9yIGNvbW1pdCBpbiBjb21taXRzICV9JyxcbiAgICAgICcgICAgICAgIC0geyUgaWYgY29tbWl0LnNjb3BlICV9Kih7eyBjb21taXQuc2NvcGUgfX0pKiB7JSBlbmRpZiAlfVxcXFwnLFxuICAgICAgJyAgICAgICAgICAgIHslIGlmIGNvbW1pdC5icmVha2luZyAlfVsqKmJyZWFraW5nKipdIHslIGVuZGlmICV9XFxcXCcsXG4gICAgICAnICAgICAgICAgICAge3sgY29tbWl0Lm1lc3NhZ2UgfCB1cHBlcl9maXJzdCB9fVxcXFwnLFxuICAgICAgJyAgICB7JSBlbmRmb3IgJX0nLFxuICAgICAgJ3slIGVuZGZvciAlfVxcXFwnLFxuICAgICAgJ1wiXCJcIicsXG4gICAgICAnIyB0ZW1wbGF0ZSBmb3IgdGhlIGNoYW5nZWxvZyBmb290ZXInLFxuICAgICAgJ2Zvb3RlciA9IFwiXCJcIicsXG4gICAgICAnPCEtLSBnZW5lcmF0ZWQgYnkgZ2l0LWNsaWZmIC0tPicsXG4gICAgICAnXCJcIlwiJyxcbiAgICAgICcjIHJlbW92ZSB0aGUgbGVhZGluZyBhbmQgdHJhaWxpbmcgcycsXG4gICAgICAndHJpbSA9IHRydWUnLFxuICAgICAgJyMgcG9zdHByb2Nlc3NvcnMnLFxuICAgICAgJ3Bvc3Rwcm9jZXNzb3JzID0gWycsXG4gICAgICAnICAjIHsgcGF0dGVybiA9IFwiPFJFUE8+XCIsIHJlcGxhY2UgPSBcImh0dHBzOi8vZ2l0aHViLmNvbS9vcmh1bi9naXQtY2xpZmZcIiB9LCAjIHJlcGxhY2UgcmVwb3NpdG9yeSBVUkwnLFxuICAgICAgJ10nLFxuICAgICAgJycsXG4gICAgICAnW2dpdF0nLFxuICAgICAgJyMgcGFyc2UgdGhlIGNvbW1pdHMgYmFzZWQgb24gaHR0cHM6Ly93d3cuY29udmVudGlvbmFsY29tbWl0cy5vcmcnLFxuICAgICAgJ2NvbnZlbnRpb25hbF9jb21taXRzID0gdHJ1ZScsXG4gICAgICAnIyBmaWx0ZXIgb3V0IHRoZSBjb21taXRzIHRoYXQgYXJlIG5vdCBjb252ZW50aW9uYWwnLFxuICAgICAgJ2ZpbHRlcl91bmNvbnZlbnRpb25hbCA9IHRydWUnLFxuICAgICAgJyMgcHJvY2VzcyBlYWNoIGxpbmUgb2YgYSBjb21taXQgYXMgYW4gaW5kaXZpZHVhbCBjb21taXQnLFxuICAgICAgJ3NwbGl0X2NvbW1pdHMgPSBmYWxzZScsXG4gICAgICAnIyByZWdleCBmb3IgcHJlcHJvY2Vzc2luZyB0aGUgY29tbWl0IG1lc3NhZ2VzJyxcbiAgICAgICdjb21taXRfcHJlcHJvY2Vzc29ycyA9IFsnLFxuICAgICAgJyAgIyBSZXBsYWNlIGlzc3VlIG51bWJlcnMnLFxuICAgICAgJyAgI3sgcGF0dGVybiA9IFwiKCh3K3MpPyMoWzAtOV0rKSlcIiwgcmVwbGFjZSA9IFwiKFsjJHsyfV0oPFJFUE8+L2lzc3Vlcy8kezJ9KSlcIn0sJyxcbiAgICAgICcgICMgQ2hlY2sgc3BlbGxpbmcgb2YgdGhlIGNvbW1pdCB3aXRoIGh0dHBzOi8vZ2l0aHViLmNvbS9jcmF0ZS1jaS90eXBvcycsXG4gICAgICAnICAjIElmIHRoZSBzcGVsbGluZyBpcyBpbmNvcnJlY3QsIGl0IHdpbGwgYmUgYXV0b21hdGljYWxseSBmaXhlZC4nLFxuICAgICAgJyAgI3sgcGF0dGVybiA9IFwiLipcIiwgcmVwbGFjZV9jb21tYW5kID0gXCJ0eXBvcyAtLXdyaXRlLWNoYW5nZXMgLVwiIH0sJyxcbiAgICAgICddJyxcbiAgICAgICcjIHJlZ2V4IGZvciBwYXJzaW5nIGFuZCBncm91cGluZyBjb21taXRzJyxcbiAgICAgICdjb21taXRfcGFyc2VycyA9IFsnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeZmVhdFwiLCBncm91cCA9IFwiPCEtLSAwIC0tPvCfmoAgRmVhdHVyZXNcIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5maXhcIiwgZ3JvdXAgPSBcIjwhLS0gMSAtLT7wn5CbIEJ1ZyBGaXhlc1wiIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXmRvY1wiLCBncm91cCA9IFwiPCEtLSAzIC0tPvCfk5ogRG9jdW1lbnRhdGlvblwiIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXnBlcmZcIiwgZ3JvdXAgPSBcIjwhLS0gNCAtLT7imqEgUGVyZm9ybWFuY2VcIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5yZWZhY3RvclwiLCBncm91cCA9IFwiPCEtLSAyIC0tPvCfmpwgUmVmYWN0b3JcIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5zdHlsZVwiLCBncm91cCA9IFwiPCEtLSA1IC0tPvCfjqggU3R5bGluZ1wiIH0sJyxcbiAgICAgICcgIHsgbWVzc2FnZSA9IFwiXnRlc3RcIiwgZ3JvdXAgPSBcIjwhLS0gNiAtLT7wn6eqIFRlc3RpbmdcIiB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5jaG9yZShyZWxlYXNlKTogcHJlcGFyZSBmb3JcIiwgc2tpcCA9IHRydWUgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeY2hvcmUoZGVwcy4qKVwiLCBza2lwID0gdHJ1ZSB9LCcsXG4gICAgICAnICB7IG1lc3NhZ2UgPSBcIl5jaG9yZShwcilcIiwgc2tpcCA9IHRydWUgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeY2hvcmUocHVsbClcIiwgc2tpcCA9IHRydWUgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJeY2hvcmV8XmNpXCIsIGdyb3VwID0gXCI8IS0tIDcgLS0+4pqZ77iPIE1pc2NlbGxhbmVvdXMgVGFza3NcIiB9LCcsXG4gICAgICAnICB7IGJvZHkgPSBcIi4qc2VjdXJpdHlcIiwgZ3JvdXAgPSBcIjwhLS0gOCAtLT7wn5uh77iPIFNlY3VyaXR5XCIgfSwnLFxuICAgICAgJyAgeyBtZXNzYWdlID0gXCJecmV2ZXJ0XCIsIGdyb3VwID0gXCI8IS0tIDkgLS0+4peA77iPIFJldmVydFwiIH0sJyxcbiAgICAgICddJyxcbiAgICAgICcjIHByb3RlY3QgYnJlYWtpbmcgY2hhbmdlcyBmcm9tIGJlaW5nIHNraXBwZWQgZHVlIHRvIG1hdGNoaW5nIGEgc2tpcHBpbmcgY29tbWl0X3BhcnNlcicsXG4gICAgICAncHJvdGVjdF9icmVha2luZ19jb21taXRzID0gZmFsc2UnLFxuICAgICAgJyMgZmlsdGVyIG91dCB0aGUgY29tbWl0cyB0aGF0IGFyZSBub3QgbWF0Y2hlZCBieSBjb21taXQgcGFyc2VycycsXG4gICAgICAnZmlsdGVyX2NvbW1pdHMgPSBmYWxzZScsXG4gICAgICAnIyByZWdleCBmb3IgbWF0Y2hpbmcgZ2l0IHRhZ3MnLFxuICAgICAgJyMgdGFnX3BhdHRlcm4gPSBcInZbMC05XS4qXCInLFxuICAgICAgJyMgcmVnZXggZm9yIHNraXBwaW5nIHRhZ3MnLFxuICAgICAgJyMgc2tpcF90YWdzID0gXCJcIicsXG4gICAgICAnIyByZWdleCBmb3IgaWdub3JpbmcgdGFncycsXG4gICAgICAnIyBpZ25vcmVfdGFncyA9IFwiXCInLFxuICAgICAgJyMgc29ydCB0aGUgdGFncyB0b3BvbG9naWNhbGx5JyxcbiAgICAgICd0b3BvX29yZGVyID0gZmFsc2UnLFxuICAgICAgJyMgc29ydCB0aGUgY29tbWl0cyBpbnNpZGUgc2VjdGlvbnMgYnkgb2xkZXN0L25ld2VzdCBvcmRlcicsXG4gICAgICAnc29ydF9jb21taXRzID0gXCJvbGRlc3RcIicsXG4gICAgICAnIyBsaW1pdCB0aGUgbnVtYmVyIG9mIGNvbW1pdHMgaW5jbHVkZWQgaW4gdGhlIGNoYW5nZWxvZy4nLFxuICAgICAgJyMgbGltaXRfY29tbWl0cyA9IDQyJyxcbiAgICBdO1xuICB9XG5cbiAgLyoqXG4gICAqIFdvcmtmbG93IHJlbGVhc2UgdGVtcGxhdGUgZm9yIHRoZSBHaXRIdWIgY29uZmlndXJhdGlvbi5cbiAgICogQHJldHVybiBPcHRpb25zIGZvciByZWxlYXNlIHdvcmtmbG93XG4gICAqIEBwcm90ZWN0ZWRcbiAgICovXG4gIHByb3RlY3RlZCBnZXQgcmVsZWFzZVdvcmtmbG93T3B0aW9ucygpOiBXb3JrZmxvd09wdGlvbnMge1xuICAgIHJldHVybiB7XG4gICAgICBvbjoge1xuICAgICAgICBwdWxsUmVxdWVzdDoge1xuICAgICAgICAgIGJyYW5jaGVzOiBbJ21haW4nXSxcbiAgICAgICAgICB0eXBlczogWydjbG9zZWQnXSxcbiAgICAgICAgfSxcbiAgICAgIH0sXG4gICAgICBqb2I6IHtcbiAgICAgICAgcnVuc09uOiBbJ3VidW50dS1sYXRlc3QnXSxcbiAgICAgICAgcGVybWlzc2lvbnM6IHtcbiAgICAgICAgICBjb250ZW50czogSm9iUGVybWlzc2lvbi5XUklURSxcbiAgICAgICAgICBwdWxsUmVxdWVzdHM6IEpvYlBlcm1pc3Npb24uV1JJVEUsXG4gICAgICAgIH0sXG4gICAgICAgIHN0ZXBzOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogJ0NyZWF0ZSByZWxlYXNlJyxcbiAgICAgICAgICAgIHVzZXM6ICdkeGZyb250aWVyL2doLWFjdGlvbi1yZWxlYXNlQG1haW4nLFxuICAgICAgICAgICAgd2l0aDoge1xuICAgICAgICAgICAgICBHSVRIVUJfVE9LRU46ICcke3sgc2VjcmV0cy5HSVRIVUJfVE9LRU4gfX0nLFxuICAgICAgICAgICAgICBCUkFOQ0g6ICdtYWluJyxcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgfTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSB0ZW1wbGF0ZSBmaWxlIGZvciBhIEdpdEh1YiBwdWxsIHJlcXVlc3QuXG4gICAqIEBwcml2YXRlXG4gICAqL1xuICBwcml2YXRlIGNyZWF0ZVB1bGxSZXF1ZXN0KCk6IHZvaWQge1xuICAgIG5ldyBQdWxsUmVxdWVzdFRlbXBsYXRlKHRoaXMucHJvamVjdC5naXRodWIhLCB7XG4gICAgICBsaW5lczogdGhpcy5wdWxsUmVxdWVzdFRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIGJ1ZyBpc3N1ZS5cbiAgICogQHByaXZhdGVcbiAgICovXG4gIHByaXZhdGUgY3JlYXRlQnVnSXNzdWUoKTogdm9pZCB7XG4gICAgbmV3IFRleHRGaWxlKHRoaXMucHJvamVjdCwgdGhpcy5idWdJc3N1ZUZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy5idWdJc3N1ZVRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIGZlYXR1cmUgaXNzdWUuXG4gICAqIEBwcml2YXRlXG4gICAqL1xuICBwcml2YXRlIGNyZWF0ZUZlYXR1cmVJc3N1ZSgpOiB2b2lkIHtcbiAgICBuZXcgVGV4dEZpbGUodGhpcy5wcm9qZWN0LCB0aGlzLmZlYXR1cmVJc3N1ZUZpbGVQYXRoLCB7XG4gICAgICBsaW5lczogdGhpcy5mZWF0dXJlSXNzdWVUZW1wbGF0ZSxcbiAgICB9KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSB0ZW1wbGF0ZSBmaWxlIGZvciBhIEdpdEh1YiBob3VzZWtlZXBpbmcgaXNzdWUuXG4gICAqIEBwcml2YXRlXG4gICAqL1xuICBwcml2YXRlIGNyZWF0ZUhvdXNla2VlcGluZ0lzc3VlKCk6IHZvaWQge1xuICAgIG5ldyBUZXh0RmlsZSh0aGlzLnByb2plY3QsIHRoaXMuaG91c2VrZWVwaW5nSXNzdWVGaWxlUGF0aCwge1xuICAgICAgbGluZXM6IHRoaXMuaG91c2VrZWVwaW5nSXNzdWVUZW1wbGF0ZSxcbiAgICB9KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSB0ZW1wbGF0ZSBmaWxlIGZvciBhIEdpdEh1YiBxdWVzdGlvbiBpc3N1ZS5cbiAgICogQHByaXZhdGVcbiAgICovXG4gIHByaXZhdGUgY3JlYXRlUXVlc3Rpb25Jc3N1ZSgpOiB2b2lkIHtcbiAgICBuZXcgVGV4dEZpbGUodGhpcy5wcm9qZWN0LCB0aGlzLnF1ZXN0aW9uSXNzdWVGaWxlUGF0aCwge1xuICAgICAgbGluZXM6IHRoaXMucXVlc3Rpb25Jc3N1ZVRlbXBsYXRlLFxuICAgIH0pO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgdGhlIHRlbXBsYXRlIGZpbGUgZm9yIGEgR2l0SHViIHJlbGVhc2Ugd29ya2Zsb3cuXG4gICAqIEBwcml2YXRlXG4gICAqL1xuICBwcml2YXRlIGNyZWF0ZVJlbGVhc2VXb3JrZmxvdygpOiB2b2lkIHtcbiAgICBjb25zdCB3b3JrZmxvdzogR2l0aHViV29ya2Zsb3cgfCB1bmRlZmluZWQgPSB0aGlzLnByb2plY3QuZ2l0aHViPy5hZGRXb3JrZmxvdygnUmVsZWFzZScpO1xuICAgIHdvcmtmbG93Py5vbih0aGlzLnJlbGVhc2VXb3JrZmxvd09wdGlvbnMub24pO1xuICAgIHdvcmtmbG93Py5hZGRKb2IoJ3JlbGVhc2UnLCB0aGlzLnJlbGVhc2VXb3JrZmxvd09wdGlvbnMuam9iKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDcmVhdGVzIHRoZSBjb25maWd1cmF0aW9uIGZpbGUgZm9yIHRoZSBjbGlmZiB0b21sIENIQU5HRUxPRyBjcmVhdGlvbiBpbiByZWxlYXNlIHdvcmtmbG93LlxuICAgKiBAcHJpdmF0ZVxuICAgKi9cbiAgcHJpdmF0ZSBjcmVhdGVDbGlmZlRvbWxDb25maWd1cmF0aW9uKCk6IHZvaWQge1xuICAgIG5ldyBUZXh0RmlsZSh0aGlzLnByb2plY3QsIHRoaXMuY2xpZmZUb21sRmlsZVBhdGgsIHtcbiAgICAgIGxpbmVzOiB0aGlzLmNsaWZmVG9tbENvbmZpZ3VyYXRpb24sXG4gICAgfSk7XG4gIH1cblxuICBwcm90ZWN0ZWQgYWRkVGVtcGxhdGVzKCk6IHZvaWQge1xuICAgIHRoaXMuY3JlYXRlUHVsbFJlcXVlc3QoKTtcbiAgICB0aGlzLmNyZWF0ZUJ1Z0lzc3VlKCk7XG4gICAgdGhpcy5jcmVhdGVGZWF0dXJlSXNzdWUoKTtcbiAgICB0aGlzLmNyZWF0ZUhvdXNla2VlcGluZ0lzc3VlKCk7XG4gICAgdGhpcy5jcmVhdGVRdWVzdGlvbklzc3VlKCk7XG5cbiAgICB0aGlzLmNyZWF0ZVJlbGVhc2VXb3JrZmxvdygpO1xuICAgIHRoaXMuY3JlYXRlQ2xpZmZUb21sQ29uZmlndXJhdGlvbigpO1xuICB9XG59XG4iXX0=