import { TextFile } from 'projen';
import { HuskyBase, TypeScriptProjectBase } from '../base';

/**
 * Husky builder implementing all relevant configuration for the project.
 */
export class Husky extends HuskyBase {
  /**
   * Initializes the Husky builder.
   * It calls the `initialize()` method immediately after invoking `super(project)`
   * to ensure that all necessary configuration steps are applied.
   * @param project The project to configure Husky for.
   */
  constructor(project: TypeScriptProjectBase) {
    super(project);
    this.initialize();
  }

  /**
   * File path to the Husky pre-push hook.
   * @return File path to pre-push hook file.
   * @protected
   */
  protected get prePushFilePath(): string {
    return '.husky/pre-push';
  }

  /**
   * Pre-push hook template for the Husky configuration.
   * @return Template for the pre-push hook file.
   * @protected
   */
  protected get prePushTemplate(): string[] {
    return ['# Generated by projen.To modify, edit.projenrc.ts and run "npx projen".', '', 'npm run build'];
  }

  /**
   * Creates the template file for the Husky pre-push hook.
   * @protected
   */
  protected createPrePushHook(): void {
    new TextFile(this.project, this.prePushFilePath, {
      lines: this.prePushTemplate,
    });
  }

  /**
   * @override
   */
  protected addTemplates(): void {
    super.addTemplates();
    this.createPrePushHook();
  }
}
